MediaArea/MediaInfoLib

Source/MediaInfo/Video/File_Ffv1.cpp
Source/MediaInfo/Video/File_Ffv1.h

Video/FFV1: use the quant_table_index for the context count by plane

---

Source/MediaInfo/Video/File_Ffv1.cpp

Video/FFV1: check if slices are initialized before cleaning them

---

Source/MediaInfo/Audio/File_Flac.cpp
Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Tag/File_VorbisCom.cpp

Fix FLAC Default Layouts

---

Source/MediaInfo/Multiple/File_Mk.cpp

It was comparing the track duration to "Generic Duration" instead of "General Duration" so the correct durations weren't being set.
I've been fiddling with the statistics tag code, I don't know if it's better or not.

Generic_Duration to General Duration

---

Source/MediaInfo/Video/File_Ffv1.cpp

Video/FFV1: finish to read the buffer with range coder

---

Source/MediaInfo/Multiple/File_Mpeg4.cpp
Source/MediaInfo/Multiple/File_Mpeg4.h
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

I doubt this is the final product, but it's a start.

Added m4v default, forced and references values.

---

Project/BCB/Library/MediaInfoLib.cbproj
Project/CMake/CMakeLists.txt
Project/CodeBlocks/Library/MediaInfoLib.cbp
Project/GNU/Library/Makefile.am
Project/MSVC2012/Library/MediaInfoLib.vcxproj
Project/MSVC2012/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2013/Library/MediaInfoLib.vcxproj
Project/MSVC2013/Library/MediaInfoLib.vcxproj.filters
Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_MinimizeSize.h
Source/MediaInfo/HashWrapper.cpp
Source/MediaInfo/HashWrapper.h
Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.h
Source/MediaInfo/Multiple/File_Mpeg4.cpp
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Riff.cpp
Source/MediaInfo/Multiple/File_Riff_Elements.cpp
Source/MediaInfo/Multiple/File__ReferenceFilesHelper.cpp
Source/MediaInfo/Multiple/File__ReferenceFilesHelper.h
Source/MediaInfo/Multiple/File__ReferenceFilesHelper_Sequence.cpp
Source/MediaInfo/Multiple/File__ReferenceFilesHelper_Sequence.h
Source/MediaInfo/Setup.h

Add SHA-1 and SHA-2 as potential hash functions in addition to current MD5
MI.Option("ParseSpeed", "1");
MI.Option("File_Hash", "MD5,SHA-1,SHA-224,SHA-256,SHA-384,SHA-512");

Hash wrapper

---

Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Multiple/File_Mk.h

slight modification of https://github.com/MediaArea/MediaInfoLib/pull/40

Matroska: get cover data

---

Source/Example/HowToUse_Dll.py
Source/Example/HowToUse_Dll3.py
Source/MediaInfoDLL/MediaInfoDLL.py
Source/MediaInfoDLL/MediaInfoDLL3.py

HowToUse_Dll.py and HowToUse_Dll3.py are same
MediaInfoDLL.py and MediaInfoDLL3.py are same
but all files are kept in order to not break programs calling them.

Python 2/3 files merge

---

Source/MediaInfo/Audio/File_Aac.cpp
Source/MediaInfo/Audio/File_Aac.h
Source/MediaInfo/Audio/File_Aac_GeneralAudio.cpp
Source/MediaInfo/Audio/File_Aac_GeneralAudio_Sbr.cpp
Source/MediaInfo/Audio/File_Aac_GeneralAudio_Sbr_Ps.cpp
Source/MediaInfo/Audio/File_Aac_Main.cpp
Source/MediaInfo/Audio/File_Aac_Others.cpp
Source/MediaInfo/Audio/File_Ac3.cpp
Source/MediaInfo/Audio/File_Mpega.cpp
Source/MediaInfo/Audio/File_SmpteSt0302.cpp
Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_MinimizeSize.h
Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Multiple/File_MpegPs.cpp

Creating generic timestamp functions, and modifying some parser in order to use these new functions.

Timestamp more precise

---

History_DLL.txt
Source/MediaInfo/Multiple/File_Mpeg_Psi.cpp

Analog, SCTE_mode_1 aka 64-QAM, SCTE_mode_2 aka 256-QAM, 8-VSB, 16-VSB

+ MPEG-TS: ATSC Modulation Mode

---

Source/MediaInfo/Multiple/File_MpegTs.cpp

Average of the PCR of all programs

x MPEG-TS: if several programs, compute of overall bit rate of all programs

---

Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

Bug 977 in the sourceforge issue tracker:
https://sourceforge.net/p/mediainfo/bugs/977/

x #B977 Fix ChannelLayout for mov files with channel bitmap

---

Project/OBS/deb9.debian/rules
debian/rules

Signed-off-by: Almin <almin@almin.tf>

x Disable --with-tinyxml in rules files

---

Project/MSVC2015/Library/MediaInfoLib.vcxproj

Signed-off-by: Jérôme Martinez <jerome@mediaarea.net>

Project/MSVC/2015: 2015 is not 2013

---

Project/GNU/Library/libmediainfo-config.in

Pkg-config: Stop to use bash

---

Source/MediaInfo/Audio/File_Aac.cpp
Source/MediaInfo/Audio/File_Mpega.cpp
Source/MediaInfo/Audio/File_SmpteSt0331.cpp
Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Video/File_Ffv1.cpp
Source/MediaInfo/Video/File_H263.cpp
Source/MediaInfo/Video/File_HuffYuv.cpp
Source/MediaInfo/Video/File_Mpeg4v.cpp
Source/MediaInfo/Video/File_Vc1.cpp
Source/MediaInfo/Video/File_Vp8.cpp
Source/MediaInfo/Video/File_Y4m.cpp

(for --Trace_Level=Container1;1)

More Trace_Layers_Update(8) when relevant

---

Source/MediaInfoDLL/MediaInfoDLL.py

https://github.com/MediaArea/MediaInfoLib/issues/144

Issue 144 (MacOS)

---

Source/MediaInfo/MediaInfoList_Internal.cpp

If we do this, it segfaults, so don't do it.

Don't try to print filename in XML output if input file doesn't exist.

---

Source/MediaInfo/Video/File_Ffv1.cpp
Source/MediaInfo/Video/File_Ffv1.h

Video/FFV1: check validity of the x and y pos of the slice in the frame

---

Source/MediaInfo/MediaInfo.h

Adding info about parameter per https://sourceforge.net/p/mediainfo/discussion/297610/thread/e4ca0ee0/

add info about integer parameter

---

Source/MediaInfo/Export/Export_EbuCore.cpp
Source/MediaInfo/MediaInfoList_Internal.cpp
Source/MediaInfo/MediaInfo_Inform.cpp

Fix for Embarcadero C++ Builder

+ --HTTPS=0 option for using HTTP in XML output

---

Source/MediaInfo/Video/File_Ffv1.cpp
Source/MediaInfo/Video/File_Ffv1.h

Memory leak removed, smaller trace

FFV1 update

---

Source/MediaInfo/MediaInfoList_Internal.cpp

x MultiThread: permits to check the state of a MediaInfoList from another thread
If MediaInfoList is launched from thread 1, thread 2 was not able to check MediaInfoList::State_Get()
(was blocking)

Multithread MediaInfoList

---

Project/CMake/CMakeLists.txt

Fixes compilation with MediaInfo app.

cmake: Add new file since 4e7f71dc

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_Buffer.cpp
Source/MediaInfo/File__Analyze_Element.cpp
Source/MediaInfo/File__Analyze_Element.h
Source/MediaInfo/File__Analyze_MinimizeSize.h
Source/MediaInfo/MediaInfoList_Internal.cpp
Source/MediaInfo/MediaInfo_Config.cpp
Source/MediaInfo/MediaInfo_Config.h

+ remove unused Element_End_Common_Flush_Build()

Trace: create a micro media trace in XML

---

Project/GNU/Library/test/Source/analyze.cpp
Project/GNU/Library/test/trace.sh
Project/GNU/Library/test/utils.sh

Test: add a test for testing micromediatrace with the MIL output

---

Source/MediaInfo/File__Analyze_Element.cpp

Trace: take into account the \0 when copying string

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_Element.cpp
Source/MediaInfo/File__Analyze_Element.h
Source/MediaInfo/Multiple/File_Mk.cpp

Element_Node related optimizations

---

Source/MediaInfo/MediaInfoList_Internal.cpp

Trace/Micro: remove new lines and spaces from the XML header

---

Source/MediaInfo/Video/File_Ffv1.cpp

FFV1: parse v0-v1

---

Project/GNU/libmediainfo.dsc
Project/GNU/libmediainfo.spec
Project/OBS/deb6.debian/control
Project/OBS/deb6.debian/rules
Project/OBS/deb6.dsc
Project/OBS/deb9.debian/control
Project/OBS/deb9.debian/rules
Project/OBS/deb9.dsc
debian/control
debian/rules

Add debug packages

---

Project/Qt/MediaInfoLib.pro

Fix Qt project file

---

.travis.yml

Add cmake travis test

---

Project/GNU/Library/Makefile.am
Project/GNU/PKGBUILD
Project/GNU/libmediainfo.spec
Project/OBS/deb6.debian/rules
Project/OBS/deb9.debian/rules
debian/rules

Install libmediainfo-config and libmediainfo.pc

---

Project/GNU/libmediainfo.spec

Remove libmediainfo-config from devel rpm

---

.travis.yml
Project/GNU/Library/test/Makefile.am
Project/GNU/Library/test/s3.sh

Add s3.sh to automake test suite

---

Project/GNU/Library/AddThisToRoot_DLL_compile.sh
Project/GNU/Library/configure.ac
Project/GNU/Library/libmediainfo-config.in

Build shared lib by default

---

Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.h
Source/MediaInfo/MediaInfo_Config_PerPackage.h
Source/MediaInfo/Multiple/File_DcpCpl.cpp
Source/MediaInfo/Multiple/File_MpegPs.cpp
Source/MediaInfo/Multiple/File_MpegTs.cpp
Source/MediaInfo/XmlUtils.cpp

Bunch of patchs taken from the modified source code in another (non public) repository.

Merge from another repo

---

Project/MSVC2015/Example/HowToUse_Dll.vcxproj
Project/MSVC2015/RegressionTest/RegressionTest.vcxproj

* Fix copy-paste AdditionalLibraryDirectories 2013 -> 2015
* Fix AdditionalDependencies link error:
RegressionTest.cpp
LINK : fatal error LNK1104: cannot open file 'ZenLib.lib'

Fix build VC++2015 

---

History_DLL.txt
Source/MediaInfo/Image/File_Bmp.cpp

https://sourceforge.net/p/mediainfo/feature-requests/485/

BMP height is negative

---

Source/MediaInfo/MediaInfo_Config.cpp

Fix build without libcurl

---

Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp

Fix typo from https://github.com/MediaArea/MediaInfoLib/pull/293
@pavel-pimenov

PR 293 fix

---

Source/MediaInfo/Audio/File_Als.cpp
Source/MediaInfo/Audio/File_Als.h
Source/MediaInfo/Audio/File_Ape.h
Source/MediaInfo/Audio/File_La.h
Source/MediaInfo/Audio/File_Rkau.h
Source/MediaInfo/Audio/File_Tta.cpp
Source/MediaInfo/Audio/File_Tta.h
Source/MediaInfo/Tag/File__Tags.h

 Add help-class File__UnCompressedSize_Helper

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_Element.cpp
Source/MediaInfo/File__Analyze_Element.h
Source/MediaInfo/Multiple/File_Mk.cpp

Matroska/Trace: do not print correct node (SimpleBlock level)

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_Element.cpp
Source/MediaInfo/File__Analyze_Element.h
Source/MediaInfo/Multiple/File_Mk.cpp

Matroska/Trace: Remove Cluster from the trace

---

Source/MediaInfo/File__Analyze_Element.cpp

Trace/Matroska: Remove Cluster tag from Trace if no error

---

Source/MediaInfo/Duplicate/File__Duplicate__Writer.cpp
Source/MediaInfo/Export/Export_EbuCore.cpp
Source/MediaInfo/Export/Export_Fims.cpp
Source/MediaInfo/Export/Export_Mpeg7.cpp
Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/MediaInfo_Config.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Source/MediaInfo/MediaInfo_Events.h
Source/MediaInfo/MediaInfo_Inform.cpp
Source/MediaInfo/MediaInfo_Internal.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Reader/Reader_libcurl.cpp
Source/MediaInfo/Tag/File_ApeTag.cpp
Source/MediaInfo/Tag/File_Id3v2.cpp
Source/MediaInfo/Tag/File_VorbisCom.cpp
Source/MediaInfo/Text/File_Ttml.cpp
Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_Hevc.cpp

http://www.viva64.com/en/w/V817/

Optimisation find("x")

---

Source/MediaInfo/Audio/File_DolbyE.cpp
Source/MediaInfo/Multiple/File_Lxf.cpp
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Multiple/File_MpegPs.cpp
Source/MediaInfo/Video/File_Ffv1.cpp
Source/MediaInfo/Video/File_Ffv1.h
Source/MediaInfo/Video/File_ProRes.cpp

x gcc warnings: -Wsign-compare

---

History_DLL.txt
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

and show the country number if unknown

+ MP4: more AppleStoreCountry values mapped to countries

---

Source/MediaInfoDLL/MediaInfoDLL.cpp

Max Pos = 2 (MB2WC(Handle, 2, OldParameter))

Unicode[8] -> Unicode[3]

---

Source/MediaInfo/Audio/File_Pcm.cpp
Source/MediaInfo/Audio/File_Pcm.h
Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.h
Source/MediaInfo/Multiple/File_Mpeg4.cpp
Source/MediaInfo/Multiple/File_Mpeg4.h
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

Better handling of corner cases for MOV demux + SplitAudio feature

MOV demux updates

---

Source/Example/HowToUse_Dll.py
Source/Example/HowToUse_Dll3.py

Add by buffer python example

---

Source/MediaInfo/Audio/File_Aac_GeneralAudio.h
Source/MediaInfo/Audio/File_Ac3.cpp
Source/MediaInfo/Audio/File_Mpega.cpp
Source/MediaInfo/Text/File_AribStdB24B37.cpp

https://randomascii.wordpress.com/2017/01/08/add-a-const-here-delete-a-const-there/

Move const data to readonly segment

---

Project/OBS/deb6.debian/control
Project/OBS/deb9.debian/control
debian/control

Fix minimal libzen version dependency

---

.appveyor.yml
README.md

Add .appveyor.yml

---

Source/MediaInfo/Text/File_SubRip.cpp
Source/MediaInfo/Video/File_Ffv1.cpp

Valgrind: remove memory problems

---

Source/MediaInfo/Text/File_SubRip.cpp

Valgrind: size is not index

---

History_DLL.txt

Signed-off-by: Guillaume Roques <guillaume.roques@gmail.com>

Preparing v0.7.92.1

---

Source/Resource/Text/DataBase/Format.csv

Complement asked in https://github.com/MediaArea/MediaInfo/pull/124/files
@JeromeMartinez I'm a little confuse with OpenMG and ATRAC3...so i added them to the already exixting ones.
Should i have added an WTV entry ?
https://msdn.microsoft.com/en-us/library/windows/desktop/bb188788.aspx

Complement to MediaInfo #124

---

History_DLL.txt
Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp

Thanks to @Sami32 for having provided the file.

MPEG-TS: Detection of Opus

---

Source/MediaInfo/Audio/File_Ac3.cpp

Actually also comment it as we don't need it for the moment.

x Compilation fix

---

Project/GNU/Library/AddThisToRoot_DLL_compile.sh

Build DLL with libcurl support

---

Project/GNU/libmediainfo.spec

Fix libcurl option for rhel/centos

---

Source/MediaInfo/MediaInfo_Config.cpp

If someone wants to display details from multiple categories using just one command line, entering the ‘\n’ as format line separator is quite tricky and awkward.
On Windows, it is actually impossible to do that (at least in cmd.exe).
In bash, you may enter ‘\n’, but once you entered ‘\n’, the command line portion before ‘\n’ would become in-editable.
One alternative way is to complement mediainfo with printf command:
mediainfo --output="`printf 'General;%%CompleteName%%,\nAudio;%%BitRate%%'`" some.mp3
Still quite awkward however.
So I worked out the enhancement to support using Escape-C string as output format.
The above command line can become:
mediainfo --output="cstr:// General;%CompleteName%,\nAudio;%BitRate%" some.mp3
I choose the “cstr://” prefix just to minimize potential impact to …

Added support using escape C string as output format.

---

Source/MediaInfo/Audio/File_Pcm.cpp
Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/Multiple/File_Mk.cpp

Signed-off-by: Guillaume Roques <guillaume.roques@gmail.com>

Remove some warnings

---

History_DLL.txt
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

https://sourceforge.net/p/mediainfo/bugs/1035/

MPEG-4: crash with some invalid CEA-608 packets (size of 0)

---

History_DLL.txt
Source/MediaInfo/Multiple/File_Mxf.cpp

fixing https://github.com/MediaArea/MediaInfo/issues/143

MXF with Acquisition Metadata: crash fixed

---

History_DLL.txt
Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Multiple/File_Mk.h
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Mxf.h

For Matroska and MXF.
Currently the limit is hard coded.

Trace: reduction of its size

---

Source/Resource/Text/DataBase/Format.csv

THD complement to MediaInfo #145

---

Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Multiple/File_Rm.cpp

Includes fix for https://github.com/MediaArea/MediaInfoLib/issues/474.

Small fixes

---

Source/MediaInfo/Audio/File_DolbyE.cpp
Source/MediaInfo/Audio/File_DolbyE.h
Source/MediaInfo/Audio/File_Dts.cpp
Source/MediaInfo/Audio/File_SmpteSt0302.cpp
Source/MediaInfo/Audio/File_SmpteSt0302.h
Source/MediaInfo/Audio/File_SmpteSt0337.cpp
Source/MediaInfo/Audio/File_SmpteSt0337.h
Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/Multiple/File_MpegPs.cpp
Source/MediaInfo/Multiple/File_MpegPs.h

Mostly Dolby E in MPEG-TS files, and DTS.

Fix frame count for a couple of formats

---

Source/MediaInfo/Multiple/File__ReferenceFilesHelper.cpp
Source/MediaInfo/Multiple/File__ReferenceFilesHelper_Sequence.cpp

The object (0x02EF1900) [size: 40 bytes] was created with new
Call Tree:
0x00A307C7(=PreRelease.exe:0x01:62F7C7) ..\..\..\Source\MediaInfo\Multiple\File__ReferenceFilesHelper.cpp#78
0x0076CAFC(=PreRelease.exe:0x01:36BAFC) ..\..\..\Source\MediaInfo\Multiple\File_Hls.cpp#138
0x0053C34E(=PreRelease.exe:0x01:13B34E) ..\..\..\Source\MediaInfo\File__Analyze.cpp#2092
0x00536E85(=PreRelease.exe:0x01:135E85) ..\..\..\Source\MediaInfo\File__Analyze.cpp#1056
0x005332D3(=PreRelease.exe:0x01:1322D3) ..\..\..\Source\MediaInfo\File__Analyze.cpp#695
0x006BC547(=PreRelease.exe:0x01:2BB547) ..\..\..\Source\MediaInfo\MediaInfo_Internal.cpp#833
0x00A5B24B(=PreRelease.exe:0x01:65A24B) ..\..\..\Source\MediaInfo\Reader\Reader_File.cpp#754
0x00A58E0F(=PreRelease.exe:0x01:657E0F) …

Memory leak rfh_common

---

Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Multiple/File_Mk.h

Handling buggy files if possible instead of rejecting them.

Matroska related updates

---

Source/MediaInfo/Export/Export_EbuCore.cpp

From https://sourceforge.net/p/mediainfo/bugs/1037/ and issues with frame rate values

EBUCore output nd rational numbers

---

Source/MediaInfo/Export/Export_EbuCore.cpp

Fix pow call for clang/old gcc

---

Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_Hevc.cpp

Add function Avc_Colorimetry_format_idc

---

Source/MediaInfo/Multiple/File_MpegTs.cpp

Update of https://github.com/MediaArea/MediaInfoLib/pull/504, complete file was sometimes parsed

MPEG-TS and BDAV false-positive fix, update

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.h

for speed setting per file instead of global only

File_ParseSpeed option

---

Source/MediaInfo/Video/File_Avc.cpp

https://github.com/MediaArea/MediaInfoLib/issues/477

AVC: fix hang when open .mpls from some 3D BD

---

Source/MediaInfo/Multiple/File_Mpeg4.cpp
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

Request from https://twitter.com/The_BFOOL/status/869633548214521856

 MPEG-4: display of recorded date from DV substream

---

Source/MediaInfo/Audio/File_Aac_GeneralAudio.cpp

Close https://github.com/MediaArea/MediaInfoLib/issues/518.

AAC: consider 4 back channels as 2 side + 2 back channels

---

Source/MediaInfo/Image/File_Dpx.cpp
Source/MediaInfo/Image/File_Dpx.h

https://sourceforge.net/p/mediainfo/bugs/1029/

DPX: endianess not considered with some fields in trace

---

Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Multiple/File_Mk.h

matroska: rename functions to match paths in the xml

---

Source/MediaInfo/Multiple/File_Mk.cpp

Also closes https://github.com/MediaArea/MediaInfoLib/issues/527.

Matroska: integrate all elements from Matroska specs, update

---

Source/MediaInfo/Multiple/File_Riff.h
Source/MediaInfo/Multiple/File_Riff_Elements.cpp

Not used by MediaInfo report for the moment

WAV: parsing of MPEG Audio extension "mext" chunk

---

Project/GNU/libmediainfo.spec

Mageia 6 and Fedora Rawhide compatibility

---

Source/MediaInfo/Audio/File_Mpega.cpp
Source/MediaInfo/Multiple/File_Flv.cpp
Source/MediaInfo/Multiple/File_Flv.h

FLV: support of FLV files with an ID3v2 header

---

Source/MediaInfo/Audio/File_Aac.cpp

AAC: ADTS/ADIF duration in case of full parsing and/or "risky bitrate estimation" option
and better support of non-48k frequencies

 AAC: ADTS/ADIF duration in case of full parsing

---

Source/MediaInfo/Audio/File_Speex.cpp

Close https://github.com/MediaArea/MediaInfoLib/issues/544

Speex: provide information also if version_id is more than 1

---

Source/MediaInfo/Video/File_Ffv1.cpp

FFV1: more tolerant to stream errors, update

---

Source/MediaInfo/Audio/File_Aac.cpp
Source/MediaInfo/Audio/File_Aac_GeneralAudio_Sbr.cpp
Source/MediaInfo/Audio/File_Ac3.cpp
Source/MediaInfo/Audio/File_Dts.cpp
Source/MediaInfo/Audio/File_Mpega.cpp
Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/Multiple/File_Flv.cpp
Source/MediaInfo/Multiple/File_Gxf_TimeCode.cpp
Source/MediaInfo/Multiple/File_Lxf.cpp
Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Multiple/File_Mpeg4.cpp
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Multiple/File_MpegTs.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Riff_Elements.cpp
Source/MediaInfo/Multiple/File_Skm.cpp
Source/MediaInfo/Multiple/File_Wm_Elements.cpp
Source/MediaInfo/Text/File_DvbSubtitle.cpp
Source/MediaInfo/Video/File_AfdBarData.cpp
Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_H263.cpp
Source/MediaInfo/Video/File_Hevc.cpp
Source/MediaInfo/Video/File_Mpeg4v.cpp
Source/MediaInfo/Video/File_Mpegv.cpp
Source/MediaInfo/Video/File_Vc1.cpp
Source/MediaInfo/Video/File_Vc3.cpp
Source/MediaInfo/Video/File_Vp8.cpp

Update with some fixes (was not working everywhere)

File_ParseSpeed option, update

---

Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.h
Source/MediaInfo/Reader/Reader_File.cpp
Source/MediaInfo/Reader/Reader_libcurl.cpp

For when we need to request termination from another thread.

File_RequestTerminate

---

Project/CMake/CMakeLists.txt

CMake: Use PkgConfig module

---

Source/MediaInfoDLL/MediaInfoDLL.pas

Signed-off-by: Jérôme Martinez <jerome@mediaarea.net>

Delphi XE8 64 bit support

---

Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Multiple/File_Mk.h

Will also fix https://github.com/MediaArea/MediaConch_SourceCode/issues/612.

Matroska, handling of files with Tracks element after Cluster elements

---

Source/MediaInfo/Export/Export_PBCore.cpp

Fix build with BCB

---

Project/CMake/CMakeLists.txt

Signed-off-by: Guillaume Roques <guillaume.roques@gmail.com>

Fix duplicate else in if block (fix error with cmake 3.9)

---

Source/MediaInfo/File__Analyze_Streams_Finish.cpp
Source/MediaInfo/MediaInfo_Internal.cpp

Ugly but fast implementation before a complete refactoring of human readable fields management is implemented.

EBUCore: WritingLibrary was missing if ReadByHuman option is set

---

Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp

Fix hangs on some files

---

.travis.yml
Project/GNU/Library/test/ebucore.sh
Project/GNU/Library/test/utils.sh
Source/MediaInfo/Export/Export_EbuCore.cpp
Source/MediaInfo/Export/Export_EbuCore.h
Source/MediaInfo/MediaInfo_Inform.cpp
Source/MediaInfo/OutputHelpers.cpp
Source/MediaInfo/OutputHelpers.h

EBUCore: Add JSON Output

---

Source/MediaInfo/Video/File_Mpegv.cpp

"Perceptual Quantization" easier to read and more known nowadays.
Replacement done without a lot of risks, as there is only few streams in the wild with PQ.

transfer_characteristics: SMPTE ST 2084 renamed to PQ

---

Source/MediaInfo/MediaInfoList_Internal.cpp
Source/MediaInfo/MediaInfo_Inform.cpp

Old crappy XML output becomes OLDXML and MIXML becomes XML

---

Source/MediaInfo/MediaInfo_Internal.cpp

x CS.leave() out of CSL scope

---

Release/Release_DLL_Windows_i386.bat
Release/Release_DLL_Windows_x64.bat
Source/Install/MediaInfo_DLL_Windows_i386.nsi
Source/Install/MediaInfo_DLL_Windows_x64.nsi

Build with MSVC 2017

---

Source/MediaInfo/Audio/File_Pcm.cpp
Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Multiple/File_Mk.h
Source/MediaInfo/Multiple/File_Riff.h
Source/MediaInfo/Multiple/File_Riff_Elements.cpp

After discussion in https://github.com/MediaArea/MediaInfoLib/issues/641

PCM in WAV and Matroska fixes

---

Source/MediaInfo/Export/Export_EbuCore.cpp

https://github.com/MediaArea/MediaInfo/issues/197

EBUCore: 1.8 Output uses now final version of XSD and final XSD location

---

Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Multiple/File_Mk.h

As there is no frame rate tag, this is empirical checks/guess of frame rate.

Matroska frame rate detection tweaks

---

Source/Install/MediaInfo_DLL_Windows_i386.nsi
Source/Install/MediaInfo_DLL_Windows_x64.nsi

Fix version number in nsi files

---

Source/MediaInfo/Multiple/File_Mk.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/669

Matroska: wrong color range info

---

Source/MediaInfo/Tag/File_Id3v2.cpp

Fixed equality comparison that must be an assignment.

---

Source/MediaInfo/Multiple/File_Mk.cpp

File_MK fix crash

---

Source/MediaInfo/MediaInfo_Internal.cpp

in MediaInfo::State_Get/set and MediaInfo_Config_MediaInfo::State_Get/Set

x double call to CSL

---

Project/CMake/CMakeLists.txt

Fix soname in cmake project

---

Source/MediaInfo/Multiple/File_Bdmv.cpp

From https://sourceforge.net/p/mediainfo/feature-requests/523/

 BDMV: Support of UHD Blu-ray playlist

---

Source/MediaInfo/Audio/File_Pcm.cpp
Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Multiple/File_Mk.h

Signed-off-by: Jérôme Martinez <jerome@mediaarea.net>

Endianness and Sign report for PCM Matroska tracks

---

Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.h
Source/MediaInfo/MediaInfo_Internal.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File__ReferenceFilesHelper.cpp

x errors with some DEFINE

---

Source/MediaInfo/File__Analyze_Buffer.cpp
Source/MediaInfo/File__Analyze_Buffer_MinimizeSize.cpp
Source/MediaInfo/File__Analyze_Element.cpp
Source/MediaInfo/Multiple/File_MpegPs.cpp
Source/MediaInfo/Multiple/File_MpegTs.cpp
Source/MediaInfo/Multiple/File__ReferenceFilesHelper.cpp

Valgrind errors

---

Source/MediaInfo/Multiple/File_Mxf.h

x infinite loop while parsing mxf with MEDIAINFO_TRACE_NO

---

Source/MediaInfo/Audio/File_Aac_GeneralAudio.cpp
Source/RegressionTest/RegressionTest_Basic.cpp

RegressionTest: Fix dup Time_Start = -1;

File_Aac: fix Infos["Format_Settings"] == L"NBC"

---

Project/GNU/Library/AddThisToRoot_DLL_compile.sh
Source/Example/HowToUse_Dll.html
Source/MediaInfoDLL/MediaInfoJS.cpp
Source/Resource/JavaScript/Post.js
Source/Resource/JavaScript/Pre.js

MediaInfoLib Emscripten interface

---

Source/MediaInfo/Setup.h

`MEDIAINFO_MIDO_*` instead of `MEDIAINFO_MIDI_*`

Typo in Setup.h

---

Release/CleanUp.bat

... add clean *.ipch,*.lastbuildstate *.tlog *.log *.VC.db (Visual C++)

Fix delete MediaInfoLib\Release\Example.ogg

---

Project/GNU/Library/AddThisToRoot_DLL_compile.sh

Build JavaScript module with 128mB memory space

---

Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/Video/File_Mpegv.cpp

thanks to @kodabb for some hints.

Some colour description related updates

---

Source/MediaInfo/Multiple/File_MpegPs.cpp
Source/MediaInfo/Multiple/File_MpegPs.h

File_MpegPs: Add Set_Unsynch_Frame_Count and Streams_Update

---

Source/MediaInfo/Multiple/File_Mpeg4.cpp

Fix https://github.com/MediaArea/MediaConch_SourceCode/issues/630

Field names must be with 7-bit codes

---

Source/MediaInfo/Image/File_Bmp.cpp

BMP: was wrongly considering 4-bit without palette as with palette

---

Source/MediaInfo/Export/Export_EbuCore.cpp
Source/MediaInfo/Export/Export_Fims.cpp
Source/MediaInfo/Export/Export_Mpeg7.cpp
Source/MediaInfo/Export/Export_PBCore.cpp
Source/MediaInfo/Export/Export_PBCore2.cpp

On Windows.
Ugly fix, waiting for refactoring of the whole thing.

 CLI: sometimes returning \r\r\n instead of \r\n

---

Source/MediaInfo/Export/Export_EbuCore.cpp
Source/MediaInfo/Export/Export_EbuCore.h
Source/MediaInfo/MediaInfo_Config.cpp
Source/MediaInfo/MediaInfo_Config.h
Source/MediaInfo/MediaInfo_Inform.cpp
Source/MediaInfo/OutputHelpers.h

EBUCore external metadata

---

Source/Example/HowToUse_Dll.html

Update JavaScript example

---

Source/MediaInfo/Export/Export_EbuCore.cpp

Use file name instead of id number for EBUCore external metadata

---

Source/MediaInfo/Multiple/File_DvDif.cpp
Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_Avc.h

[Voted feature request](https://mediaarea.net/Vote/Mpeg-Ts-Original-Encode-Date-147).
2nd commit is developed due to some curiosity about the content in the file I received, not complete and for the moment I just display iris F number and camera model name.

Consumer camera recording date/time 

---

Project/GNU/Library/test/Makefile.am
Project/GNU/Library/test/utils.sh
Project/GNU/Library/test/xml.sh

MediaInfo xml validity test

---

Source/Example/HowToUse_Dll.html
Source/Resource/JavaScript/Post.js

MediaInfoJs Open helper

---

Source/MediaInfo/Video/File_Hevc.cpp
Source/MediaInfo/Video/File_Mpegv.cpp

x uninitialised values

---

Source/MediaInfo/Multiple/File_MpegPs.cpp

1 file not updated in https://github.com/MediaArea/MediaInfoLib/pull/789 :(

Consumer camera recording date/time, update

---

Source/MediaInfo/Image/File_Jpeg.cpp
Source/MediaInfo/Image/File_Jpeg.h

```
<track type="Image">
<ColorSpace>YUV</ColorSpace>
<extra>
<ColorSpace_ICC>RGB</ColorSpace_ICC>
</extra>
</track>
```

JPEG: ICC parsing, display of ICC color space

---

Source/MediaInfo/Export/Export_EbuCore.cpp
Source/MediaInfo/Export/Export_PBCore.cpp
Source/MediaInfo/Export/Export_PBCore2.cpp
Source/MediaInfo/MediaInfo_Config.cpp
Source/MediaInfo/MediaInfo_Inform.cpp
Source/MediaInfo/MediaInfo_Internal.h
Source/MediaInfo/OutputHelpers.cpp
Source/MediaInfo/OutputHelpers.h
Source/MediaInfo/Setup.h

MediaInfo JSON output

---

Source/MediaInfo/Audio/File_Aac.cpp
Source/MediaInfo/Audio/File_Aac.h
Source/MediaInfo/Audio/File_Aac_GeneralAudio.cpp
Source/MediaInfo/Audio/File_Aac_GeneralAudio_Sbr.cpp
Source/MediaInfo/Audio/File_Aac_GeneralAudio_Sbr_Ps.cpp

with sometimes false-positive PS detection

AAC: SBR parsing issue with 3+ channel streams

---

Project/BCB/Dll/MediaInfo_i386.cbproj
Project/BCB/Library/MediaInfoLib.cbproj
Project/BCB/MediaInfoLib_Proj.groupproj
Project/BCB/PreRelease/PreRelease.cbproj
Project/CMake/CMakeLists.txt
Project/CodeBlocks/Library/MediaInfoLib.cbp
Project/GNU/Library/Makefile.am
Project/GNU/Library/configure.ac
Project/MSVC2013/Library/MediaInfoLib.vcxproj
Project/MSVC2013/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2015/Library/MediaInfoLib.vcxproj
Project/MSVC2015/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2017/Library/MediaInfoLib.vcxproj
Project/MSVC2017/Library/MediaInfoLib.vcxproj.filters
Source/MediaInfo/Image/File_Dpx.cpp
Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/MediaInfo/MediaInfo_File.cpp
Source/MediaInfo/Multiple/File_DcpAm.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Video/File_Av1.cpp
Source/MediaInfo/Video/File_Av1.h
Source/MediaInfo/Video/File_Mpegv.cpp
Source/Resource/Text/DataBase/CodecID_Video_Matroska.csv
Source/Resource/Text/DataBase/Format.csv

Raw (OBU) and in MKV.
Includes some changes in colour description labeling and crash fix

AV1: support of AOmedia AV1 based on latest specifications draft

---

Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/File__Analyze_Streams_Finish.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Mxf.h

MXF support is implemented thanks to [vote for MXF HDR metadata support](https://mediaarea.net/Vote/Mxf-Hdr-Metadata-Support-139)

HDR related stuff (MXF, HDR10...)

---

Source/MediaInfo/OutputHelpers.cpp

Fix compilation with Borland C++ Builder

---

Source/MediaInfo/MediaInfo_Inform.cpp

JSON output: fix newline

---

Source/MediaInfo/MediaInfo_Inform.cpp

Fix slash in numeric fields

---

Source/MediaInfo/MediaInfo_Inform.cpp

Add EBUCore_JSON Inform parameter

---

Project/MSVC2017/Library/MediaInfoLib_UWP.vcxproj
Project/MSVC2017/MediaInfoLib_UWP.sln
Source/MediaInfo/Reader/Reader_libcurl.cpp

UWP support

---

Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

'moov_trak_mdia_minf_stbl_stsd_Pos>1' second condition is always false

Fix Identical condition

---

Project/BCB/Library/MediaInfoLib.cbproj
Project/CMake/CMakeLists.txt
Project/GNU/Library/Makefile.am
Project/MSVC2013/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2015/Library/MediaInfoLib.vcxproj
Project/MSVC2015/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2017/Library/MediaInfoLib.vcxproj
Project/MSVC2017/Library/MediaInfoLib.vcxproj.filters
Project/Qt/MediaInfoLib.pro
Source/MediaInfo/Export/Export_EbuCore.cpp
Source/MediaInfo/Export/Export_Niso.cpp
Source/MediaInfo/Export/Export_Niso.h
Source/MediaInfo/MediaInfo_Config.cpp
Source/MediaInfo/MediaInfo_Config.h
Source/MediaInfo/MediaInfo_Inform.cpp
Source/MediaInfo/OutputHelpers.cpp
Source/MediaInfo/OutputHelpers.h
Source/MediaInfo/Setup.h

NISO Z39.87 output with External Metadata

---

Project/GNU/libmediainfo.spec

Make rpm relocatable

---

Source/MediaInfo/MediaInfo_Inform.cpp

Fix JSON escape

---

Source/MediaInfo/MediaInfo_Internal.cpp

Fix JSON output for multiple files

---

Source/ThirdParty/tinyxml2/tinyxml2.cpp
Source/ThirdParty/tinyxml2/tinyxml2.h

https://github.com/leethomason/tinyxml2/releases

TinyXML2 6.2

---

Source/MediaInfo/Export/Export_Mpeg7.cpp

MPEG-7: Fix some invalid xml fields

---

Source/MediaInfo/Export/Export_Mpeg7.cpp

MPEG-7: Fix Windows build

---

Source/MediaInfo/Export/Export_Niso.cpp

x Ambiguous call to std::pow

---

Source/MediaInfo/Export/Export_Mpeg7.cpp

MPEG-7: Fix some xml errors

---

Source/MediaInfo/Export/Export_Niso.cpp

x Ambiguous call to std::pow (fix for BCB and llvm)

---

Project/MSVC2017/Library/MediaInfoLib_UWP.vcxproj

Fix NISO sources in UWP project

---

Source/MediaInfo/Export/Export_Mpeg7.cpp

MPEG: x Text value in integer field

---

Project/GNU/libmediainfo.spec

RPM with version suffix for CentOS/RHEL

---

Project/GNU/libmediainfo.spec

RPM spec: revert to %define for some complex macros

---

Source/ThirdParty/tinyxml2/tinyxml2.h

Fix tinyxml2 visibility

---

Release/Release_DLL_Windows_i386.bat
Release/Release_DLL_Windows_x64.bat

Generate zip archive for Windows

---

Project/GNU/Library/configure.ac

Support for iPhoneOS/iPhoneSimulator in automake scripts

---

Source/MediaInfo/Export/Export_PBCore2.cpp

Fix unexpected behavior from https://github.com/MediaArea/MediaInfoLib/pull/929/files#diff-8de88b2673e7157b4ef71707f48f96c9L190.

Fix PBCore2 output essenceTrackTimeStart annotation

---

Source/MediaInfo/Audio/File_Aac_Main.cpp
Source/MediaInfo/MediaInfo_Internal.cpp

Display e.g. "AAC LC SBR PS" in Format field if HighestFormat option is set

Support of HighestFormat option for AAC

---

Source/MediaInfo/MediaInfo_Config.cpp
Source/MediaInfo/MediaInfo_Config.h

Fix https://github.com/MediaArea/MediaInfoLib/issues/953

Fix issue with some #defines

---

Source/MediaInfo/Audio/File_Aac_Main.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/836#issuecomment-413540900

ADTS CodecID

---

Source/MediaInfo/Reader/Reader_libcurl.cpp

This permits e.g. to manage temporary credentials (AssumeRole) through the use of x-amz-security-token header

HTTPS: support of AWS extension "x-amz-*" in HTTPS headers

---

Source/MediaInfo/File__Analyze_Buffer.cpp

Fix #965
@pavel-pimenov please confirm it is OK after this patch.

Prevent potential overflow if buffer is misused later during stream analysis

---

Source/MediaInfo/Export/Export_Mpeg7.cpp
Source/MediaInfo/Multiple/File_Riff_Elements.cpp

Includes some BWF (bext) updates.

MPEG-7 export update

---

Source/MediaInfo/Export/Export_Mpeg7.cpp
Source/MediaInfo/OutputHelpers.cpp
Source/MediaInfo/OutputHelpers.h

on the same line as FileSize element.

MPEG-7 output: display "Malformed file: truncated" in comments

---

Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/File__Analyze_Streams_Finish.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/982.

E-AC-3: fix extensions list for hybrid AC-3/E-AC-3 files

---

Source/MediaInfo/Text/File_Pdf.cpp

File_Pdf: Fix atoi (CodeGuard)

---

Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_Hevc.cpp

Floating point division by zero

---

Source/MediaInfo/Text/File_SubRip.cpp

SubRip: Fix potential invalid buffer read

---

Source/MediaInfo/Export/Export_Niso.cpp

Fix bug in NISO_Z39.87 with external metadata output

---

Source/MediaInfo/Audio/File_Ac3.cpp
Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp

Access overrun AC3_BitRate

---

Source/MediaInfo/Audio/File_Aac_Main.cpp

Access overrun Aac_sampling_frequency_Size

---

Source/MediaInfo/Tag/File_Id3v2.cpp

Fix https://github.com/MediaArea/MediaInfo/issues/298

ID3v2: fix wrong read of recording date in some cases

---

Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Video/File_ProRes.cpp

Extend https://github.com/MediaArea/MediaInfoLib/pull/1041 to more all formats.

Provide source of the color related metadata (container or stream)

---

Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/MediaInfo/Video/File_Hevc.cpp
Source/MediaInfo/Video/File_Hevc.h

SL-HDRx mode, spec version, payload mode

MPEG-TS: add support of parsing some ETSI TS 103-433 messages

---

Source/MediaInfo/Video/File_Hevc.cpp
Source/MediaInfo/Video/File_Hevc.h

Some uncommon slice types were not correctly handled.

HEVC: handle all slices the same manner

---

Source/MediaInfo/OutputHelpers.h

Consider replacing the expression 'RawContent(std::string())'

V815 Decreased performance.

---

Source/MediaInfoDLL/MediaInfoDLL.cpp

MediaInfoDll: MI_Outputs.find optimisation

---

Source/MediaInfo/Audio/File_Ac3.cpp

if(acmod_Max[Pos][Pos2]!=(int8u)-1) always true

Fix File_Ac3::Streams_Fill()

---

Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfoDLL/MediaInfoJS.cpp

V808 'ShowSource_List' object of 'map' type was created but was not utilized.

cppcheck PVS Studio warning

---

Source/MediaInfo/Multiple/File_Mk.cpp

Found from https://forum.videolan.org/viewtopic.php?t=142752&p=486513

Matroska: chapters timestamp were not display if chapters have no name

---

Source/MediaInfo/Audio/File_Aac.cpp
Source/MediaInfo/Audio/File_Aac.h
Source/MediaInfo/Audio/File_Aac_GeneralAudio.cpp
Source/MediaInfo/Audio/File_Aac_Main.cpp
Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/MediaInfo_Internal.cpp

AAC: better handling of corrupted/unknown streams

---

Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

Fix build on Windows/UWP

---

Source/MediaInfo/Multiple/File_Mpeg4.cpp

V781 Perhaps there is a mistake in program logic. Check lines: 2023, 2035. File_Mpeg4.cpp 2023

'mdhd_TimeScale' variable is checked after it was used.

---

Source/MediaInfo/Audio/File_SmpteSt0337.cpp
Source/MediaInfo/Multiple/File_Riff.cpp
Source/MediaInfo/Multiple/File_Riff_Elements.cpp

Source: https://sourceforge.net/p/mediainfo/bugs/1101/

Fix crashes with some invalid streams

---

LICENSE
License.html
Project/MSVC2013/Dll/MediaInfo.rc
Project/MSVC2013/Example/HowToUse.rc
Project/MSVC2013/ShellExtension/MediaInfoShellExt.rc
Project/MSVC2015/Dll/MediaInfo.rc
Project/MSVC2015/Example/HowToUse.rc
Project/MSVC2015/ShellExtension/MediaInfoShellExt.rc
Project/MSVC2017/Dll/MediaInfo.rc
Project/MSVC2017/Example/HowToUse.rc
Project/MSVC2017/ShellExtension/MediaInfoShellExt.rc
Project/MSVC2019/Dll/MediaInfo.rc
Project/MSVC2019/Example/HowToUse.rc
Project/MSVC2019/ShellExtension/MediaInfoShellExt.rc
Project/OBS/deb9.debian/copyright
debian/copyright

Update copyright year

---

Source/MediaInfo/Text/File_Ttml.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/1119

TTML: fix wrong output with standalone files

---

Source/MediaInfo/File__Analyze_Streams.cpp

One file update was missing in https://github.com/MediaArea/MediaInfoLib/pull/1122.

MP4 Spatial audio metadata, update

---

Project/CMake/CMakeLists.txt
Project/CMake/MediaInfo.rc

Handle vcpkg target in CMake project

---

Source/MediaInfo/Video/File_Vc3.cpp
Source/MediaInfo/Video/File_Vc3.h

Fix https://github.com/MediaArea/MediaInfo/issues/362.

VC-3: fix sub sampling with some v2 files

---

Project/GNU/libmediainfo.spec

Fix spec file for Mageia 7

---

Project/CMake/CMakeLists.txt

x Missing file for Windows in CMake project

---

Project/BCB/Library/MediaInfoLib.cbproj
Project/CMake/CMakeLists.txt
Project/CodeBlocks/Library/MediaInfoLib.cbp
Project/GNU/Library/Makefile.am
Project/MSVC2013/Library/MediaInfoLib.vcxproj
Project/MSVC2013/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2015/Library/MediaInfoLib.vcxproj
Project/MSVC2015/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2017/Library/MediaInfoLib.vcxproj
Project/MSVC2017/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2017/Library/MediaInfoLib_UWP.vcxproj
Project/MSVC2019/Library/MediaInfoLib.vcxproj
Project/MSVC2019/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2019/Library/MediaInfoLib_UWP.vcxproj
Project/Qt/MediaInfoLib.pro
Source/MediaInfo/Audio/File_Ac4.cpp
Source/MediaInfo/Audio/File_Ac4.h
Source/MediaInfo/File__MultipleParsing.cpp
Source/MediaInfo/MediaInfo_File.cpp
Source/MediaInfo/Multiple/File_Mpeg4.h
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Multiple/File_MpegPs.cpp
Source/MediaInfo/Multiple/File_MpegPs.h
Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp
Source/MediaInfo/Multiple/File_Mpeg_Descriptors.h
Source/MediaInfo/Setup.h

AC-4: basic detection

---

Source/MediaInfo/Text/File_SubRip.cpp

SubRip: bad handling of files having a quote character

---

Source/MediaInfo/MediaInfoList_Internal.cpp
Source/MediaInfo/MediaInfo_Config.cpp
Source/MediaInfo/MediaInfo_Config.h
Source/MediaInfo/MediaInfo_Internal.cpp

Option for resetting config

---

Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

MP4: do not show audio bit deph if it is the "default" 16

---

Source/MediaInfoDLL/MediaInfoDLL.cpp

x Memory leak in ASCII version of DLL interface

---

Source/MediaInfoDLL/MediaInfoDLL3.py

Fix characters encoding in Python3 ANSI API

---

Project/GNU/libmediainfo.spec

Fix OBS build for CentOS8

---

Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp

Fix typo File_Mpeg_Descriptors::Descriptor_7F_15

---

Source/MediaInfo/MediaInfo_Config.cpp

Remove Version.clear();

---

Source/MediaInfo/MediaInfo_Events.h
Source/MediaInfo/Multiple/File_DvDif.cpp
Source/MediaInfo/Multiple/File_DvDif.h
Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp

Info in events (not available by classic API)

[WIP] Detection of DV frame format change & DV errors per Dseq

---

Project/GNU/PKGBUILD
Project/GNU/libmediainfo.spec

RPM & Arch python packages

---

Project/GNU/libmediainfo.spec

Fix rpm python modules depencency

---

Source/MediaInfo/Multiple/File_DvDif.cpp
Source/MediaInfo/Multiple/File_DvDif.h
Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp

Fix https://github.com/mipops/dvrescue/issues/29

More detection of DV frame format change

---

Source/MediaInfo/Reader/Reader_libcurl.cpp

really permitting to use URL encoded or non URL encoded links.

URL encoding option fixes

---

LICENSE
License.html
Project/GNU/PKGBUILD
Project/MSVC2013/Example/HowToUse.rc
Project/MSVC2013/ShellExtension/MediaInfoShellExt.rc
Project/MSVC2015/Example/HowToUse.rc
Project/MSVC2015/ShellExtension/MediaInfoShellExt.rc
Project/MSVC2017/Example/HowToUse.rc
Project/MSVC2017/ShellExtension/MediaInfoShellExt.rc
Project/MSVC2019/Example/HowToUse.rc
Project/MSVC2019/ShellExtension/MediaInfoShellExt.rc
Project/OBS/deb9.debian/copyright
Source/MediaInfoDLL/MediaInfoDLL.rc
debian/copyright

Update copyright year and licence

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_Element.cpp
Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Riff_Elements.cpp

Fix https://github.com/sbraz/pymediainfo/issues/76#issuecomment-593392976.

Some 128-bit identifiers well not well displayed in multi-thread

---

Source/MediaInfo/Audio/File_Aac_Main.cpp
Source/MediaInfo/Audio/File_Usac.cpp

Includes some fixes in DRC parsing.

USAC: support of more channel configurations

---

Source/MediaInfo/File__Analyze_Buffer.cpp
Source/MediaInfo/File__Analyze_Buffer_MinimizeSize.cpp

File__Analyze::Get_MacRoman 

---

Source/MediaInfo/Multiple/File_Mk.cpp

https://github.com/MediaArea/MediaInfoLib/issues/1181
https://github.com/MediaArea/MediaInfo/issues/371

File_Mk - fix crash

---

Source/MediaInfo/Audio/File_Ac4.cpp
Source/MediaInfo/Audio/File_Ac4.h
Source/MediaInfo/Multiple/File_MpegTs.cpp
Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp

Handle some corner cases with AC-4 EHFR (Efficient high frame rate) streams and with AC-4 streams with unordered presentation IDs in MPEG-TS with preselection descriptor.

AC-4: full featured support (presentations, groups, substreams), update

---

Source/MediaInfo/MediaInfo_Inform.cpp

Fix crash with nested nodes in xml and json output

---

Source/MediaInfo/MediaInfo_Inform.cpp

Don't use translated StreamKind/String for XML/JSON attributes

---

Source/MediaInfoDLL/MediaInfoJNI.cpp

Fix IDE warnings in JNI interface

---

Source/MediaInfo/Reader/Reader_libcurl.cpp

URL encoding detection fix for URL having a query part

---

Source/MediaInfo/Video/File_Avc.cpp

Fix https://sourceforge.net/p/mediainfo/bugs/1123/

AVC: prioritize SPS bitrate info over other bitrate metadata

---

Source/MediaInfo/TimeCode.cpp

support timecode hours up to +/-99 before resorting to mod 24

---

Project/CMake/CMakeLists.txt

cmake_minimum_required() needs to be set before project()

---

Source/MediaInfo/Audio/File_Ac3.cpp
Source/MediaInfo/Audio/File_Ac3.h
Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/MediaInfo/Multiple/File_Mpeg4.h
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/Resource/Text/DataBase/CodecID_Audio_Mpeg4.csv

Fix https://github.com/MediaArea/MediaInfo/issues/451.

I451, MPEG-4: support of TrueHD

---

Source/MediaInfo/MediaInfo_Events.h
Source/MediaInfo/Multiple/File_DvDif.h
Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp

Partially resolves https://github.com/mipops/dvrescue/issues/66.

DV: add tests on captions

---

Source/MediaInfo/Audio/File_Opus.cpp

Fix https://github.com/MediaArea/MediaInfo/issues/461

Opus: fix wrong channel mapping

---

Source/MediaInfo/Audio/File_Mpegh3da.cpp
Source/MediaInfo/Audio/File_Mpegh3da.h
Source/MediaInfo/Multiple/File_Mpeg4.h
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

MP4: support of MPEG-H 3D Audio with CodecID mha1 (with mhaC atom)

---

Project/GNU/Library/AddThisToRoot_DLL_compile.sh
Project/GNU/Library/configure.ac

Remove hardcoded obsolete SDK paths and target version for macOS

---

Source/MediaInfo/File__Analyze_Streams_Finish.cpp
Source/MediaInfo/Multiple/File_Riff.cpp
Source/MediaInfo/Multiple/File_Riff_Elements.cpp

Fix https://sourceforge.net/p/mediainfo/bugs/971/

WAV: more precise sample count

---

Source/MediaInfo/Multiple/File_MpegPs.cpp

Fix [B1127](https://sourceforge.net/p/mediainfo/bugs/1127/).

MPEG-PS: Fix off by one read

---

Project/GNU/Library/configure.ac

Check for libdl requirement

---

Source/MediaInfo/File__Analyze.cpp

Fix https://github.com/MediaArea/MediaInfo/issues/487.

MPEG-TS: Fix crash with a specific file

---

Project/CMake/CMakeLists.txt
Project/GNU/Library/Makefile.am
Project/MSVC2013/Library/MediaInfoLib.vcxproj
Project/MSVC2013/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2015/Library/MediaInfoLib.vcxproj
Project/MSVC2015/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2017/Library/MediaInfoLib.vcxproj
Project/MSVC2017/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2019/Library/MediaInfoLib.vcxproj
Project/MSVC2019/Library/MediaInfoLib.vcxproj.filters
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Multiple/File_Riff_Elements.cpp
Source/MediaInfo/Setup.h
Source/MediaInfo/Video/File_CineForm.cpp
Source/MediaInfo/Video/File_CineForm.h

Color space including RGGB, bit depth...
In AVI and MOV/MP4.

CineForm: more details about CineForm streams

---

Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp

Accept duplicated packs.
After https://github.com/MediaArea/MediaInfoLib/pull/1320, it was remarked that e.g. FFmpeg inserts more than 1 instance of a VAUX pack. They are same so not so incoherent.

DVRescue: skip incoherent VAUX, update

---

Project/GNU/Library/configure.ac

Autotools: Add arm architecture for macOS

---

Source/MediaInfo/Audio/File_Ac3.cpp
Source/MediaInfo/Audio/File_Ac3.h

Solve https://github.com/MediaArea/MediaInfo/issues/472.
@Krobar in practice it seems I have no file with EX flag. Please provide a sample file so I can confirm that it works before merging this PR.

AC-3: EX and Pro Logic IIz detection

---

Source/MediaInfo/Image/File_Tiff.cpp

Fix https://github.com/MediaArea/MediaInfo/issues/508.

TIFF: fix division by 0

---

Source/MediaInfo/Video/File_Ffv1.cpp

Fix crash in ffv1 parser

---

Source/MediaInfo/Multiple/File_Mk.cpp

Fix https://github.com/mipops/dvrescue/issues/151.

Support of DV in Matroska

---

Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp

Fix https://github.com/mipops/dvrescue/issues/174.

DV: ignore invalid recdate

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_MinimizeSize.h
Source/MediaInfo/MediaInfo_Events_Internal.h
Source/MediaInfo/MediaInfo_Internal.cpp
Source/MediaInfo/MediaInfo_Internal.h
Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Source/MediaInfo/Multiple/File__ReferenceFilesHelper.cpp

Especially put zeroes in the whole event, also padding bytes

Events: refactor events initialization

---

Project/Mac/BR_extension_SO.sh
Project/Mac/Make_tarball.sh

Replace i386 arch by arm64 on macOS

---

Project/iOS/build.sh

Add build script for iOS

---

Source/MediaInfo/MediaInfo_Config.cpp

Fix double call to CriticalSectionLocker()

---

Source/MediaInfo/Reader/Reader_libcurl.cpp

Remove URL parameters from FileName

---

Source/MediaInfo/Reader/Reader_libcurl.cpp

Remove invalid character in comment

---

Source/MediaInfo/Multiple/File_Mpeg4.h
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/1353

MP4: Skip user data Xtra and free atoms

---

Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp

Update of https://github.com/MediaArea/MediaInfoLib/pull/1355.

DVRescue: read from stdin, update

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/Multiple/File_DvDif.cpp
Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp

DVRescue: read from stdin, update 2

---

Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_Avc.h

#1345 Added support List1 on B-Frames for AVC video format

---

Source/MediaInfo/File__Analyze_Buffer_MinimizeSize.cpp
Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/MediaInfo_Inform.cpp
Source/MediaInfo/OutputHelpers.cpp
Source/MediaInfo/OutputHelpers.h
Source/MediaInfo/Text/File_AribStdB24B37.cpp
Source/MediaInfo/Text/File_N19.cpp
Source/MediaInfo/Text/File_SubRip.cpp
Source/MediaInfo/Text/File_Teletext.cpp
Source/MediaInfo/Text/File_Ttml.cpp

Fix nonw wide char build

---

Project/GNU/Library/AddThisToRoot_DLL_compile.sh
Source/Example/HowToUse_Dll.html

Use non-wide char build for JavaScript module

---

Project/GNU/Library/AddThisToRoot_DLL_compile.sh
Project/JavaScript/ReadMe.txt
Source/Example/HowToUse_Dll.html
Source/Resource/JavaScript/Post.js
Source/Resource/JavaScript/Pre.js

JavaScript: Support emscripten v2.x

---

Project/GNU/Library/AddThisToRoot_DLL_compile.sh

JavaScript module: Reserve less memory at startup

---

Source/MediaInfo/MediaInfo_Internal.cpp

Fix for UWP and Borland C++ builder

---

Source/MediaInfo/MediaInfo_Config.cpp
Source/MediaInfo/MediaInfo_Config.h
Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/MediaInfo/MediaInfo_Inform.cpp

Add version to text output if requested

---

Source/MediaInfo/Image/File_Jpeg.cpp
Source/MediaInfo/Image/File_Jpeg.h

As to how should I do lossless JPEG, I dunno.
Again, lossless JPEG are markers  
SOF3 is Lossless (sequential), Huffman coding
SOF11: Lossless (sequential), arithmetic coding
SOF7: differential lossless process frame marker, Huffman coding
SOF15: differential lossless process frame marker, arithmetic coding

JPEG: zeros in markers are actually letters

---

Source/MediaInfo/MediaInfo_Config.cpp
Source/MediaInfo/MediaInfo_Config.h
Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/MediaInfo/MediaInfo_Inform.cpp

Add report creation timestamp to text output if requested

---

Source/MediaInfo/MediaInfo_Inform.cpp

After https://github.com/MediaArea/MediaInfoLib/pull/1385

Fix invalid UTC time

---

Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp

Update of https://github.com/MediaArea/MediaInfoLib/pull/1392.

DV: fix PTS/DUR info, caption part

---

Source/MediaInfo/MediaInfo_Inform.cpp

Add creatingLibrary field to JSON output

---

Project/MSVC2019/ShellExtension/MediaInfoShellExt.vcxproj
Release/Release_DLL_Windows_i386.bat
Release/Release_DLL_Windows_x64.bat
Source/Install/MediaInfo_DLL_Windows_i386.nsi
Source/Install/MediaInfo_DLL_Windows_x64.nsi

Use MSVC2019 for releases

---

Project/BCB/Library/MediaInfoLib.cbproj
Project/CMake/CMakeLists.txt
Project/GNU/Library/AddThisToRoot_DLL_compile.sh
Project/GNU/Library/Makefile.am
Project/GNU/Library/configure.ac
Project/GNU/Library/libmediainfo.pc.in
Project/MSVC2013/Library/MediaInfoLib.vcxproj
Project/MSVC2013/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2015/Library/MediaInfoLib.vcxproj
Project/MSVC2015/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2017/Library/MediaInfoLib.vcxproj
Project/MSVC2017/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2017/Library/MediaInfoLib_UWP.vcxproj
Project/MSVC2019/Library/MediaInfoLib.vcxproj
Project/MSVC2019/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2019/Library/MediaInfoLib_UWP.vcxproj
Project/Qt/MediaInfoLib.pro
Source/MediaInfo/Audio/File_Ac4.cpp
Source/MediaInfo/Export/Export_Graph.cpp
Source/MediaInfo/Export/Export_Graph.h
Source/MediaInfo/Export/Export_Graph_gvc_Include.h
Source/MediaInfo/MediaInfo_Config.cpp
Source/MediaInfo/MediaInfo_Config.h
Source/MediaInfo/MediaInfo_Inform.cpp
Source/MediaInfo/Setup.h

Graph output

---

Source/MediaInfo/MediaInfo_Inform.cpp

Prevent xml tag name to begin with number

---

Source/MediaInfo/Export/Export_Graph.cpp

Fix ADM detection in graphs

---

Source/MediaInfo/Export/Export_EbuCore.cpp

Fix EBUCore fields order and types

---

Source/MediaInfo/Audio/File_ChannelSplitting.cpp
Source/MediaInfo/Audio/File_ChannelSplitting.h

Some fixes after https://github.com/MediaArea/MediaInfoLib/pull/1419.

SMPTE ST 337: support of SMPTE ST 2116 (S-ADM in AES3), levels A1/A2/AX1/AX2, update

---

Source/MediaInfo/Audio/File_Adm.cpp

Fix C++03 compatibility

---

Source/MediaInfo/MediaInfo_Internal.cpp

Fix https://github.com/MediaArea/MediaInfo/issues/565.

Fix compilation issue with e.g. musl

---

Source/MediaInfo/Multiple/File_Mk.cpp

In some specific case the CRC32 compute of Matroska blocks does not take all needed bytes then indicates that a CRC32 is wrong but it is not true.

Matroska: fix false positive detection of bad CRC32

---

Source/MediaInfo/Text/File_SubRip.cpp

Fix https://github.com/MediaArea/MediaInfo/issues/566.

WebVTT: was not correctly handling WebVTT header with comment

---

Source/MediaInfo/Audio/File_ChannelSplitting.cpp

Also handle 32-bit mono SMPTE ST-337 in WAV/MOV

WAV: fix freeze with 32-bit PCM

---

Source/MediaInfo/Audio/File_Adm.cpp
Source/ThirdParty/tfsxml/tfsxml.c
Source/ThirdParty/tfsxml/tfsxml.h

XML content is decoded e.g. `&amp;`.

ADM: support of complex XML files

---

Source/MediaInfoDLL/MediaInfoJNI.cpp

Fix JNI interface

---

Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_MinimizeSize.h
Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Mxf.h
Source/MediaInfo/Video/File_Av1.cpp
Source/MediaInfo/Video/File_Av1.h
Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_Avc.h
Source/MediaInfo/Video/File_DolbyVisionMetadata.h
Source/MediaInfo/Video/File_Hevc.cpp
Source/MediaInfo/Video/File_Hevc.h

This permits forks to add generic light level tests

HDR light level in a centralized place

---

Source/MediaInfo/Image/File_Exr.cpp

Fix off-by-one issue when parsing EXR header flags

---

Source/MediaInfo/MediaInfo_Internal.cpp

Update MediaTrace schema version

---

Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.h

Fix https://github.com/MediaArea/MediaConch_SourceCode/issues/721.

Flag for DF / NDF for Media which does not denote drop frame

---

Source/MediaInfo/Text/File_Ttml.cpp
Source/MediaInfo/Text/File_Ttml.h
Source/MediaInfo/TimeCode.cpp

Fix https://github.com/MediaArea/MediaConch_SourceCode/issues/722.

TTML: Maximum count of lines per event includes overlapping times

---

Source/MediaInfo/Audio/File_DolbyAudioMetadata.cpp
Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/MediaInfo/TimeCode.cpp
Source/Resource/Text/Language/DefaultLanguage.csv

Example:
```
Audio
Dolby Atmos metadata                     : Yes
First frame of action                   : 00:00:09.97131
```

Dolby Audio Metadata: First frame of action

---

Project/CMake/CMakeLists.txt
Project/GNU/Library/Makefile.am
Project/Qt/MediaInfoLib.pro

Enable C++11

---

Source/MediaInfo/Multiple/File_Nsv.cpp
Source/MediaInfo/Multiple/File_Nsv.h

Proprietary format, not documented, implementation done by reverse engineering of the files.

NSV: StarDiva metadata support

---

Project/MSVC2017/Dll/MediaInfoDll.vcxproj
Project/MSVC2017/Library/MediaInfoLib.vcxproj
Project/MSVC2019/Dll/MediaInfoDll.vcxproj
Project/MSVC2019/Library/MediaInfoLib.vcxproj
Source/MediaInfo/Multiple/File_Nsv.cpp

Fix UWP build

---

Source/MediaInfo/Text/File_Cdp.cpp

Fix https://github.com/MediaArea/MediaInfo/issues/606.

CDP: better catching of wrong line21_field value

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/Multiple/File_Nsv.cpp

Especially with full scan and demux

NSV: better handling of invalid frames

---

Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/Resource/Text/Stream/Audio.csv
Source/Resource/Text/Stream/Other.csv
Source/Resource/Text/Stream/Text.csv

Fix type of VideoDelay

---

Source/MediaInfoDLL/MediaInfoDLL.h

Support DLL name provided by the calling program

---

Source/MediaInfo/Text/File_Eia708.cpp

https://github.com/MediaArea/MediaInfoLib/pull/1538 was missing a modified file.

CDP: readout of display aspect ratio, update

---

Source/MediaInfo/Multiple/File_Nsv.cpp

Fix of https://github.com/MediaArea/MediaInfoLib/commit/991466bd669e30f9e8b2d0b2d24ab64dcf2bcbfc#r73158743

NSV: better handling of buggy StarDiva agenda negative timestamps, update

---

Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/File__Analyze_Streams_Finish.cpp

Fix of https://github.com/MediaArea/MediaInfoLib/pull/1543, regression with some files.

Frame rate precise numerator/denominator also for text streams in MOV, fix

---

Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Mxf.h

Based on an early draft, not to be used in prod.

MXF, add FFV1 support

---

Source/MediaInfo/Multiple/File_DvDif.cpp

DV: timecode trace in HH:MM:SS:FF format

---

Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.cpp

Fix https://github.com/MediaArea/MediaConch/issues/231#issuecomment-1179644930

MOV/MPEG-4: List of QuickTime time code discontinuities, fix

---

Source/MediaInfo/MediaInfo_Inform.cpp

Fixes SF#1179 and https://github.com/MediaArea/MediaInfo/issues/629.

Fix array detection for JSON output

---

Source/MediaInfo/Text/File_Scc.cpp

Fix https://github.com/MediaArea/MediaInfo/issues/634.

SCC: fix TimeCode_Last

---

Source/MediaInfo/Multiple/File_Mpeg4.h
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

https://github.com/MediaArea/MediaInfoLib/pull/1555 was not complete.

Dolby Vision: add info about more profiles, update

---

Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp

Update of https://github.com/MediaArea/MediaInfoLib/pull/1556.

DV analysis: provide capture speed, update

---

Source/MediaInfo/Multiple/File_Mpeg4.cpp
Source/MediaInfo/Multiple/File_Mpeg4.h
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.cpp
Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.h

Handle corners cases like edit lists and/or non stripped streams.

MPEG-4/MOV: last time code value for all kind of QuickTime time codes 

---

Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/Text/File_Ttml.cpp

Close https://github.com/MediaArea/MediaInfo/issues/635.

Frame rate: store FrameRate_Num/Den also for integer values

---

Source/MediaInfo/Audio/File_Mpega.cpp
Source/MediaInfo/File_Other.cpp
Source/MediaInfo/Multiple/File_Ancillary.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Mxf.h
Source/ThirdParty/tfsxml/tfsxml.c

Thank you to the anonymous donor of crafted files triggering crashes or random behaviors.

Fixes after Fuzzing

---

Source/MediaInfo/Audio/File_Usac.cpp

Small update of https://github.com/MediaArea/MediaInfoLib/pull/1599 for coherency between new messages and deprecated messages.

USAC: sampling rate and IOD related checks, update

---

Source/MediaInfo/Audio/File_Aac.h

Fix build with MEDIAINFO_ADVANCED=NO

---

Project/GNU/libmediainfo.spec

Fix doc arch for versioned rpm package

---

Source/MediaInfo/OutputHelpers.cpp

Fix memory leak in JSON output

---

Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp

Fix https://sourceforge.net/p/mediainfo/bugs/1182/.

Teletext subtitle: prioritize subtitle metadata other overs

---

Source/MediaInfo/Multiple/File_Riff.h
Source/MediaInfo/Multiple/File_Riff_Elements.cpp

Detection only, actually it is still not supported for reading out fields.

AVI/WAV: detection of character set

---

Source/MediaInfo/MediaInfo_Internal.cpp

Fix crash with stdin input and ctrl-c

---

Source/MediaInfo/Text/File_SubRip.cpp

Follow up of https://github.com/MediaArea/MediaInfoLib/pull/1623, part of https://github.com/MediaArea/MediaInfo/issues/654.

WebVTT: support of overlapping blocks

---

Source/MediaInfo/Multiple/File_Mk.cpp

Fix https://sourceforge.net/p/mediainfo/discussion/297609/thread/a7218c395d/

Matroska: add support of DATE_ENCODED, DATE_RECORDED, DATE_TAGGED

---

Source/MediaInfo/Audio/File_Dts.cpp

Fix https://github.com/MediaArea/MediaInfo/issues/662.

WAV: fix false-positive detection of DTS in PCM

---

Source/MediaInfo/MediaInfo_Inform.cpp

Remove minus sign from names for JSON/XML output

---

Project/GNU/libmediainfo.spec

rpm: add support for rhel 9 and derivates

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/Multiple/File_MiXml.cpp

Fix infinite loop

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.h
Source/MediaInfo/MediaInfo_Inform.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Mxf.h

MXF only for the moment.
With ` --ParseSpeed=1 --Output=TimecodeXML`

Extract of time codes, XML format

---

Source/MediaInfo/Video/File_Ffv1.cpp

Fix use of NULL Buffer

---

Source/MediaInfo/MediaInfo_Internal.cpp

Avoid destruction of Cin object while running

---

Source/MediaInfo/Audio/File_Aac_GeneralAudio.cpp

Fix https://github.com/MediaArea/MediaInfo/issues/675

ER AAC ELD: support of ER AAC ELD sbr_header

---

Source/MediaInfo/Audio/File_Aac.h
Source/MediaInfo/Audio/File_Aac_GeneralAudio_Sbr.cpp
Source/MediaInfo/MediaInfo_Internal.cpp

Fix https://github.com/MediaArea/MediaInfo/issues/676.

AAC: detection of eSBR (and fix of random wrong PS detection)

---

Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_Avc.h
Source/MediaInfo/Video/File_Mpegv.cpp

Detection of "sub" profiles e.g. "Constrained Baseline" or "Progressive High"

AVC: detection of more profiles

---

Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/Resource/Text/Language/DefaultLanguage.csv

Fix https://github.com/MediaArea/MediaInfoLib/issues/1683.

Fix typo "Chinese (Simplified)"

---

Source/MediaInfo/Export/Export_Fims.cpp
Source/MediaInfo/Export/Export_Mpeg7.cpp
Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/Multiple/File_Flv.cpp
Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Multiple/File_Mpeg_Psi.cpp
Source/MediaInfo/Multiple/File_P2_Clip.cpp
Source/MediaInfo/Multiple/File_Wm_Elements.cpp
Source/MediaInfo/OutputHelpers.cpp
Source/MediaInfo/Tag/File_Id3v2.cpp
Source/MediaInfo/Tag/File_VorbisCom.cpp
Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_Mpeg4v.cpp

Date/time nearly in ISO format, better guess of some date/time formatting from input.

Normalization of date/time in report

---

Source/MediaInfo/Audio/File_Ac4.cpp
Source/MediaInfo/File__Analyze_Streams_Finish.cpp

AC-4 and MPEG-H 3D Audio: Merged channel layout

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_Avc.h

Fix https://github.com/MediaArea/MediaInfoLib/issues/1701.

AVC: fix PTS of last frame

---

Source/MediaInfo/Audio/File_Adm.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/1703.

Fix a compilation error with some compilers

---

Source/MediaInfo/Audio/File_Flac.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/1709

FLAC: fix sampling count

---

Source/Resource/Text/Stream/Audio.csv
Source/Resource/Text/Stream/General.csv
Source/Resource/Text/Stream/Generic.csv
Source/Resource/Text/Stream/Image.csv
Source/Resource/Text/Stream/Menu.csv
Source/Resource/Text/Stream/Text.csv
Source/Resource/Text/Stream/Video.csv

This PR is for filling out and clarifying values in MediaInfo's `--Info-Parameters` page. 
Now ready for review!

Update parameter definitions

---

Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/Resource/Text/Stream/General.csv

Fix display of stream size for general part

Update parameter definitions, update

---

Source/MediaInfo/Multiple/File_Mpeg4.h
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Video/File_Hevc.cpp
Source/MediaInfo/Video/File_Hevc.h

Close https://github.com/MediaArea/MediaInfoLib/issues/1649

Add HDR Vivid support

---

Source/MediaInfo/Audio/File_Usac.cpp

Advanced USAC conformance checks are not fully ready, disabling them for the next public release

USAC: revert conformance checks

---

Project/BCB/Library/MediaInfoLib.cbproj
Project/CMake/CMakeLists.txt
Project/GNU/Library/Makefile.am
Project/GNU/Library/configure.ac
Project/MSVC2013/Library/MediaInfoLib.vcxproj
Project/MSVC2013/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2015/Library/MediaInfoLib.vcxproj
Project/MSVC2015/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2017/Library/MediaInfoLib.vcxproj
Project/MSVC2017/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2017/Library/MediaInfoLib_UWP.vcxproj
Project/MSVC2019/Library/MediaInfoLib.vcxproj
Project/MSVC2019/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2019/Library/MediaInfoLib_UWP.vcxproj
Project/MSVC2022/Library/MediaInfoLib.vcxproj
Project/MSVC2022/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2022/Library/MediaInfoLib_UWP.vcxproj
Project/Qt/MediaInfoLib.pro
Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Setup.h
Source/MediaInfo/Video/File_Vp9.cpp
Source/MediaInfo/Video/File_Vp9.h

VP9: initial support

---

Source/MediaInfo/Multiple/File_Mpeg4.h
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

Thumbnail information is in a dedicated image track.

MP4: more information about thumbnails

---

Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp

Fix division by 0 + fix the descriptor parsing

MPEG-TS: fix crash in HEVC_timing_and_HRD

---

Source/MediaInfo/Multiple/File_Mk.cpp

Matroska: fix crash in support of HDR10+

---

Source/MediaInfo/Multiple/File__ReferenceFilesHelper.cpp

Also display the source field without URL encoding.
Fix https://github.com/MediaArea/MediaInfoLib/issues/1759
Temporary in MediaInfoLib in order [to avoid another release of ZenLib](https://github.com/MediaArea/ZenLib/pull/149) soon.

Reference files: fix handling of URL encoded with UTF-8 content

---

Project/BCB/Library/MediaInfoLib.cbproj
Project/CMake/CMakeLists.txt
Project/CodeBlocks/Library/MediaInfoLib.cbp
Project/GNU/Library/Makefile.am
Project/GNU/Library/configure.ac
Project/MSVC2013/Library/MediaInfoLib.vcxproj
Project/MSVC2013/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2015/Library/MediaInfoLib.vcxproj
Project/MSVC2015/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2017/Library/MediaInfoLib.vcxproj
Project/MSVC2017/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2017/Library/MediaInfoLib_UWP.vcxproj
Project/MSVC2019/Library/MediaInfoLib.vcxproj
Project/MSVC2019/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2019/Library/MediaInfoLib_UWP.vcxproj
Project/MSVC2022/Library/MediaInfoLib.vcxproj
Project/MSVC2022/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2022/Library/MediaInfoLib_UWP.vcxproj
Project/Qt/MediaInfoLib.pro
Source/MediaInfo/Audio/File_Adm.cpp
Source/MediaInfo/Audio/File_Mga.cpp
Source/MediaInfo/Audio/File_Mga.h
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Mxf.h
Source/MediaInfo/Setup.h

S-ADM: support of SMPTE ST 2127-1 / SMPTE ST 2109 / SMPTE ST 2127-10

---

Source/MediaInfo/Video/File_Hevc.cpp

It is [also for DVB](https://www.etsi.org/deliver/etsi_ts/103500_103599/103572/01.03.01_60/ts_103572v010301p.pdf), so more generic output.

HEVC: support of SMPTE ST 2094-10, update

---

Source/MediaInfo/MediaInfo_File.cpp
Source/MediaInfo/Multiple/File_Ancillary.cpp
Source/MediaInfo/Multiple/File_Ancillary.h
Source/MediaInfo/Multiple/File_MpegPs.cpp
Source/MediaInfo/Multiple/File_MpegPs.h
Source/MediaInfo/Text/File_Eia608.cpp

Include captions, time codes, etc.

MPEG-TS: support of SMPTE ST 2038 (ancillary data)

---

Source/MediaInfo/Video/File_AfdBarData.cpp
Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_Hevc.cpp
Source/MediaInfo/Video/File_Hevc.h
Source/MediaInfo/Video/File_Mpegv.cpp

and small rework of MPEG Video related DAR detection

AVC & HEVC: active format description

---

Source/MediaInfo/Audio/File_Ac3.cpp
Source/MediaInfo/Multiple/File_Mpeg4.cpp
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

In `moov/trak/udta/kind` atom, with DASH dictionary.

MP4: support of service kind

---

Source/MediaInfo/Export/Export_Mpeg7.cpp
Source/MediaInfo/Export/Export_Mpeg7.h
Source/MediaInfo/MediaInfo_Inform.cpp

Rework on custom extension of the XSD.
Needs https://github.com/MediaArea/MediaAreaXml/pull/61.

MPEG-7 output update

---

Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_MinimizeSize.h
Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp
Source/MediaInfo/Multiple/File_Mpeg_Descriptors.h
Source/MediaInfo/Multiple/File_Mpeg_Psi.cpp

[H.222.0:2022](https://www.itu.int/rec/T-REC-H.222.0)
[ISO/IEC 21122-2:2022](https://www.iso.org/standard/81552.html)
[ISO/IEC 21122-2:2022](https://www.iso.org/standard/81553.html)

MPEG-TS: support of JPEG XS

---

Source/MediaInfo/File__Analyze_Streams.cpp

Fix https://github.com/MediaArea/MediaConch_SourceCode/issues/752.

URL: remove query part of the URL in the FileExtension field

---

Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Video/File_Hevc.cpp
Source/MediaInfo/Video/File_Hevc.h

With files from https://dvb.org/specifications/verification-validation/hdr-test-content/.

HDR: display of all formats if more than 1 format is detected

---

Source/MediaInfo/Export/Export_Mpeg7.cpp
Source/MediaInfo/File__Analyze_Streams_Finish.cpp
Source/MediaInfo/Multiple/File_Mpeg4.cpp
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

from `tagc` atom.
Fix https://github.com/MediaArea/MediaInfoLib/issues/1793.

MP4: support of media characteristic (spoken dialog, translation, easy to read...)

---

Source/MediaInfo/Export/Export_Mpeg7.cpp

Needs https://github.com/MediaArea/MediaAreaXml/pull/62

MPEG-7 update (MediaTime for text, TotalNumOfSamples)

---

Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

Handle https://github.com/MediaArea/MediaInfoLib/issues/1793#issuecomment-1594502193.

MP4: verbose support of media characteristic

---

Project/MSVC2013/Library/MediaInfoLib.vcxproj
Project/MSVC2015/Library/MediaInfoLib.vcxproj
Project/MSVC2017/Library/MediaInfoLib.vcxproj
Project/MSVC2017/Library/MediaInfoLib_UWP.vcxproj
Project/MSVC2019/Library/MediaInfoLib.vcxproj
Project/MSVC2019/Library/MediaInfoLib_UWP.vcxproj
Project/MSVC2022/Dll/MediaInfoDll.vcxproj
Project/MSVC2022/Library/MediaInfoLib.vcxproj
Project/MSVC2022/Library/MediaInfoLib_UWP.vcxproj
Source/MediaInfo/Audio/File_Ac3.cpp
Source/MediaInfo/Audio/File_Aptx100.cpp
Source/MediaInfo/Audio/File_DolbyAudioMetadata.cpp
Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/MediaInfo_Events_Internal.h
Source/MediaInfo/Multiple/File_DvDif.cpp
Source/MediaInfo/Multiple/File_Gxf.cpp
Source/MediaInfo/Multiple/File_Mpeg4.cpp
Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Nsv.cpp
Source/MediaInfo/Text/File_N19.cpp
Source/MediaInfo/Text/File_Scc.cpp
Source/MediaInfo/Text/File_Ttml.cpp
Source/MediaInfo/TimeCode.cpp
Source/MediaInfo/TimeCode.h
Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_Hevc.cpp
Source/MediaInfo/Video/File_Mpegv.cpp

Better management of additions, subtractions, especially with different frame rates

TimeCode: refactoring of timecode handler

---

Source/MediaInfo/Audio/File_Usac.cpp

Needs https://github.com/MediaArea/MediaArea-Website/pull/473

USAC conformance checker: sbgp presence check

---

Source/MediaInfo/Tag/File_Id3.cpp
Source/MediaInfo/Tag/File_Id3v2.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/1414#issuecomment-1611996935.

ID3/ID3v2: fix (again) missing report of Blues genre

---

Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_Hevc.cpp

Also synchronize HEVC and AVC time code parsing

AVC: time code

---

Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/Resource/Text/DataBase/CodecID_Video_Mpeg4.csv

+ brvn
I'll keep these coming if I find any more :)

Added another Blackmagic RAW Codec ID

---

Source/MediaInfo/Video/File_Avc.cpp
Source/MediaInfo/Video/File_Hevc.cpp

Fix https://github.com/MediaArea/MediaInfo/issues/754.

AVC&HEVC: fix risk of crash with some streams

---

Source/MediaInfo/Archive/File_Iso9660.cpp
Source/MediaInfo/Archive/File_Iso9660.h

PublisherIdentifier, CopyrightIdentifier, CreationDateTime

ISO9660: more metadata

---

Source/MediaInfo/Export/Export_Mpeg7.cpp
Source/MediaInfo/MediaInfo_Config.cpp
Source/MediaInfo/MediaInfo_Config.h
Source/MediaInfo/MediaInfo_Inform.cpp
Source/MediaInfo/Multiple/File_Dvdv.cpp
Source/MediaInfo/Multiple/File_Dvdv.h
Source/MediaInfo/Multiple/File_MpegPs.cpp

Also better support of ISO having several episodes.

MPEG-7: tweaking of the output for DVD Video in ISO

---

Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/Resource/Text/Language/DefaultLanguage.csv

Fix https://github.com/MediaArea/MediaInfoLib/issues/1869.

Languages: add 'fil' (Filipino)

---

Source/MediaInfo/Audio/File_Mpegh3da.cpp
Source/MediaInfo/Multiple/File_MpegPs.cpp

Also avoid some wrong detection of MPEG-H 3D Audio as MPEG Audio.

MPEG-TS: display of all metadata for MPEG-H 3D Audio in MPEG-TS

---

Source/MediaInfo/File__Analyze_Streams_Finish.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/1880.

MXF: fix incorrect pixel aspect ratio

---

Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_MinimizeSize.h
Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/1884.

MXF: fix duplicate frame count / frame rate values

---

Source/MediaInfo/Multiple/File_Riff.cpp
Source/MediaInfo/Multiple/File_Riff_Elements.cpp

It handles better a couple of corner cases.
Needed for one of the next PR.

RIFF: update 2-byte alignment handling

---

Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_Buffer.cpp
Source/MediaInfo/File__Analyze_Buffer_MinimizeSize.cpp
Source/MediaInfo/File__Analyze_MinimizeSize.h
Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp
Source/MediaInfo/Multiple/File_Mpeg_Descriptors.h

Fix https://github.com/MediaArea/MediaInfoLib/issues/1887

TS DVB: fix wrong handling of UTF-8 strings in service name or EPG

---

Source/MediaInfo/Audio/File_Ac3.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/1928.

TrueHD: display of Dolby Surround EX & Dolby Pro Logic IIz

---

Source/MediaInfo/MediaInfo_File.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/1903.

SelectFromExtension: permit more values

---

Project/BCB/Library/MediaInfoLib.cbproj
Project/CMake/CMakeLists.txt
Project/GNU/Library/Makefile.am
Project/GNU/Library/configure.ac
Project/MSVC2013/Library/MediaInfoLib.vcxproj
Project/MSVC2013/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2015/Library/MediaInfoLib.vcxproj
Project/MSVC2015/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2017/Library/MediaInfoLib.vcxproj
Project/MSVC2017/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2017/Library/MediaInfoLib_UWP.vcxproj
Project/MSVC2019/Library/MediaInfoLib.vcxproj
Project/MSVC2019/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2019/Library/MediaInfoLib_UWP.vcxproj
Project/MSVC2022/Library/MediaInfoLib.vcxproj
Project/MSVC2022/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2022/Library/MediaInfoLib_UWP.vcxproj
Project/Qt/MediaInfoLib.pro
Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp
Source/MediaInfo/Multiple/File_Mpeg_Descriptors.h
Source/MediaInfo/Multiple/File_Mpeg_Psi.cpp
Source/MediaInfo/Setup.h
Source/MediaInfo/Video/File_Vvc.cpp
Source/MediaInfo/Video/File_Vvc.h
Source/Resource/Text/DataBase/Format.csv

Related to https://github.com/MediaArea/MediaInfoLib/issues/1942.

MPEG-TS: detection of VVC and EVC

---

Source/MediaInfo/ExternalCommandHelpers.cpp

using CreateProcessW implies using STARTUPINFOW

fix UNICODE structure mismatch

---

Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/MediaInfo/MediaInfo_File.cpp
Source/MediaInfo/Tag/File_Icc.cpp
Source/Resource/Text/DataBase/Format.csv

Follow up of https://github.com/MediaArea/MediaInfoLib/pull/1934

ICC: support of raw files

---

Source/MediaInfo/Audio/File_ChannelGrouping.cpp
Source/MediaInfo/Audio/File_ChannelSplitting.cpp
Source/MediaInfo/Audio/File_Pcm.h
Source/MediaInfo/Audio/File_SmpteSt0302.cpp
Source/MediaInfo/Audio/File_SmpteSt0337.cpp
Source/MediaInfo/Audio/File_SmpteSt0337.h
Source/MediaInfo/Multiple/File_Lxf.cpp
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Riff_Elements.cpp

MOV: fix bit depth info for some PCM tracks with pcmC box

---

Source/MediaInfo/Text/File_Pdf.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/1967.

PDF: fix crash with corrupted files

---

Source/MediaInfo/File__Analyze_Streams.cpp

https://github.com/MediaArea/MediaInfoLib/pull/1971 was not complete.

Dolby Vision: support dv_md_compression also for version 1, update

---

Source/MediaInfo/Image/File_Png.cpp

Also fix bit depth of indexed < 8-bit
Close https://github.com/MediaArea/MediaInfo/issues/811

 PNG: packing kind (linear or indexed)

---

Source/MediaInfo/Audio/File_Adm.cpp
Source/MediaInfo/Multiple/File_Riff.cpp
Source/MediaInfo/Multiple/File_Riff.h
Source/MediaInfo/Multiple/File_Riff_Elements.cpp

WAV: support of 4+ GiB axml

---

Source/ThirdParty/tfsxml/tfsxml.c
Source/ThirdParty/tfsxml/tfsxml.h

tfsxml update

---

Source/MediaInfo/Audio/File_Adm.cpp
Source/MediaInfo/Audio/File_Adm.h
Source/MediaInfo/Multiple/File_Riff_Elements.cpp

ADM: version 3, AdvSS emission, more conformance checks

---

Source/MediaInfo/Multiple/File_Riff.cpp
Source/MediaInfo/Multiple/File_Riff.h

Close https://github.com/MediaArea/MediaInfo/issues/822

WAV: support of BS.2088 BW64 chunkId

---

Source/MediaInfo/Audio/File_Adm.cpp

We forgot that some people can do weird things like not using the same letter case in one file :-p.

ADM: IDs are case insensitive

---

Source/MediaInfo/Audio/File_Wvpk.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/2005.

WavPack: fix duration with small files

---

Source/MediaInfo/Multiple/File_Ivf.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/2009

IVF: fix division by zero

---

Source/MediaInfo/Audio/File_Dsdiff.cpp
Source/MediaInfo/Audio/File_Dsf.cpp
Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_MinimizeSize.h
Source/MediaInfo/Multiple/File_Mk.cpp
Source/MediaInfo/Multiple/File_Mpeg4.cpp
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Nsv.cpp
Source/MediaInfo/Multiple/File_Riff.cpp

Report will be available in MediaConch, and there are more details:
```
Conformance errors                       : 1
General compliance                      : File size 7820 is less than expected size 7821
```

IsTruncated line moved to a conformance check report

---

Source/MediaInfo/File__MultipleParsing.cpp
Source/MediaInfo/MediaInfo_File.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/2014.

Lower priority for some parsers

---

Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Source/MediaInfo/MediaInfo_Config_MediaInfo.h
Source/MediaInfo/Multiple/File_Mpeg4.cpp
Source/MediaInfo/Multiple/File_Mpeg4.h
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Text/File_Cdp.cpp
Source/MediaInfo/Text/File_Eia608.cpp

Close https://github.com/MediaArea/MediaInfoLib/issues/1881.

MXF & MOV: customizable seek pos and duration of caption probe

---

Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Text/File_Cdp.cpp

MXF & MOV: customizable seek pos and duration of caption probe, update

---

Source/MediaInfo/Image/File_Bmp.cpp

Per component rather than total

BMP: fix bitdepth info

---

Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Vbi.cpp
Source/MediaInfo/Multiple/File_Vbi.h

Close https://github.com/MediaArea/MediaInfoLib/issues/2029.

MXF: decode of VBI (Line 21 & VITC)

---

Source/MediaInfo/Audio/File_Ac3.cpp

Fix https://github.com/MediaArea/MediaInfo/issues/830.

AC-3: fix crash with some TrueHD files

---

Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Mxf.h

Conformance error if not enough place for the indicated count of elements in the vector.

MXF: Check coherency of elements having vectors

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/File__Analyze.h
Source/MediaInfo/File__Analyze_MinimizeSize.h
Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Source/MediaInfo/MediaInfo_Inform.cpp
Source/MediaInfo/Multiple/File_Mpeg4.cpp
Source/MediaInfo/Multiple/File_Mpeg4.h
Source/MediaInfo/Multiple/File_Riff.cpp
Source/MediaInfo/Multiple/File_Riff.h
Source/MediaInfo/Multiple/File_Swf.cpp

Example:
```
Conformance errors                       : 3
AVI                                     : Yes
INFO                                   : Yes
IpRT                                  : Yes
General compliance                   : Element size 65546 is more than maximal permitted size 72 (offset 0x2302)
```

Conformance checker: an element is indicated bigger than its upper element

---

Source/MediaInfo/File__Analyze_Streams.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/2055.

Dolby Vision: fix crash with some files

---

Source/MediaInfo/Setup.h

Fix typo in Setup.h for MEDIAINFO_LIBMMS_YES

---

Source/MediaInfo/Multiple/File_Mxf.cpp
Source/MediaInfo/Multiple/File_Mxf.h

Close https://github.com/MediaArea/MediaInfo/issues/673.

MXF: StreamOrder for tracks in ANC

---

Source/MediaInfo/File__Analyze.cpp

Fix https://sourceforge.net/p/mediainfo/bugs/1194/

Fix random behavior due to uninitialised value

---

Source/MediaInfo/Text/File_N19.cpp
Source/MediaInfo/Text/File_Pac.cpp

After https://github.com/MediaArea/MediaInfoLib/pull/2103

Fix compilation issues with non Unicode version

---

Source/MediaInfo/Text/File_Ttml.cpp
Source/MediaInfo/Text/File_Ttml.h

TTML: fix timecode when timeBase is media

---

Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp

This Reverts commit 450ac95ef80b1a4d69e27e37dbaae0e4a9e531c0.
This Reverts commit 51b764a3557e6a4eba19f1139d51c4421abe6f8c.

DvDif: Fix issues with playback speed and discontinuity detection

---

Source/MediaInfo/Export/Export_Graph.cpp
Source/MediaInfo/Export/Export_Graph_gvc_Include.h

Replace old gvPluginList function signature

---

Source/MediaInfo/Image/File_Png.cpp
Source/MediaInfo/Image/File_Png.h

I am not the only one playing with letter case :).

PNG: adapt cLLi/mdCv letter case

---

Source/MediaInfo/MediaInfo_Inform.cpp
Source/MediaInfo/MediaInfo_Internal.h

Fix #2104 and other build issues when certain configurations of defines are used.

MediaInfo_Inform: Improve define guards

---

Source/MediaInfo/Audio/File_Dat.cpp
Source/MediaInfo/Audio/File_Dat.h
Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp

Also fix https://github.com/mipops/dvrescue/issues/966.

DAT: reduce false-positives and rejection of buggy frames

---

Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

MP4: Handle `loci` atom

---

Source/ThirdParty/aes-gladman/aes.h
Source/ThirdParty/aes-gladman/aes.txt
Source/ThirdParty/aes-gladman/aes_amd64.asm
Source/ThirdParty/aes-gladman/aes_modes.c
Source/ThirdParty/aes-gladman/aes_ni.c
Source/ThirdParty/aes-gladman/aes_ni.h
Source/ThirdParty/aes-gladman/aes_via_ace.h
Source/ThirdParty/aes-gladman/aes_x86_v1.asm
Source/ThirdParty/aes-gladman/aes_x86_v2.asm
Source/ThirdParty/aes-gladman/aescrypt.c
Source/ThirdParty/aes-gladman/aeskey.c
Source/ThirdParty/aes-gladman/aesopt.h
Source/ThirdParty/aes-gladman/aestab.c
Source/ThirdParty/aes-gladman/aestab.h
Source/ThirdParty/aes-gladman/aesxam.c
Source/ThirdParty/aes-gladman/brg_endian.h
Source/ThirdParty/aes-gladman/brg_types.h
Source/ThirdParty/aes-gladman/tablegen.c
Source/ThirdParty/sha1-gladman/sha1.c
Source/ThirdParty/sha1-gladman/sha1.h
Source/ThirdParty/sha2-gladman/sha2.c
Source/ThirdParty/sha2-gladman/sha2.h
Source/ThirdParty/sha2-gladman/shasum.c

Update from https://github.com/BrianGladman while keeping our ARM64 patches.
@cjee21 let me know if it is not enough for removing MSVC2022 warnings.

AES/SHA: update of the libraries

---

Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/MediaInfo/Text/File_Ttml.cpp
Source/Resource/Text/DataBase/Format.csv

Update of https://github.com/MediaArea/MediaInfoLib/pull/2219.

TTML: detect IMSC Rosetta, update

---

.gitignore

Catch the remaining files that are not supposed to be committed.

Update .gitignore for MSVC

---

Source/MediaInfo/Multiple/File_Mxf.cpp

Fix #2213 (more or less a workaround, ignoring the Descriptor `Linked Track ID` element when there is only one track).

MXF: better handling of bad LinkedTrackID in descriptors

---

Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/Resource/Text/DataBase/CodecID_Video_Mpeg4.csv

Fix https://github.com/MediaArea/MediaInfoLib/issues/2231

2vuy: bitdepth

---

Source/MediaInfo/Video/File_Hevc.cpp

Fix https://sourceforge.net/p/mediainfo/discussion/297610/thread/59d690c0d7/

HEVC: fix false positive conformance issue with LHEVC SPS

---

Source/MediaInfo/File__Analyze_Streams.cpp

Fix #2240 
Add display aspect ratio 9:16

Feat: Add display aspect ratio 9:16

---

Source/MediaInfo/Archive/File_Mz.cpp

Fix after https://github.com/MediaArea/MediaInfoLib/pull/2254

MZ: add more archs, update

---

Source/MediaInfo/Multiple/File_MpegTs.cpp

Fix https://github.com/MediaArea/MediaInfo/pull/1091#discussion_r2046586846

MPEG-TS: fix false-positive detection

---

Source/MediaInfo/Image/File_Jpeg.cpp
Source/MediaInfo/Image/File_Jpeg.h

The codes for detection part can probably be improved.

JPEG: XMP parsing

---

Project/MSVC2022/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2022/Library/MediaInfoLib_UWP.vcxproj
Source/MediaInfo/Audio/File_Aac.cpp
Source/MediaInfo/Audio/File_Aac.h
Source/MediaInfo/Audio/File_Aac_GeneralAudio.cpp
Source/MediaInfo/Audio/File_Aac_Main.cpp
Source/MediaInfo/Audio/File_Flac.cpp
Source/MediaInfo/Audio/File_Flac.h
Source/MediaInfo/Audio/File_Iamf.cpp
Source/MediaInfo/Multiple/File_Mpeg4_Descriptors.cpp
Source/MediaInfo/Multiple/File_Mpeg4_Descriptors.h
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp

I'll leave the remaining AAC one to others as it seems more complex.

IAMF: Codec info for PCM and FLAC and AAC

---

Source/MediaInfo/File__Analyze_Streams_Finish.cpp
Source/MediaInfo/Image/File_Jpeg.cpp
Source/MediaInfo/Image/File_Jpeg.h

as well as image stream size ignoring metadata chunks.

JPG: Writing library name

---

Source/MediaInfo/MediaInfo_File.cpp
Source/MediaInfo/Tag/File_Xmp.cpp

Fix crash when API is called while testing parsers

---

Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/Image/File_Jpeg.cpp
Source/MediaInfo/Multiple/File_Ogg.cpp

Fix after https://github.com/MediaArea/MediaInfoLib/pull/2289

Add image track for thumbnails and covers, fix decode

---

Source/MediaInfoDLL/MediaInfoDLL.JNA.java

JNA: Fix Java to Native integer conversion

---

Project/CMake/CMakeLists.txt
Project/GNU/Library/Makefile.am
Project/GNU/Library/configure.ac
Project/MSVC2022/Library/MediaInfoLib.vcxproj
Project/MSVC2022/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2022/Library/MediaInfoLib_UWP.vcxproj
Project/Qt/MediaInfoLib.pro
Source/MediaInfo/File__Analyze.cpp
Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/File__Base.h
Source/MediaInfo/Image/File_Jpeg.cpp
Source/MediaInfo/Image/File_Jpeg.h
Source/MediaInfo/Image/File_Png.cpp
Source/MediaInfo/Image/File_Png.h
Source/MediaInfo/MediaInfo_Config_Automatic.cpp
Source/MediaInfo/MediaInfo_File.cpp
Source/MediaInfo/Setup.h
Source/MediaInfo/Tag/File_C2pa.cpp
Source/MediaInfo/Tag/File_C2pa.h

An attempt at detecting C2PA for just showing if there is C2PA metadata present and only in JPEG for now.

C2PA detection

---

Source/MediaInfo/Text/File_Pac.cpp
Source/MediaInfo/Text/File_Pac.h

& tentative of autodectect of frame rate

PAC: option for default frame rate

---

Source/MediaInfo/Tag/File_Exif.cpp
Source/MediaInfo/Tag/File_Exif.h

Exif: Initial Makernote parsing

---

Source/MediaInfo/Audio/File_Wvpk.cpp
Source/MediaInfo/Audio/File_Wvpk.h
Source/MediaInfo/Tag/File_ApeTag.cpp

WavPack: Display MD5 sum of raw audio data

---

Source/MediaInfo/Audio/File_Wvpk.cpp
Source/MediaInfo/Audio/File_Wvpk.h

Fix https://github.com/MediaArea/MediaInfoLib/pull/2327#issuecomment-2981758958

WavPack: Display MD5 sum of raw audio data (DSD)

---

Source/MediaInfo/Audio/File_Iamf.cpp
Source/MediaInfo/Audio/File_Iamf.h

I'm not sure if this is the best solution.
Fixes #2340

IAMF: Add check for TestParser

---

Source/MediaInfo/Tag/File_Xmp.cpp
Source/MediaInfo/Tag/File_Xmp.h

Since XMP parser codes are getting longer and more complicated, I tried migrating to tfsxml to see how it goes. Not thoroughly tested.

XMP: Migrate to tfsxml

---

Source/MediaInfo/Tag/File_Id3v2.cpp

ID3v2: Clear Unsynch_List when skipping invalid element

---

Source/MediaInfo/File__Analyze_Streams_Finish.cpp
Source/MediaInfo/Tag/File_Exif.cpp
Source/MediaInfo/Tag/File_Xmp.cpp
Source/MediaInfo/Tag/File_Xmp.h

Map Sony Xperia model names

---

Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Source/MediaInfo/Text/File_Eia708.cpp
Source/MediaInfo/Text/File_Eia708.h

Fix https://github.com/MediaArea/MediaInfoLib/issues/1881#issuecomment-2971858195

CEA-708: fix File_CommandOnlyMeansEmpty behavior when a service is signaled

---

Project/CMake/CMakeLists.txt
Project/GNU/Library/Makefile.am

Fix compilation of fmt on Unix

---

Source/MediaInfo/Audio/File_Dts.cpp

Sample file:
[Trinnov_Trailer_Experience_DTSX-Pro.zip](https://github.com/user-attachments/files/21396344/Trinnov_Trailer_Experience_DTSX-Pro.zip)
If necessary, I can upload a full video clip with this audio track.

More DTS:X parsing.

---

Source/MediaInfo/File__Analyze_Streams_Finish.cpp

Fix https://github.com/MediaArea/MediaInfoLib/pull/2365#issuecomment-3121464905 + code improvements.

Improve model / company name handling

---

Project/CMake/CMakeLists.txt
Project/GNU/Library/Makefile.am
Project/MSVC2022/Library/MediaInfoLib.vcxproj
Project/MSVC2022/Library/MediaInfoLib.vcxproj.filters
Project/MSVC2022/Library/MediaInfoLib_UWP.vcxproj
Project/Qt/MediaInfoLib.pro
Source/MediaInfo/Image/File_GainMap.cpp
Source/MediaInfo/Image/File_GainMap.h
Source/MediaInfo/Image/File_Jpeg.cpp
Source/MediaInfo/Image/File_Jpeg.h
Source/MediaInfo/Image/File_Png.cpp
Source/MediaInfo/Image/File_Png.h
Source/MediaInfo/Multiple/File_Mpeg4.h
Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Source/MediaInfo/Tag/File_Xmp.cpp
Source/MediaInfo/Tag/File_Xmp.h

Parse ISO 21496-1 Gain map metadata for JPEG and PNG.

Parse gain map metadata

---

Source/MediaInfo/Audio/File_Wvpk.cpp
Source/MediaInfo/Audio/File_Wvpk.h

Fix https://sourceforge.net/p/mediainfo/bugs/1200/

WavPack: fix duration for long duration

---

Source/MediaInfo/Image/File_Jpeg.cpp
Source/MediaInfo/Image/File_Jpeg.h

JPEG: Detect lossless

---

Source/MediaInfo/File__Analyze_Streams.cpp
Source/MediaInfo/Video/File_Mpegv.cpp

Fix https://github.com/MediaArea/MediaInfoLib/issues/2383

Dolby Vision: Fill colour, transfer & matrix for profile 5

---

Source/MediaInfo/Audio/File_Ac4.cpp

Some private langage codes are mapped to an extended content classifier.
Before:
```
Presentation #3                          : Stereo Main + Associate (French)
[...]
Group #4                                 : Associate
Language                                : qax
```
After:
```
Presentation #3                          : Stereo Main (French) + Associate (audio description, premix)
[...]
Group #4                                 : Associate (audio description, premix)
```

AC-4: Enhancement to Presentation Role display

---

Source/MediaInfo/Audio/File_Adm.cpp

Tests on [Dolby E ADM and S-ADM profile for emission (including implementation guide)](https://professionalsupport.dolby.com/s/article/Dolby-E-ADM-and-S-ADM-Profile-for-emission?language=en_US).

ADM: Dolby E profile for emission conformance checker
