- Source/MediaInfo/Video/File_Ffv1.cpp
- Source/MediaInfo/Video/File_Ffv1.h
When decoding a FFv1 slice, the CRC is verified.
If the slice is not valid, "NOK" is printed near the CRC value with the value computed.
Otherwise, the message "OK" is printed near the CRC.
> video/FFv1: Check the validy of the CRC in slice

- Source/MediaInfo/Video/File_Ffv1.cpp
- Source/MediaInfo/Video/File_Ffv1.h
In case of RGB colorspace, use the default FFv1 transition table.
> video/FFv1: use the correct state transitions table

- Source/MediaInfo/File__Analyze.cpp
- Source/MediaInfo/MediaInfoList_Internal.cpp
This line https://github.com/dericed/MediaInfoLib/blob/master/Source/MediaInfo/File__Analyze.cpp#L2580 still needs an update to replace <data> with <block> rather than appending an 's' as it currently does
> mediatrace updates

- Source/MediaInfo/Multiple/File_Mk.cpp
It shouldn't be that hard to modify to simply remove any trace of statistics tags from display.
I've modified the default track duration method to only be applied if the duration tag isn't present in case you want to keep it, but I've commented it out.  Of course, if you're going to do a full pass-through of the file that might be good enough to override the tag.
If you think there might be any lone BPS tags out there somewhere that you don't want, you might add some extra clean-up code in the stream finish section to deal with it, or with any other lonely stats tags.
I've left it to display any unknown Stat Tags (or any with an incorrect security tag) with an asterisk before them, if you just want to remove them completely that shouldn't be hard.  Or you could go the other way and …
> Matroska Statistics Tags Fix

- Source/MediaInfo/Multiple/File_Mk.cpp
Set VFR if framerate of first frames not equal to framerate implied in Statistics Tags.
(TimecodeScale*0.0000000010021) is the margin of error needed to detect 59.880 fps as being equal to 60/1.001 fps with a timescale of 1000000ns.  Tweak it as you like.
> Set VFR if framerate of first frames not equal to framerate implied in Matroska Statistics Tags.

- Source/MediaInfo/Audio/File_Ac3.cpp
It could probably do with better formatting to look more like DTS:X.
There might be more in the header to better recognise exactly what the 4th HD substream is, but this seems to work on the samples I have at least.
TrueHD is "TrueHD", ATMOS is "ATMOS / TrueHD"
> ATMOS Hack

- Source/MediaInfo/Audio/File_Ac3.cpp
As far as I can tell, this is a literal interpretation of the code Madshi sent me to detect Atmos in TrueHD the way EAC3To does.
```
function ParseThdMajorSyncHeader(buffer: TPAByte; len: int64; ...) : integer; begin
atmos := false;
if (len >= 32) and (TPCardinal(@buffer[4])^ = $ba6f72f8) then begin
if buffer[29] and 1 <> 0 then begin
headerSize := 32 + (buffer[30] shr 4) * 2;
atmos := true;
end else
headerSize := 30;
```
I'm not so sure now.  It looks as though the 01 he's using as a trigger does nothing more than flag an extension to the header.  I should think he'd know more about this stuff than I do, so I'm guessing without access to the actual TrueHD specs to properly scan the streams for definitive Atmos elements this is the best we've got for now.
> Processing TrueHD Header Extention (Atmos?)

- Project/GNU/libmediainfo.spec
x Disable debuginfo package to fix Fedora 23 build
Signed-off-by: Guillaume Roques <guillaume.roques@gmail.com>
> x Fix date in .spec changelog

- Source/MediaInfo/MediaInfo_Inform.cpp
- Source/MediaInfo/Text/File_Cdp.cpp
- Source/MediaInfo/Text/File_DtvccTransport.cpp
Compilation currently fail when MEDIAINFO_XML_YES and/or MEDIAINFO_ADVANCED is not defined.
> x Fixed compilation issues with some #defines

- Source/MediaInfo/Multiple/File_Mk.cpp
- Source/MediaInfo/Text/File_TimedText.cpp
Description of patches
1. Number of chapters of Timed Text 
On some MPEG-4 movies MediaInfo shows a menu of "Timed Text" format (codec id "text") with defined Duration.
But such menu has no Menu_Chapters_Pos_End and Menu_Chapters_Pos_Begin tags, so I added it.
Some description and sample - https://sourceforge.net/p/mediainfo/bugs/914/
2. Matrsoka: ORIGINAL/URL is not useless
Last updates of MI had removed a ORIGINAL/URL tags from Matroska files as useless.
I add it back as is. Sample file ( https://sourceforge.net/projects/matroska/files/test_files/cover_art.mkv/download )
has a link to youtube in this tag.
3. Matroska: add PixelCrop tags
I added Matroska PixelCrop tags, sample is in this request - https://sourceforge.net/p/mediainfo/feature-requests/446/
> Please look at this patches and accept if possible

- Source/MediaInfoDLL/MediaInfoDLL.py
- Source/MediaInfoDLL/MediaInfoDLL3.py
I've made the following changes:
- Argument lists for most calls were set in a "argtype" attribute which
is wrong. The correct attribute name is "argtypes".
- Added support to load the Mac OS X dynamic library.
- Modified the Python 3 version of the library to also be compatible
with Python 2, so that a single file can be used on both.
> Mac OS X support for the Python interface

- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Mxf.h
x MXF: Handling of MXF files having e.g. first Element Number 1 for video essences and 0 for audio essences.
TODO: we should do also per Item Type / Element Type
> MXF ElementNumber

- Source/MediaInfo/Multiple/File_Mk.cpp
MakeMKV has added it's own tags into the fray.
I have a TV episode at NTSC film frame rate with exactly 29821 frames...
Do I need to show the math?
> MakeMKV Tags and (ever so slightly) less faulty frame rate detections

- Source/MediaInfo/Multiple/File_Mk.cpp
- Source/MediaInfo/Multiple/File_Mk.h
Comparing to illegal byte values, depending of EBMLMaxSizeLength
> + Matroska: support of padding/junk at the start of a segment

- Source/MediaInfo/Video/File_Avc.cpp
Due to wrong algorithm during reordering
> x AVC: some DTVCC Transport stream packets were not correctly demuxed

- Source/MediaInfo/Multiple/File_DcpAm.cpp
- Source/MediaInfo/Multiple/File_DcpCpl.cpp
- Source/MediaInfo/Multiple/File_DcpPkl.cpp
GitHub issue #100
Previously, when an ASSETMAP/CPL/PKL file was given as a relative path,
MediaInfo would look for related assets in the wrong place because the
'directory' was empty yet it prepended a path separator anyway.
Where dirname is empty, we need to drop the path separator.
Signed-off-by: Peter Chapman <pchapman@vidcheck.com>
> x Fix parsing of DCP MXF files when input file is not an absolute path

- Source/MediaInfo/Multiple/File_Ogg.cpp
With some impacts on automatic filling (e.g. no media type)
> x Ogg: "Ogg" was spelled "OGG"

- Source/MediaInfo/Multiple/File_DcpCpl.cpp
Hi again Jérôme,
Suggested change to remove assumption about what namespace prefix is used for MarkerSequence.
> IMF: Ignore MarkerSequence whatever namespace prefix is used

- Source/MediaInfo/Text/File_Teletext.cpp
I just found this via a GCC warning.
> Teletext: correct invalid character constant

- Source/MediaInfo/Multiple/File_DashMpd.cpp
The segment filename will get 'configured' later to include the SourceDir anyway, and that would duplicate the SourceDir in the path, so just include the base filename in the sequence instead.
> Don't include the SourceDir when adding a DASH segment file to the sequence.

- History_DLL.txt
- Source/MediaInfo/Video/File_Ffv1.cpp
In case of e.g. a 5x5 4:2:0 stream, slice pixels sizes for all planes (luma and chroma) are not correctly handled.
You can test with such file:
ffmpeg -y -f lavfi -i "color=c=white" -t 1 -filter:v scale="5:5" -vcodec ffv1 -level 3 5x5.mkv
> FFV1 correct handling of width/height

- History_DLL.txt
- Source/MediaInfoDLL/MediaInfoDLL.py
Python binding: some errors during call of Get() API with Python3 on Linux/Mac.
> Python Get() API with Python3 on Linux/Mac.

- History_DLL.txt
- Source/MediaInfo/File__Analyze_Streams.cpp
Sometimes duration was displayed with only count of minutes
> x Duration: fixed regression in last release

- History_DLL.txt
- Source/MediaInfo/Video/File_Ffv1.cpp
- Source/MediaInfo/Video/File_Ffv1.h
Handling 16+ bitdepth (YUV and RGB) while handling buggy version <= 3 YUV 16-bit streams
> FFV1 RGB 16-bit

- History_DLL.txt
- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/Resource/Text/DataBase/CodecID_Video_Riff.csv
https://github.com/MediaArea/MediaInfoLib/issues/242
> + I242, AVI/Matroska: mapping of mjp2 to JPEG 2000 format name

- History_DLL.txt
- Source/MediaInfo/Multiple/File_Riff.cpp
Resolves https://github.com/MediaArea/MediaInfo/issues/94
> + #M94, WAV: support of file with a buggy RIFF header

- Source/MediaInfo/MediaInfo_Internal.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Text/File_AribStdB24B37.cpp
- Source/MediaInfo/Text/File_AribStdB24B37.h
- Source/MediaInfo/Text/File_Eia608.cpp
- Source/MediaInfo/Text/File_Eia608.h
- Source/MediaInfo/Text/File_Eia708.cpp
- Source/MediaInfo/Text/File_Eia708.h
- Source/MediaInfo/Text/File_SubRip.cpp
In file included from ../../../Source/MediaInfo/File__MultipleParsing.cpp:258:0:
../../../Source/MediaInfo/Text/File_Eia608.h:40:12: warning: extra tokens at end of #endif directive [enabled by default]
#endif MEDIAINFO_EVENTS
^
> Fix  #endif MEDIAINFO_%

- Source/MediaInfo/Audio/File_Aac.h
- Source/MediaInfo/Audio/File_Aac_GeneralAudio_Sbr.cpp
- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Wm_Elements.cpp
- Source/MediaInfo/Reader/Reader_libcurl.cpp
- Source/MediaInfo/Text/File_AribStdB24B37.cpp
- Source/MediaInfo/Text/File_AribStdB24B37.h
V813 Decreased performance. The 'x' argument should probably be rendered as a constant reference.
http://www.viva64.com/en/w/V813/print/
> Fix const T -> const T& for private functions

- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Mxf.h
- V802 On 32-bit platform, structure size can be reduced from 24 to 16 bytes by rearranging the fields according to their sizes in decreasing order. file_mxf.h 550
http://www.viva64.com/en/w/V802/print/
- Fix copy-paste
if (MxfTimeCodeForDelay.RoundedTimecodeBase && MxfTimeCodeForDelay.StartTimecode!=(int64u)-1)
float64 TimeCode_StartTimecode_Temp=((float64)(MxfTimeCodeForDelay.StartTimecode+Config->File_IgnoreEditsBefore))/MxfTimeCodeForDelay.RoundedTimecodeBase;
if (MxfTimeCodeForDelay.DropFrame)
{
TimeCode_StartTimecode_Temp*=1001;
TimeCode_StartTimecode_Temp/=1000;
}
> Refactoring File_Mxf::mxftimecode

- Source/MediaInfo/Export/Export_Mpeg7.cpp
- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/Multiple/File_DcpCpl.cpp
- Source/MediaInfo/Multiple/File_Mk.cpp
- Source/MediaInfo/Multiple/File_Mxf.h
- Source/MediaInfo/Reader/Reader_libcurl.cpp
- Source/MediaInfo/Text/File_AribStdB24B37.cpp
- Source/MediaInfo/Text/File_AribStdB24B37.h
- Source/MediaInfo/Text/File_DvbSubtitle.cpp
- Source/MediaInfo/Video/File_Avc_Duplicate.cpp
- Source/MediaInfo/Video/File_Ffv1.cpp
- Source/MediaInfo/Video/File_Mpeg4v.cpp
V614 Potentially uninitialized variable 'Size' used. file_mk.cpp 1150
V571 Recurring check. The '!colour_description_present_Temp.empty()' condition was already verified in line 1429. file__analyze_streams.cpp 1431
V571 Recurring check. The 'frame_num != (int32u) - 1' condition was already verified in line 205. file_avc_duplicate.cpp 207
V127 An overflow of the 32-bit 'k' variable is possible inside a long cycle which utilizes a memsize-type loop counter. file_ffv1.cpp 1603
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: FpaPass. file_mxf.h 1031
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: PKL_Pos. file_dcpcpl.cpp 50
V590 Consider inspecting the 'shape != 2 && shape == 0' expression. The …
> PVS Studio fix

- Source/MediaInfo/File__Analyze.cpp
- Source/MediaInfo/File__Analyze.h
- Source/MediaInfo/File__Analyze_Element.cpp
- Source/MediaInfo/File__Analyze_Element.h
- Source/MediaInfo/MediaInfo_Internal.h
- Source/MediaInfo/Multiple/File_DashMpd.cpp
- Source/MediaInfo/Video/File_Avc.h
- Source/MediaInfo/Video/File_Hevc.h
V690 The 'template_generic' class implements a copy constructor, but lacks the '=' operator. It is dangerous to use such a class. file_dashmpd.cpp 118
V690 The 'xxl_data' class implements the '=' operator, but lacks a copy constructor. It is dangerous to use such a class. file_avc.h 67
V690 The 'xxl' class implements the '=' operator, but lacks a copy constructor. It is dangerous to use such a class. file_avc.h 65
V690 The 'bitstream_restriction_struct' class implements the '=' operator, but lacks a copy constructor. It is dangerous to use such a class. file_avc.h 131
V690 The '=' operator is declared as private in the 'vui_parameters_struct' class, but the default copy constructor will still be generated by compiler. It is dangerous to use such a class. file_avc.h 63
V690 The '=' …
> Fix operator= and copy constructor

- Source/ThirdParty/base64/base64.h
* Remove dynamic allocation for sBase64Table (optimisation)
* TODO - remove inline for Base64::encode / Base64::decode ?
* Magic fix crash Win XP SP3 + Visual Basic + MediaInfoNET.dll + MediaInfo.DLL https://sourceforge.net/p/mediainfo/bugs/990/
Crash - stack :
ntdll.dll!ExecuteHandler@20()    Unknown
ntdll.dll!_KiUserExceptionDispatcher@8()    Unknown
>    MediaInfo.DLL!Base64::encode(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & sString) Line 32    C++
MediaInfo.DLL!MediaInfoLib::File_Mk::Segment_Attachments_AttachedFile_FileData() Line 1761    C++
MediaInfo.DLL!MediaInfoLib::File_Mk::Data_Parse() Line 1257    C++
MediaInfo.DLL!MediaInfoLib::File__Analyze::Data_Manage() Line 2356    C++
MediaInfo.DLL!MediaInfoLib::File__Analyze::Buffer_Parse() Line 1516 …
> Fix Base64::encode

- Source/MediaInfo/Multiple/File__ReferenceFilesHelper.cpp
Old logic attempts to find a single index for both channel and language lookups.  Then for each referenced file, it splits the filename on "_", " ", "." and uses the calculated index to determine the channel and language metadata. This causes a segfault when a PTX session file references different length filenames and attempts to access an out of bounds index.
Instead, the fix attempts to find the channel and language index for each individual referenced file in the session.  Also added additional channels (Lsr, Rsr).
> Modify channel and language index search logic

- History_DLL.txt
- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/MediaInfo/Multiple/File__ReferenceFilesHelper.cpp
- Source/Resource/Text/Language/DefaultLanguage.csv
IMF and PTX: more languages detected from file names (but the full list of common languages tags still need to be added)
> IMF and PTX: more languages detected from file names

- Source/MediaInfoDLL/MediaInfoDLL.py
- Source/MediaInfoDLL/MediaInfoDLL3.py
The buffer functions are missing in the Python DLL interface files.
> add missing buffer functions to Python interface

- Source/MediaInfo/File__Analyze.cpp
- Source/MediaInfo/File__Analyze.h
- Source/MediaInfo/File__Analyze_MinimizeSize.h
- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Especially with MOV files having the header at the end of the file, and with non-interleaved streams.
> x Refactoring of hash algorithm in order to handle some corner cases

- History_DLL.txt
- Source/MediaInfo/Multiple/File_Riff.cpp
Responding to https://twitter.com/bitsgalore/status/816718028683546624
http://openpreservation.org/blog/2017/01/04/breaking-waves-and-some-flacs/
About the WAV truncate detection.
Check the new "IsTruncated: Yes" line:
General
Complete name                            : C:\Users\jerome\Downloads\frogs-01.wav
Format                                   : Wave
File size                                : 1.96 MiB
Duration                                 : 11 s 626 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 1 411 kb/s
Track name                               : untitled
Writing application                      : Lavf57.56.100
Audio
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, …
>  AVI/WAV: test of truncated file

- History_DLL.txt
- Source/MediaInfo/Video/File_Hevc.cpp
- Source/MediaInfo/Video/File_Hevc.h
From HEVC/H.265 draft, preferred method for HLG in DVB
https://sourceforge.net/p/mediainfo/feature-requests/508/
> HEVC: support preferred_transfer_characteristics SEI 

- Source/MediaInfo/Audio/File_ChannelGrouping.cpp
- Source/MediaInfo/Audio/File_ChannelGrouping.h
- Source/MediaInfo/Audio/File_Pcm.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Moving PCM acceptance threshold config to Mpeg4 demuxer, so it can set the frame count limit depending of the Demux_SplitAudioBlocks: if audio blocks are split, there are several PCM frames of half-stream 1 before first PCM frame of half-stream 2.
> x MP4/MOV: Dolby E was not detected if Demux_SplitAudioBlocks option

- Source/MediaInfo/File__Analyze.cpp
- Source/MediaInfo/File__Analyze.h
- Source/MediaInfo/File__Analyze_Element.cpp
- Source/MediaInfo/File__Analyze_Element.h
Previously, the output was not as expected if an offset is at more that 4 GiB (the 4+ GiB offset were having more characters that the others, no more alignment), and small files were having too much digits in the offset.
There was also a performance issue on Windows ("\r\n" end of line).
> Dynamic size of the offset string in the tree trace

- Source/MediaInfo/Multiple/File_DcpCpl.cpp
- Source/MediaInfo/Multiple/File_DcpPkl.cpp
IMF files coming out of Clipster 6.1.0.0 use the 2016 SMPTE 2067 namespace, and aren't detected as IMF by MediaInfoLib. This patch fixes the issue. Thanks!
Signed-off-by: Peter Chapman <peterc@telestream.net>
> + IMF: Add awareness of 2016 SMPTE 2067 namespaces

- Source/MediaInfo/Export/Export_EbuCore.cpp
EBUCore output is not correctly XML Encoded.  This adds a few more XML_Encode to it.
> EBUCore output is not correctly XML Encoded.

- History_DLL.txt
- Source/MediaInfo/Multiple/File_Mk.cpp
- Source/MediaInfo/Multiple/File_Mk.h
Fix for https://github.com/MediaArea/MediaInfoLib/issues/316
Based on https://github.com/MediaArea/MediaInfoLib/pull/357
> x Matroska: crash in case of big attachment and CRC32 present

- Source/MediaInfo/Multiple/File_Mk.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.h
1. [bcc32 Error] File_Mk.cpp(814): E2268 Call to undefined function 'fabs'
2. [bcc32 Error] algorithm(1430): E2093 'operator<' not implemented in type 'MediaInfoLib::File_Mpeg4::mdat_Pos_Type' for arguments of the same type
> Fix build with C++Builder 10.1 (Part 1)

- Source/MediaInfo/Audio/File_Dts.cpp
E2354 Two operands must evaluate to the same type
> Fix C++ Builder 10.1 error

- Project/MSVC2013/Library/MediaInfoLib.vcxproj
- Project/MSVC2013/MediaInfoLib.sln
- Project/MSVC2015/Library/MediaInfoLib.vcxproj
- Project/MSVC2015/MediaInfoLib.sln
- Project/MSVC2017/Library/MediaInfoLib.vcxproj
- Project/MSVC2017/MediaInfoLib.sln
From https://github.com/MediaArea/MediaInfoLib/pull/422, I prefer to keep original project locations and IDs.
Project has been patched in order to accept 32-bit compilation.
> VS support: switch back to madler/zlib

- History_DLL.txt
- Source/MediaInfo/MediaInfo_Config.cpp
- Source/MediaInfo/MediaInfo_Config.h
- Source/MediaInfo/Multiple/File_MpegTs.cpp
- Source/MediaInfo/Multiple/File_MpegTs.h
For showing e.g. DVB streams detected in PMT even if there is no PES at the beginning of the file
> MPEG-TS: MpegTs_ForceTextStreamDisplay option

- Project/BCB/Library/MediaInfoLib.cbproj
Fix C++Builder warning
[TLIB Warning] Warning: public '_t_rc' in module 'tablegen' clashes with prior module 'aestab'
[TLIB Warning] Warning: public '_t_fn' in module 'tablegen' clashes with prior module 'aestab'
[TLIB Warning] Warning: public '_t_fl' in module 'tablegen' clashes with prior module 'aestab'
[TLIB Warning] Warning: public '_t_in' in module 'tablegen' clashes with prior module 'aestab'
[TLIB Warning] Warning: public '_t_il' in module 'tablegen' clashes with prior module 'aestab'
[TLIB Warning] Warning: public '_t_im' in module 'tablegen' clashes with prior module 'aestab'
[TLIB Warning] Warning: public '_main' in module 'shasum' clashes with prior module 'tablegen'
[TLIB Warning] Warning: public '_t_rc' in module 'tablegen' clashes with prior module 'aestab'
[TLIB Warning] …
> Remove tablegen.c

- Source/MediaInfo/MediaInfo_Inform.cpp
in templates
Fixes https://github.com/MediaArea/MediaInfoLib/issues/466
> Field names with first letter lower case were not handled

- Source/MediaInfo/Video/File_Ffv1.cpp
Fixing https://github.com/MediaArea/MediaConch_SourceCode/issues/570
> FFV1 PixelAspectRatio was an integer, switched to 3-digit rational

- Source/MediaInfo/Audio/File_SmpteSt0337.cpp
Too early validation of https://github.com/MediaArea/MediaInfoLib/pull/481
> Fix compilation

- Source/MediaInfo/Multiple/File_Mk.cpp
mediainfolib\source\mediainfo\multiple\file_mk.cpp(1274): warning C4701: potentially uninitialized local variable 'Name' used
> fix warning C4701

- Source/MediaInfo/Audio/File_Ac3.cpp
- Source/MediaInfo/Audio/File_Ac3.h
Fix https://github.com/MediaArea/MediaInfoLib/issues/505, superseding https://github.com/MediaArea/MediaInfoLib/pull/506.
> AC-3: crash with some potentially malformed frames

- Source/MediaInfo/Multiple/File_Mk.cpp
e.g. when reading from HTTP link
> Matroska: fix parsing issue with small byte blocks

- Source/MediaInfo/Multiple/File_Riff_Elements.cpp
Tolerance range is reduced from 10% to 2% (arbitrary decided)
> WAV: metadata coherency, ignore "fact" chunk more often

- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Mxf.h
Probing the first bytes as magic value is not enough.
> MXF: less false-positive detection of some files as MXF

- Source/MediaInfo/Audio/File_Mpc.cpp
Related to this issue: https://github.com/MediaArea/MediaInfoLib/issues/535#issuecomment-308850445
Taken from FFmpeg code source:
https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/mpc.c#L94
Thank you to @JeromeMartinez for his advice :wink:
> Channels display add for MPC

- Source/MediaInfo/Multiple/File_Riff_Elements.cpp
Now limited on AC-3 and DTS
Closes https://github.com/MediaArea/MediaInfo/issues/169
> x I169, WAV: too much aggressive detection of wrong 5-channel audio

- Project/CMake/libmediainfo.pc.in
- Project/GNU/Library/configure.ac
- Project/GNU/Library/libmediainfo.pc.in
* Adding Libs_Static to CMake .pc, like in ZenLib
* zlib is a required dependency so it can be hardcoded into Requires
* -lpthread is pulled in from libzen, so it's not needed again
Should be the last modification required.
> Make template pkg-config file consistent between autotools and cmake

- Project/CMake/CMakeLists.txt
- Project/CMake/libmediainfo.pc.in
- Project/GNU/Library/configure.ac
- Project/GNU/Library/libmediainfo.pc.in
- Project/GNU/libmediainfo.spec
- Project/OBS/deb6.debian/control
- Project/OBS/deb9.debian/control
- debian/control
- zlib .pc isn't aviable on old systems
- pkg-config fail if libcurl .pc is missing
> pkg-config: fix build on debian/old RPM

- Source/Resource/Text/DataBase/Format.csv
- Matroska link
Related to this issue: https://github.com/MediaArea/MediaInfoLib/issues/85
Their default link is for the most popular OS, Windows, but from that page it's very easy to select an other OS.
- CAF
https://en.wikipedia.org/wiki/Core_Audio_Format
[Chimpanzee+Calls.caf.txt](https://github.com/MediaArea/MediaInfoLib/files/1106866/Chimpanzee.Calls.caf.txt)
- QLCM
https://en.wikipedia.org/wiki/QCP  (Qualcomm's PureVoice)
https://tools.ietf.org/rfc/rfc3625.txt
[When_I_Need_You_Celine_Dion.qcp.txt](https://github.com/MediaArea/MediaInfoLib/files/1106864/When_I_Need_You_Celine_Dion.qcp.txt)
- AACP and ADTS extensions
https://developer.apple.com/library/content/qa/qa1534/_index.html
https://developer.apple.com/library/content/technotes/tn2236/_index.html …
> Add CAF and QLCM formats, more some small fixes

- Source/MediaInfo/File__Analyze_Streams.cpp
Note: @dericed I am aware this is a messy hot fix, and that I should spend time on storing Numerator and Denominator of PAR at some point instead of such workaround.
> Fix a weird 1.334 DAR due to a rounding issue

- Source/MediaInfo/Video/File_Ffv1.cpp
@dericed which image will you find this time for this stupid bug? ;-)
> FFV1: fix false positive about FFV1 slice_x error when slice_w>slice_h

- Source/MediaInfo/Video/File_Mpegv.cpp
There was a change between draft and final version of HEVC 2016.
> matrix_coefficients: Y'D'zD'x support, fix for Chromaticity-derived

- Source/MediaInfo/Multiple/File_Mk.cpp
- Source/MediaInfo/Multiple/File_Riff_Elements.cpp
[bcc32 Error] File_Mk.cpp(979): E2015 Ambiguity between 'std::pow(double,double) at c:\bcb10\include\windows\crtl\math.h:245' and 'std::pow(double,int) at c:\bcb10\include\windows\crtl\math.h:417'
[bcc32 Error] File_Mk.cpp(979): E2268 Call to undefined function 'pow'
[bcc32 Error] File_Riff_Elements.cpp(3602): E2096 Illegal structure operation
> Fix build with C++Builder 10.1

- Source/MediaInfo/Multiple/File_Riff.cpp
Fix regression after https://github.com/MediaArea/MediaInfoLib/pull/685
> AIFF: was not skipping the SSND chunk header during demux, update

- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/Video/File_Vc3.cpp
Looks like the 4 last bytes are the size of a frame
> VC-3: skip the 4 last bytes of a VC-3 sample in MOV with 2+ frames

- Source/MediaInfo/File__MultipleParsing.cpp
- Source/MediaInfo/MediaInfo_File.cpp
...which is caused by using `MEDIAINFO_WM_YES` instead of `MEDIAINFO_WTV_YES`
> Fixed undefined reference to File_Wtv

- Source/MediaInfo/Video/File_Mpegv.cpp
MI count-call(C++Builder CodeGuard)
fflush (4 times)
strcmp (81 times)
strrchr (21 times)
strncmp (2556 times)
atan2 (286 times)
log10 (5740 times)
ceil (917488 times)
pow (5777504 times)
gmtime (4598 times)
memcmp (130790 times)
strncpy (39835 times)
memchr (250680 times)
sprintf (2007465 times)
memmove (93454179 times)
memset (212663 times)
delete[] (869395 times)
new[] (869395 times)
delete (20649151 times)
SysReallocMem (107 times)
SysAllocMem (12 times)
SysFreeMem (4593 times)
SysGetMem (4582 times)
strdup (10 times)
free (37 times)
_lsetlocale (15 times)
new (20649160 times)
calloc (19 times)
strlen (2381543 times)
realloc (1 times)
malloc (7 times)
memcpy (47544595 times)
> File_Mpegv: small fix ceil

- Source/MediaInfo/Audio/File_Mpega.cpp
V781 The value of the 'mode' variable is checked after it was used. Perhaps there is a mistake in program logic. Check lines: 1119, 1132. file_mpega.cpp 1119
> Fix Mpega_Channels[]

- Source/MediaInfo/Multiple/File_Mxf.cpp
https://www.viva64.com/en/w/v811/print/
V811 Decreased performance. Excessive type casting: string -> char * -> string. Consider inspecting the 'FrontS.c_str()' expression. file_mxf.cpp 1498
V811 Decreased performance. Excessive type casting: string -> char * -> string. Consider inspecting the 'SideS.c_str()' expression. file_mxf.cpp 1503
V811 Decreased performance. Excessive type casting: string -> char * -> string. Consider inspecting the 'BackS.c_str()' expression. file_mxf.cpp 1509
V811 Decreased performance. Excessive type casting: string -> char * -> string. Consider inspecting the 'LfeS.c_str()' expression. file_mxf.cpp 1515
> Fix MXF_MCALabelDictionaryID_ChannelPositions

- Project/MSVC2013/ShellExtension/MediaInfoShellExt.vcxproj
- Project/MSVC2015/ShellExtension/MediaInfoShellExt.vcxproj
- Project/MSVC2017/ShellExtension/MediaInfoShellExt.vcxproj
MediaInfoShellExt_.cpp(5): fatal error C1083: Cannot open include file: 'MediaInfoDLL/MediaInfoDLL_Static.h': No such file or directory
> Fix build MediaInfoShellExt

- Source/MediaInfo/Audio/File_Aac_Main.cpp
- Source/MediaInfo/File__Analyze.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_MpegPs.cpp
- Source/MediaInfo/Video/File_Avc.cpp
V560 A part of conditional expression is always true: Element_Code == 0x05. file_avc.cpp 1956
V560 A part of conditional expression is always true: ReferenceFiles. file_mpeg4.cpp 1254
V560 A part of conditional expression is always true: File_IgnoreEditsBefore. mediainfo_config_mediainfo.cpp 2469
V560 A part of conditional expression is always true: ToAdd_Size. file__analyze.cpp 598
V560 A part of conditional expression is always true: End != (size_t) - 1. file_aac_main.cpp 437
V560 A part of conditional expression is always true: stream_id_extension <= 0x7F. file_mpegps.cpp 3826
V560 A part of conditional expression is always true: stream_id_extension <= 0x7F. file_mpegps.cpp 3972
> Fix V560 A part of conditional expression is always true

- Source/MediaInfo/OutputHelpers.h
The 'Name' argument should probably be rendered as a constant reference.
> Fix V813 Decreased performance.

- Source/MediaInfo/Multiple/File_Lxf.cpp
- Source/MediaInfo/Tag/File_Id3v2.cpp
- Source/MediaInfo/Video/File_Mpegv.cpp
V796 It is possible that 'break' statement is missing in switch statement. file_lxf.cpp 527
V796 It is possible that 'break' statement is missing in switch statement. file_mpegv.cpp 3109
V796 It is possible that 'break' statement is missing in switch statement. file_id3v2.cpp 1207
V796 It is possible that 'break' statement is missing in switch statement. file_id3v2.cpp 1222
> Fix V796 It is possible that 'break'

- Source/MediaInfo/Export/Export_EbuCore.cpp
Perhaps, this is a typo and 'As11_UkDpp_Pos' variable should be used instead of 'As11_Core_Pos'. export_ebucore.cpp 1792
> V778 Two similar code fragments were found.

- Source/MediaInfo/MediaInfo_Config.h
- Source/MediaInfo/MediaInfo_Internal.cpp
- Source/MediaInfo/Multiple/File_DvDif.h
V601 The 'true' value is implicitly cast to the integer type. mediainfo_config.cpp 262
V601 The 'false' value is implicitly cast to the integer type. mediainfo_internal.cpp 908
V601 The 'true' value is implicitly cast to the integer type. file_dvdif_analysis.cpp 289
V601 The 'false' value is implicitly cast to the integer type. file_dvdif_analysis.cpp 869
> Fix V601 The bool value is implicitly cast to the integer type

- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.h
- Source/MediaInfo/MediaInfo_File.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.h
https://sourceforge.net/p/mediainfo/feature-requests/522/
+ support of file names >64 chars long or non ASCII for referenced files
> MOV: Support of external time code tracks (.qtc)

- Source/Example/HowToUse_Dll.cpp
Excessive type casting: string -> char * -> string.
> Fix V811 Decreased performance. 

- Source/MediaInfo/Multiple/File__ReferenceFilesHelper.cpp
it does fail to compile if `MEDIAINFO_DVDIF_YES` is not defined.
> Fixed compilation issue at File__ReferenceFilesHelper.cpp

- Source/MediaInfo/Video/File_Vc3.cpp
Only causing an issue if `MEDIAINFO_CDP_NO` is defined.
> Missing comma at File_Vc3.cpp

- Source/MediaInfo/Video/File_Mpegv.cpp
These are caused if `MEDIAINFO_ANCILLARY_YES` is defined, while `MEDIAINFO_CDP_YES` is not, or if `MEDIAINFO_AFDBARDATA_YES` is defined while `MEDIAINFO_ANCILLARY_YES` isn't.
> Fix compilation errors at File_Mpegv.cpp

- Source/MediaInfo/Export/Export_PBCore2.cpp
- Source/MediaInfo/Export/Export_PBCore2.h
- Source/MediaInfo/MediaInfo_Config.cpp
- Source/MediaInfo/MediaInfo_Inform.cpp
With a change in output option behavior in order to be coherent with other output options (FIMS, EBUCore) :
- `--Output=PBCore` redirects now on `PBCore` latest version (currently 2.1) instead of PBCore1
Template currently only modifying the XSD location. cc @dericed
> PBCore 2.1 template

- Source/MediaInfo/Multiple/File_MpegPs.h
- Source/MediaInfo/Multiple/File_MpegTs.cpp
- Source/MediaInfo/Multiple/File_MpegTs.h
- Source/MediaInfo/Video/File_Avc.cpp
https://github.com/MediaArea/MediaInfoLib/pull/788 was permitting to show new meta only in raw AVC.
Now also in MPEG-TS, and ignore non decodable P/B frames before the 1st I-frame
> Consumer camera recording date/time, update

- Source/MediaInfo/Video/File_Ffv1.cpp
[Spec is currently not clear](https://github.com/FFmpeg/FFV1/issues/109) and FFmpeg creates such stream
(0/1 if unknown, e.g. with `./ffmpeg -f lavfi -i testsrc -vframes 1 -c:v ffv1 -level 3 -vf setsar=0/2 a.mkv`)
[FFV1-SLICE-sar_den test description](https://github.com/MediaArea/groundtruth/blob/master/matroska/54.md) needs to be updated.
[Reported by user](https://github.com/MediaArea/MediaConch/issues/210) and detected by me at the same period.
> FFV1: remove sar_den test must be 0 if sar_num is 0

- Source/MediaInfo/Video/File_Ffv1.cpp
Fix for https://github.com/MediaArea/MediaInfoLib/issues/782
and consider also v0/v1 frames with CRC (`./ffmpeg -f lavfi -i mandelbrot -t 1 -c ffv1 -slicecrc 1 a.mkv`) as valid (todo: update spec with such case)
> FFV1: bug fixes and support of CRC in v0/v1

- Source/MediaInfo/Audio/File_Flac.cpp
- Source/MediaInfo/MediaInfo_Config.cpp
- Source/MediaInfo/MediaInfo_Config.h
- Source/MediaInfo/Multiple/File_Mk.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Tag/File_Id3v2.cpp
Reducing XML output size
Still available with an option
> Attachments: do not provide anymore attachments content in XML by default

- Source/MediaInfo/Setup.h
- Source/MediaInfo/Video/File_Av1.cpp
Enabling AV1 parser was forgotten in https://github.com/MediaArea/MediaInfoLib/pull/802
> Enable AV1

- Source/MediaInfo/MediaInfo_Inform.cpp
x '\r' and '\n' strings converted to line separator
x missing trace in xml
> Fix output

- Source/MediaInfo/Audio/File_Flac.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Tag/File_Id3v2.cpp
Fixes for https://github.com/MediaArea/MediaInfoLib/pull/801.
Reported by @lordmulder  in https://github.com/MediaArea/MediaInfo/issues/227
> Attachments: do not provide anymore attachments content in XML by default, fixes

- Source/MediaInfo/Export/Export_Mpeg7.cpp
- Source/MediaInfo/MediaInfo_Config.h
[bcc32 Error] MediaInfo_Config.h(231): E2015 Ambiguity between 'MediaInfoLib::Char' and 'ZenLib::Char'
[bcc32 Error] Export_Mpeg7.cpp(1229): E2354 Two operands must evaluate to the same type
> Fix C++Builder 10.1

- Source/MediaInfo/Video/File_Hevc.cpp
At some point we should add messages when there is an error in the bitstream, but for the moment I didn't figure the best approach (with generic code for handling errors as much as possible, and not poluting the default output)
From vote https://mediaarea.net/Vote/Support-Buggy-Hevc-H-265-Sei-171
Issue from encoder, see https://github.com/rigaya/NVEnc/issues/51#issuecomment-393130636
> HEVC: Trying to better support buggy SEIs (missing rbsp_stop_one_bit)

- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/Resource/Text/DataBase/CodecID_Audio_Riff.csv
fix for https://github.com/MediaArea/MediaInfoLib/issues/594 (is a MOV but use WAV CodecIDs)
@Sami32
> WAV: Support of CodecID 19D

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Also prevent float to integer overflow (sometimes crash, depending of the environment configuration)
Fix for https://github.com/MediaArea/MediaInfo/issues/173.
> MPEG-4: consider duration of -1 as unknown.

- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/MediaInfo_Config.cpp
- Source/MediaInfo/MediaInfo_Config.h
Quick and dirty code for being able to disable carriage return replacement when reading metadata.
@Sami32 add MediaInfo::Option("CarriageReturnReplace", "") in your code before calling MediaInfo::Open and you'll get the field as is (without modifications, so containing carriage returns)
> CarriageReturnReplace option

- Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
Show the highest format detected, instead of the lowest one.
Examples:
- "AAC LC SBR PS" instead of "AAC" because a LC decoder with SBR and PS support is needed for fully decoding it (else only the 24 kHz / 1 channel part is decoded)
- "E-AC-3 JOC" instead of "E-AC-3" because an E-AC-3 decoder with JOC (Atmos) support is needed for fully decoding it (else the Atmos part is ignored)
> HighestFormat option set to true by default

- Source/MediaInfo/MediaInfo_Config.cpp
No more display of how legacy decoders handle streams with additional features e.g. AAC LC with SBR and PS now only display 48 KHz / 2 channels instead of also showing 24 kHz / 1 channel as handled by a non SBR/PS aware decoder.
> LegacyStreamDisplay option set to false by default

- Source/MediaInfo/Audio/File_Ac3.cpp
- Source/MediaInfo/Audio/File_Dts.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
- Source/MediaInfo/MediaInfo_Internal.cpp
Trying to get the same channel names in ChannelLayout whatever is the format.
Goal with ChannelLayout is also to get the decoder channel order (to be confirmed).
Use option ` --ChannelLayout=0` for having names for the spec of each format
> ChannelLayout: same name whatever is the format by default 

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.h
Obey edit list in QuickTime timecode tracks. Fixes reporting for the sample file in:
https://sourceforge.net/p/mediainfo/bugs/1005/
Signed-off-by: Peter Chapman <peterc@telestream.net>
> + Fix #1005: Obey edit list in QuickTime Timecode track

- Source/MediaInfo/MediaInfoList_Internal.cpp
- Source/MediaInfo/MediaInfo_Config.cpp
- Source/MediaInfo/MediaInfo_Config.h
`--ParseOnlyKnownExtensions` option:
- alone: filters all extensions known by MediaInfo
- "+XX" filters all extensions known by MediaInfo for the kind of format X, with X being M for containers able to handle several streams e.g. MP4, V for video, A for audio, I for images...
- "X,X" filters extensions X
- "-X,-X" removes an extension from the created list e.g. if you want extensions known by MediaInfo except "dat" (used by too many non A/V formats)
Examples:
- Filter all extensions known by Mediainfo:
`.\MediaInfo.exe --Inform=file://template.txt C:\Windows --ParseOnlyKnownExtensions`
- Filter all extensions known by Mediainfo for containers except .dat and add .bla & .bla2 to the list:
`.\MediaInfo.exe --Inform=file://template.txt C:\Windows --ParseOnlyKnownExtensions=+M,-dat,bla,bla2`
> ParseOnlyKnownExtensions option

- Source/MediaInfo/File__Analyze.h
- Source/MediaInfo/File__Analyze_MinimizeSize.h
- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/File__Analyze_Streams_Finish.cpp
- Source/MediaInfo/MediaInfoList_Internal.cpp
- Source/MediaInfo/MediaInfoList_Internal.h
- Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.h
- Source/MediaInfo/Multiple/File_Hls.cpp
- Source/MediaInfo/Multiple/File__ReferenceFilesHelper.cpp
Detect that an image sequence and an audio file are in a directory and are part of a package.
Classic usage : DPX + WAV.
As directory structure depends on the supplier, we need to adapt per supplier.
We start with this structure:
```
title-of-work/
title-of-work.wav
dpx/
title-of-work_0086880.dpx
title-of-work_0086881.dpx
... etc ...
```
> New format "Directory" when image sequence + audio file is detected

- Source/MediaInfo/Video/File_Mpegv.cpp
For MPEG2 streams, when a frame is encoded in the form of separate fields, MediaInfo erroneously detects second filed of an I-frame as a beginning of a new GOP. That leads to picture_coding_types being populated with I-frame only GOP consisting of I-frame's first fields and the remainder of the GOP with all but first frames being duplicated. That eventually breaks variable GOP detection.
I suggest considering only the first filed in calculations, in order to achieve expected behavior. In my tests, proposed changes didn't brake neither progressive stream handling, nor interlaced streams with picture structure "frame".
> MPEG2 variable GOP detectin fix

- Source/MediaInfo/Multiple/File_Mxf.cpp
additions to https://github.com/MediaArea/MediaInfoLib/pull/1021
>  MXF: display information when wrapper/essence values are detected as not same

- Source/MediaInfo/Export/Export_PBCore2.cpp
Fix #1032.
Remove test dedicated to Video (but without testing if the track is a video one), the generic test is enough.
> PBCore2: fix essenceFrameSize with non Video tracks

- Source/MediaInfo/Multiple/File_Mk.cpp
Hello,
in f1f2d80a9a8995f32e229b8aaade40a460490e40 you tried to solve issue #875 about added Matroska statistics tags that have been ignored, but you got the comparison of the dates wrong so that only tags that are newer than the file would be treated as invalid. You quickly noticed this and fixed it in 8579631710d4c726a7268822aeec84384b5a3b45, but you (most likely unintentionally) reversed this in eb0999b917054020f08daba490a87dcf41be8f2f. This PR is intended to fix this.
Greetings
mkver
> x I875, Matroska: Fix for added Statistics Tags

- Source/MediaInfo/Multiple/File_DcpCpl.cpp
- Source/MediaInfo/Multiple/File__ReferenceFilesHelper.cpp
- Source/MediaInfo/Multiple/File__ReferenceFilesHelper.h
Fix #992.
@kieranjol, I "merge" MXF files duration when I detect the same count of files per reel and the same kind of file in the same order for each reel (if reel 1 has Video then Audio, other reels must have Video then Audio too), in order to simplify the algorithm.
If count of files per reel or file kind order is different, I keep displaying each file in its each part, as I don't know yet how I would like to display that in MediaInfo in a readable way (how should it be actually displayed?), if I decide to support such kind of content one day.
I also display only the first file in the "Source" line, I am reluctant to display 10 file names in this MediaInfo field when there are 10 reels. The issue is not really technical and is not new (already implemented for IMF packages having …
> DCP: support of multi-reel DCP

- Source/MediaInfo/Reader/Reader_File.cpp
- Source/MediaInfo/Reader/Reader_File.h
- Source/MediaInfo/Reader/Reader_libcurl.cpp
- Source/MediaInfo/Reader/Reader_libcurl_Include.h
- Source/MediaInfo/Text/File_AribStdB24B37.cpp
Fix compilation issue when there is the combo C++17, windows.h, using namespace std
```
rpcndr.h(192): error C2872: 'byte': ambiguous symbol
```
> C++17, windows.h, using namespace std

- Source/MediaInfo/Multiple/File_Mxf.cpp
fix false positive truncated file detection when there is no Random Index Pack in MXF.
> MXF: fix false positive truncated file detection when there is no RIP

- Source/MediaInfo/Reader/Reader_File.cpp
- Source/MediaInfo/Reader/Reader_File.h
- Source/MediaInfo/Reader/Reader_libcurl.cpp
- Source/MediaInfo/Reader/Reader_libcurl_Include.h
- Source/MediaInfo/Text/File_AribStdB24B37.cpp
Issue reported in https://github.com/MediaArea/MediaInfoLib/issues/1079 about https://github.com/MediaArea/MediaInfoLib/pull/1076, trying another method.
`_MSVC_LANG` is there because [Microsoft decided to not comply to __cplusplus part of the C++ spec](https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus), for the moment [by default](https://blogs.msdn.microsoft.com/vcblog/2018/04/09/msvc-now-correctly-reports-__cplusplus/) (so it still doesn't comply in most cases).
> C++17, windows.h, using namespace std (update)

- Source/MediaInfo/Audio/File_Mpega.cpp
Impact is only on the [MediaTrace](https://mediaarea.net/MediaTrace) feature.
> MPEG Audio: protection_bit was not correctly handled

- Source/MediaInfo/Audio/File_Mpega.cpp
Some VBR files use "Info" Xing header, so we ignore the difference between "Info" and "Xing"
> MPEG Audio: Xing frame count header changes

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
32-bit release only.
We avoid to exactly compare float numbers.
Fix provided by https://github.com/MediaArea/MediaInfoLib/issues/943
> MPEG-4: wrong display aspect ratio in some corner cases

- Source/MediaInfo/Tag/File_VorbisCom.cpp
Fix https://github.com/MediaArea/MediaInfoLib/issues/1096.
> OGG: assign METADATA_BLOCK_PICTURE tag to cover

- Source/MediaInfo/File_Dummy.cpp
- Source/MediaInfo/MediaInfo_Internal.cpp
from https://github.com/MediaArea/MediaInfoLib/pull/1106#discussion_r273226825 + handle the typo in `MediaInfo::Get()` for legacy tools.
> Typos in language file, update

- Source/MediaInfo/MediaInfo_Inform.cpp
Fix https://github.com/MediaArea/MediaInfo/issues/339.
> Text in square brackets stripped in $if() section

- Source/MediaInfo/File__Analyze.cpp
- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Multiple/File_Riff.cpp
WAV: MP3 delay should be added to BWF time reference 
USAC: frame rate was missing in case of non standard sampling rate
Fix misbehavior of the buffering algo, leading sometimes to invalid reads
> Miscellaneous fixes

- Source/MediaInfo/File__Analyze.h
- Source/MediaInfo/File__Analyze_Buffer.cpp
- Source/MediaInfo/File__Analyze_Element.cpp
- Source/MediaInfo/File__Analyze_Element.h
- Source/MediaInfo/File__Analyze_MinimizeSize.h
- Source/MediaInfo/File__MultipleParsing.cpp
- Source/MediaInfo/MediaInfo_Internal.h
- Source/MediaInfo/Multiple/File_Mk.cpp
- Source/MediaInfo/Multiple/File_Mk.h
if MediaTrace is activated, it shows the content of the RAWcooked file inside the Matroska file.
@bturkus & @digitensions, it is a huge output but you can check the content of the RAWcooked file (DPX header, file MD5 presence...) this way (look for "XPDS" for the DPX header and "FileHash" for the MD5):
```
mediainfo "--Inform=Details;1" FileName.mkv
[...]
002F Segment (60511 bytes)
002F  Header (12 bytes)
002F   Name:                                 139690087 (0x8538067)
0033   Size:                                 60499 (0x0000000000EC53)
[...]
0329  Attachments (2052 bytes)
0329   Header (12 bytes)
0329    Name:                                155296873 (0x941A469)
032D    Size:                                2040 (0x000000000007F8)
0335   CRC-32 (6 bytes)
0335    Header (2 bytes)
0335 …
```
> Parse of RAWcooked elements, also when in Matroska file

- Source/MediaInfo/Multiple/File_Mk.cpp
- Source/MediaInfo/Multiple/File_Mk.h
- Source/MediaInfo/Video/File_Ffv1.cpp
For having [DV/MKV (or other/MKV!) comparison screenshot](https://twitter.com/pjotrek_b/status/1131445067284176896/photo/1) more coherent, showing the PCM bit rate also when in Matroska.
+ some cleanup / handling of default values.
cc @pjotrek-b
> Matroska: PCM bit rate

- Source/MediaInfo/Multiple/File_DvDif.cpp
For having [DV/FFV1 (or DV/other!) comparison screenshot](https://twitter.com/pjotrek_b/status/1131445067284176896/photo/1) more coherent.
cc @pjotrek-b
> DV: color space is explicit

- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/File__Analyze_Streams_Finish.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Frame rate line also for time code, in order to differentiate e.g. 30 fps vs 60 fps time codes
```
Frame rate                               : 29.970 (29970/1000) FPS
Time code of first frame                 : 01:16:13:09
```
> MOV: Time code frame rate

- Source/MediaInfo/Multiple/File_DvDif.cpp
Fix https://github.com/MediaArea/MediaInfo/issues/365.
> DV: DVCAM commercial name for locked audio and PAL 4:2:0

- Source/MediaInfo/Video/File_Hevc.cpp
Found 1 stream with nuh_temporal_id_plus1==0, lets disable this coherency test for the moment
> HEVC: remove nuh_temporal_id_plus1 check

- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Mxf.h
Also adds time code track name.
Part of work on https://github.com/MediaArea/MediaInfo/issues/361
> MXF: Time code frame rate

- Source/MediaInfo/Multiple/File_DvDif.cpp
- Source/MediaInfo/Multiple/File_DvDif.h
- Source/MediaInfo/TimeCode.cpp
- Source/MediaInfo/TimeCode.h
We were reading frame number as stored in the file, but there is a hack for 50/60 fps content with the frame number (limited to 5 bits so up to 31) storing the real frame number divided by 2 and another bit says if the real frame number is an odd number.
Part of work on https://github.com/MediaArea/MediaInfo/issues/361
>  DV: Time code frame number was wrong (divided by 2) for 50/60 fps content

- Source/MediaInfo/Audio/File_Usac.cpp
- Source/MediaInfo/File__Analyze.h
[bcc32 Error] File__Analyze.h(492): E2015 Ambiguity between 'MediaInfoLib::Char' and 'ZenLib::Char'
[bcc32 Warning] File_Usac.cpp(921): W8004 'nDrcChannelGroups' is assigned a value that is never used
> * Fix C++Builder 10.x

- Source/MediaInfo/Multiple/File_Mxf.cpp
Fix bug hen parsing MCA labels introduced in https://github.com/MediaArea/MediaInfoLib/pull/1123 (especially https://github.com/MediaArea/MediaInfoLib/commit/8cd27814677bf2f5e420a9c8779a5cd0bfe891a3#diff-606c0ec2e4c88f41d44231d80bc70645).
> MXF: basic refactoring of descriptors parser, with more heritage, fix

- Source/MediaInfo/Video/File_ProRes.cpp
Do not try to parse ProRes RAW as other ProRes, the frame header structure was reported as not being exactly same.
Just ignore the unknown frame header content up to when we can have more details about this bitstream.
> ProRes RAW: we know only width and height

- Source/MediaInfo/Text/File_Eia708.cpp
Hot fix, limiting windows width to 32 chars.
Could be later the full width by an event version change, if one needs it...
https://sourceforge.net/p/mediainfo/bugs/1108/
> EIA-708: fix crash with large windows

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
This patch adds audio channel description definitions for Discrete-16 to Discrete-31 for Quicktime movies.
Post Production regularly makes 24+ channel Quicktime files for network delivery with discrete labeled audio.
> add mov discrete audio channel description definitions for Discrete-16 to Discrete-31

- Source/MediaInfo/Video/File_Avc.cpp
Nullptr exception when there is no h264 vui in some mp4 files, which have DTVCC embedded in h264 SEI message.
> Nullptr exception when there is no vui in some mp4 files

- Source/MediaInfo/Image/File_Dpx.cpp
Fix https://github.com/MediaArea/MediaInfoLib/issues/1190.
> DPX: ColorimetricSpecification and TransferCharacteristic were inverted

- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Usually it is `nclc `but in MP4 spec it is `nclx `(it adds colour range, limited or full).
> MPEG-4: support of colr/nclx box

- Source/MediaInfo/Video/File_Hevc.cpp
- Source/MediaInfo/Video/File_Hevc.h
Avoid false-positive while accepting buggy but not too buggy HEVC streams by using a percentage of trust in the stream.
Next step would be to do same for all formats.
> HEVC: do not reject buggy but not too buggy streams

- Source/MediaInfo/File__Analyze.h
- Source/MediaInfo/File__Analyze_MinimizeSize.h
- Source/MediaInfo/Video/File_Hevc.cpp
- Source/MediaInfo/Video/File_Hevc.h
Found a file with 0x000001 sync inside a "File format" content (in a block in a MP4 sample), even if it is expected to have only one NAL per block.
Note: it is supported in several other players, so I guess that it is relatively common.
> HEVC: better support of MP4 files with Stream format inside a block

- Source/MediaInfo/Video/File_Avc.cpp
File_Avc.cpp::pred_weight_table
Currently there is only one set of chroma weight/offset
values read per list(l0, l1), after all the luma coefficient sets.
But I believe there should be two sets for each set of luma
coefficients.
Noticed when mediatrace returned a value of -355 for
slice_beta_offset_div2, which has range (-6,+6), and 21 for
disable_deblocking_filter_idc in range (0,+2). 😄
> AVC slice header - chroma weight table fix

- Source/MediaInfo/File__Analyze_Streams_Finish.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp
Add support of [Dolby Vision 2 metadata](https://www.dolby.com/us/en/technologies/dolby-vision/dolby-vision-bitstreams-within-the-iso-base-media-file-format-v2.1.2.pdf).
> Dolby Vision: support of Dolby Vision 2

- Source/MediaInfo/Multiple/File_DvDif.cpp
- Source/MediaInfo/Multiple/File_DvDif.h
- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Audio is split in "channel groups" (1 group for DV25, 2 groups for DV50, 4 groups for DV100)
Each "channel group" has 2 "channels", first channel in Dseq 0-4 and second channel in Dseq 5-9 (note: if 2-bit 32 kHz, each "channel" contains actually 2 real channels)
For each channel:
- We consider all audio blocks of a Dseq as invalid if audio mode of this Dseq of this channel group is 0xF (15)
- We consider all audio blocks as invalid if the frame (all channels) has no audio_source but had audio_source for this channel in the latest frame having at least 1 audio_source.
- We consider a block as invalid if full of 0x8000 (16-bit and 12-bit) or 0x800 (12-bit)
A channel group (its both channels) is considered as active if:
- at least 1 audio_source is found for this channel group
- no …
> DV analysis: update of the invalid data detection algorithm

- Source/MediaInfo/File__Analyze_Streams_Finish.cpp
when relevant.
Hidden by default.
(partial PR as the first part was inadvertently merged in a previous PR)
>  Indicate that the duration comes from the global duration in container

- Source/MediaInfo/File__Analyze.h
- Source/MediaInfo/File__Analyze_MinimizeSize.h
- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/File__Analyze_Streams_Finish.cpp
- Source/MediaInfo/MediaInfoList_Internal.cpp
- Source/MediaInfo/MediaInfo_Config.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.h
- Source/MediaInfo/MediaInfo_Inform.cpp
- Source/MediaInfo/Multiple/File_MiXml.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/OutputHelpers.cpp
Tree and text views can have something like (with presentation 1 merging signal groups 1 & 2, presentation 2 merging signal groups 1 & 3):
```
+ Presentation 1
+- Loudness
+- DRC
+ Signal group 1
+- Type: Bed channels
+- Channel mode: 7.1.4
+ Signal group 2
+- Type: Dialog
+- Language: English
+- Channel mode: 1.0
+ Presentation 2
+- Loudness
+- DRC
+ Signal group 1
+- Type: Bed channels
+- Channel mode: 7.1.4
+ Signal group 3
+- Type: Dialog
+- Language: German
+- Channel mode: 1.0
```
It will be useful for incoming support of multi-substreams audio streams.
Includes a couple of tiny fixes.
> Support of nested elements

- Source/MediaInfo/Video/File_Avc.cpp
Also handle scan order when pic_order_cnt_lsb is same for both fields
> AVC: fix frame rate value when pic_order_cnt_type and interlaced content

- Source/MediaInfo/Multiple/File_Riff.h
- Source/MediaInfo/Multiple/File_Riff_Elements.cpp
Used in association to "cue" chunk, and needed for helping to see content in https://github.com/MediaArea/BWFMetaEdit/issues/107.
> WAV: trace of adtl (Associated Data List) chunk

- Source/MediaInfo/Multiple/File_Wm_Elements.cpp
Fix https://sourceforge.net/p/mediainfo/feature-requests/545/
> WM: show legacy value of performer if not same as modern one

- Source/MediaInfo/Audio/File_Aac_Main.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
- Source/MediaInfo/Multiple/File_DvDif.cpp
- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
@kieranjol @dericed I was disturbed 😋 by "2037-02-00" date in your files.
I ignore rec_date full of 0xFF or even when only year is 0xFF or when day is 0x00 etc.
> DV: ignore rec_date/rec_time full of 0xFF or incoherent

- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Fix https://github.com/mipops/dvrescue/issues/85
(@dericed no report of bad VAUX, for a next PR, maybe something more global with different coherency tests)
> DV: skip incoherent VAUX

- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
when source/source_control is missing
Fix https://github.com/mipops/dvrescue/issues/63.
> DV Analysis: keep former source/source_control for video & audio

- Source/MediaInfo/File__Analyze.cpp
Fix https://github.com/MediaArea/MediaInfo/issues/454 "HTTP server doesn't seem to support byte ranges. Cannot resume." with HTTP links and MP4 files with header at the end.
> Don't seek to the end (false positive range related error with HTTP)

- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Fix https://github.com/mipops/dvrescue/issues/113
(stupid bad typo...)
> DV analysis : fix non-continuous recording date/time false detection

- Source/MediaInfo/Image/File_Dpx.cpp
We actually don't need to load the whole ImageData, as we don't have to parse it
Fix https://github.com/MediaArea/MediaInfoLib/issues/1273.
> DPX: don't load the whole file in RAM

- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/File__Analyze_Streams_Finish.cpp
Useless and potential XML output validation issue.
Also reformat if BOM indicates a wrong order of bytes.
Referenced in https://github.com/sbraz/pymediainfo/issues/90#issuecomment-646915113.
> Remove UTF-8 BOM from metadata if present

- Source/MediaInfo/Audio/File_Mpegh3da.cpp
- Source/MediaInfo/Audio/File_Mpegh3da.h
Display of position of speakers when `mpegh3daFlexibleSpeakerConfig` is used.
The format follows ISO/IEC 2000-3 without the "CH_" prefix (not useful as the field is dedicated to channels), e.g. `U045_R135` (upper elevation 45°, right azimuth 135°).
To do: map to known [channel layouts](https://mediaarea.net/AudioChannelLayout) when relevant.
> MPEG-H 3D Audio: support of mpegh3daFlexibleSpeakerConfig

- Source/MediaInfo/Tag/File_VorbisCom.cpp
DISCID field seems legitimate for most files, so we don't ignore it anymore.
> VorbisTag: DISCID is legitimate

- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Fix https://github.com/mipops/dvrescue/issues/122.
(memory is set as available too soon)
> DV DIF Analysis: fix memory corruption

- Project/CMake/CMakeLists.txt
- Project/GNU/Library/Makefile.am
- Project/MSVC2013/Library/MediaInfoLib.vcxproj
- Project/MSVC2013/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2015/Library/MediaInfoLib.vcxproj
- Project/MSVC2015/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2017/Library/MediaInfoLib.vcxproj
- Project/MSVC2017/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2017/Library/MediaInfoLib_UWP.vcxproj
- Project/MSVC2019/Library/MediaInfoLib.vcxproj
- Project/MSVC2019/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2019/Library/MediaInfoLib_UWP.vcxproj
- Source/MediaInfo/Audio/File_ChannelSplitting.cpp
- Source/MediaInfo/Audio/File_ChannelSplitting.h
- Source/MediaInfo/Audio/File_Pcm.cpp
- Source/MediaInfo/Audio/File_SmpteSt0337.cpp
- Source/MediaInfo/File__Analyze_Streams_Finish.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Mxf.h
- Source/MediaInfo/Multiple/File_Riff.cpp
- Source/MediaInfo/Multiple/File_Riff_Elements.cpp
- Source/MediaInfo/Multiple/File__ReferenceFilesHelper.cpp
e.g. a WAV file may have a 8-ch tracks actually containing 4 Dolby E tracks, each track containing 2 programs.
Supported in WAV/MXF/MP4.
& several Dolby E related minor fixes found during the development.
> Detection of Dolby E hidden in tracks having more than 2 channels

- Source/MediaInfo/Image/File_Png.cpp
Fix [this Google play comment](https://play.google.com/store/apps/details?id=net.mediaarea.mediainfo&hl=ru&reviewId=gp%3AAOqpTOHvoqrzB3zulPR0UVFnjLeZqBZqPV36JZY4rmtrvWXePKEDd5fc_eoVKWFfWaNU0yulRvGuwXCKwJtw4EQ).
> PNG: compression is Deflate (LZ77+Huffman), not LZ77

- Source/MediaInfo/MediaInfo_Events.h
- Source/MediaInfo/Multiple/File_DvDif.h
- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Part of https://github.com/mipops/dvrescue/issues/123.
> DVRescue: add pack presence and conceal info

- Source/MediaInfo/Multiple/File_Mpeg_Descriptors.cpp
With dual PID profile 7 streams, the DOVI descriptor can include the dependency_pid field.
Cf. dolby-vision-bitstreams-in-mpeg-2-transport-stream-multiplex-v1.2.pdf:
> Add dependency_pid in DOVI descriptor

- Source/MediaInfo/Image/File_Png.cpp
- Source/MediaInfo/Image/File_Png.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Riff_Elements.cpp
Better support of alpha channel detection in several containers: PNG (alone or in MOV/MP4), AVI, MXF.
> Alpha channel

- Project/CMake/CMakeLists.txt
A more flexible, more generic and recommended setting of CMAKE_MODULE_PATH. See examples here:
https://cgold.readthedocs.io/en/latest/tutorials/cmake-sources/includes.html#modify-correct
https://cgold.readthedocs.io/en/latest/tutorials/cmake-sources/includes.html#modify-incorrect
With this change, parent projects are able to propagate custom modules to MediaInfoLib, like a custom FindZenLib.cmake file.
> Recommended setting of CMAKE_MODULE_PATH

- Source/MediaInfo/Audio/File_DolbyE.cpp
> Fix undeclared INT8_MIN/INT8_MAX with c++03 compilers

- Source/MediaInfo/Audio/File_DolbyE.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
and don't show the position in the object summary
> Dolby ED2: don't convert object Cartesian positions to a channel layout

- Source/MediaInfo/Multiple/File_Riff_Elements.cpp
Not by default for not overloading the output, but available with "-f" option in text mode, or XML or JSON.
Example:
```
bext_Version                             : 1
```
(`bext` being the technical name of the BWF related chunk)
Fix https://github.com/MediaArea/MediaInfo/issues/493, cc @thorsted @dericed @kmurmur
> WAV: show bext (BWF) version in verbose mode / XML / JSON

- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Fix of the PR https://github.com/MediaArea/MediaInfoLib/pull/1295.
Fix https://github.com/mipops/dvrescue/issues/144.
> DVRescue: add pack presence and conceal info, fix

- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Partially fix https://github.com/mipops/dvrescue/issues/129 (the VAUX part).
> DVRescue: skip incoherent VAUX

- Source/MediaInfo/Multiple/File_DvDif.h
- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Consider a 0xFFFF byte pair as "valid" (no parity check on it).
Ignore the captions not in the first part of a DV50/DV100 frame (they are expected to be duplicated content: TODO: check that it is duplicated content).
> DVRescue: ignore 0xFFFF blocks, ignore duplicated content

- Source/MediaInfo/Image/File_Tiff.cpp
These were defined in the [Adobe Photoshop Technical Notes from 2002](https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFFphotoshop.pdf), a link to which has also been included. The document outlines Deflate compression as well as a better method for using JPEG compression in TIFFs than was previously defined in the TIFF v6 specification (which was released prior to JPEG's ISO standardization).
Also, keep up the great work. It's much appreciated.
> Add support for TIFF compression codes 7 and 8

- Source/MediaInfo/Multiple/File_Riff.cpp
A WAV malformed chunk size test is applied to a RF64 file but without using the RF64 data chunk size, so the check was done inside the data chunk instead of at the end.
> RF64: fix the WAV malformed chunk size test

- Source/MediaInfo/File__Analyze.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Randomness is due to the size of the input blocks if a block from disk or an URL ends inside after the content part + few bytes, the nested elements are not detected so discarded.
> MPEG-4: Fix of random bad parsing when atoms have both own content and nested atoms

- Source/MediaInfo/File__Analyze.cpp
Typo preventing the detection to work when small buffers are provided.
Fix https://github.com/MediaArea/MediaInfo/issues/504.
> AVC: fix detection of non raw stream

- Source/MediaInfo/Audio/File_Aac_GeneralAudio.cpp
Looks like constants are messed up:
ISO/IEC 14496-3:2009 section 4.6.8.2.3
```
function is_intensity(group,sfb) {
+1 for window groups / scalefactor bands with right channel
codebook sfb_cb[group][sfb] == INTENSITY_HCB
-1 for window groups / scalefactor bands with right channel
codebook sfb_cb[group][sfb] == INTENSITY_HCB2
0 otherwise
}
```
ISO/IEC 14496-3:2009 section 4.6.3.2
```
INTENSITY_HCB2 14
INTENSITY_HCB 15
```
> Fix File_Aac::is_intensity according to ISO/IEC 14496-3:2009

- Source/MediaInfo/Audio/File_DolbyE.cpp
A few places were assigning INT_MIN or INT_MAX to A.obj_gain_db when it's only 8-bits wide and is documented as using INT8_MIN and INT8_MAX as its special values.
Most places in the code use the correct constants, but three were missing the "8".
> INT_MAX/MIN used where INT8_MAX/MIN should be

- Source/MediaInfo/File__Analyze.cpp
- Source/MediaInfo/MediaInfoList_Internal.cpp
- Source/MediaInfo/MediaInfo_Internal.cpp
- Source/MediaInfo/Multiple/File_DvDif.cpp
- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Accept stdin as file input (`mediainfo -`).
Can demux DV (split per frame).
Part of https://github.com/mipops/dvrescue/issues/86.
> DVRescue: read from stdin

- Source/MediaInfo/File__Analyze_Streams.cpp
This it due to the fact Meta.Luminance not being float, fixes #1116. That was an always true expression, so in all cases Meta.Luminance[1] (that element in array is mastering max. luminance) was truncated to integer values (Ztring::ToZtring precision set to 0), which is very problematic.
The other idea is to set precision to 4 always.
> HDR mastering max. luminance precision was wrong

- Source/MediaInfo/MediaInfoList_Internal.cpp
This fixes https://github.com/MediaArea/MediaInfoLib/issues/1359 as directory paths with ':' in them go into the dir path. Everything else just uses the file_path directly.
> Simplify the logic in MediaInfoList_Internal::Open

- Source/MediaInfo/Multiple/File_Wm_Elements.cpp
The Windows Media parsing code tried to handle "WM/EncodingTime" but was failing because the value is a FILETIME, which uses units of 100 nanoseconds from 1601, but it was passing the value as-is to something that expects seconds from 1601. Just needs a division by 10000000 to fix.
I found a side-effect of fixing this which could be a breaking change for dependencies:
- File_Wm::Header_FileProperties sets Stream_General / General_Encoded_Date to the CreationDate from the header.
- With this fix in place, File_Wm::Header_ExtendedContentDescription also sets Stream_General / General_Encoded_Date to the "WM/EncodingTime" date-time (if the file has the tag).
- This results in MI.Get("Encoded_Date") returning a string with two date-times. For example:
"UTC 2005-11-03 16:04:06.505 / UTC …
> Fix parsing of WM/EncodingTime

- Source/MediaInfo/Multiple/File_DvDif.cpp
- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Fix https://github.com/mipops/dvrescue/issues/214.
```
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.1">
<creator>
<program>dvrescue</program>
<version>0.20.11.20210227dev</version>
</creator>
<media ref="BCD00216_take2_1st_120000000_2400000.dv" format="DV" size="120000">
<frames count="1" pts="00:00:00.000000" end_pts="00:00:00.033367" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2">
<frame n="0" pos="0" pts="00:00:00.000000" abst="3842" tc="00:00:00:00" rec_start="1" seqn="F">
<dseq n="0">
<aud n="9"/>
</dseq>
<dseq …
```
> DvDif: remove check of zeroed bytes in timecode, considered again as valid timecode

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Remove code from https://github.com/MediaArea/MediaInfoLib/pull/1338 which should never have been there.
Fix https://github.com/MediaArea/MediaInfoLib/issues/1371.
> MOV/MP4: avoid stop of parsing when huge atoms are present, fix

- Source/MediaInfo/Multiple/File_DvDif.cpp
- Source/MediaInfo/Multiple/File_DvDif.h
- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
https://github.com/MediaArea/MediaInfoLib/pull/1365 creates some false positives with super buggy files.
Trying to avoid them
- Handle Absolute track number with steps of 5 (current frame start value in the middle of the values from previous frames)
- Handle Absolute track number with steps of 15 (2 then 1 pattern for each Dseq)
- Handle Absolute track number with "random" values in the up to 40 places found; this is [heuristic](https://en.wikipedia.org/wiki/Heuristic)
- Handle negative Absolute track number
> DvDif: Absolute track number + Blank flag, update

- Source/MediaInfo/Multiple/File_Mk.cpp
warning C4189: 'MasteringMetadata': local variable is initialized but not referenced
> File_Mk 'MasteringMetadata': local variable is initialized but not referenced

- Source/MediaInfo/Audio/File_Ac3.cpp
- Source/MediaInfo/Audio/File_Ac4.cpp
as it becomes the defacto standard layout (reference decoders do the reordering too).
> AC-3/AC-4: top layer channels after Lw/Rw

- Source/MediaInfo/File__Analyze.h
- Source/MediaInfo/File__Analyze_MinimizeSize.h
- Source/MediaInfo/Multiple/File_Mxf.cpp
This change unifies the HDR10 metadata handling in Mxf to use the same code as used already by other formats (MP4, Mk etc). Having them separate could introduce differences between the string representations (e.g. "DCI P3" primaries were not recognised in MXF but were in MP4 before this change.
> Use File__Analyze HDR metadata formatting in File__Mxf

- Source/MediaInfo/Multiple/File_DvDif.cpp
- Source/MediaInfo/Multiple/File_DvDif.h
- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Note: PTS is related to the DV stream only, container PTS offset e.g. QuickTime edit list is not (yet) handled.
Part of handling of https://github.com/mipops/dvrescue/issues/284.
> DV: fix PTS/DUR info

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Encrypted audio files were not having their codec correctly filled as this line is using the wrong StreamKind
> Fix stream type on encrypted audio mp4

- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Suggestion for https://github.com/mipops/dvrescue/issues/290, while finding a better way.
> DV: width/height/chroma when stype is 1

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Fix https://github.com/buzz/mediainfo.js/issues/75.
> MPEG-4: read too much data with some predecessor definitions

- Source/MediaInfo/File__Analyse_Automatic.h
- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/Resource/Text/Language/DefaultLanguage.csv
- Source/Resource/Text/Stream/Video.csv
(Unmodified) Android stores high frame rate streams with a "normal" 30 fps stream + MP4 metadata about the real (capture) frame rate.
We show both play back frame rate and real frame rate:
~~~
Frame rate mode                          : Variable
Frame rate                               : 30.045 FPS
Minimum frame rate                       : 28.644 FPS
Maximum frame rate                       : 33.100 FPS
Real frame rate                          : 120.000 FPS
~~~
> MP4/QuickTime: Android slow motion real frame rate

- Source/MediaInfo/Video/File_DolbyVisionMetadata.cpp
Example with an MXF ISXD file:
```
Video
HDR format                               : Dolby Vision Metadata, Version 5.1.0
Frame rate                               : 24.000 FPS
Color space                              : RGB
Title                                    : track name
Color range                              : Full
Color primaries                          : Display P3
Transfer characteristics                 : PQ
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
```
> Dolby Vision Metadata XML: support of versions 4 and 5 and readout of more elements

- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Dolby Vision Metadata XML can be in a sidecar track, example with a MOV ProRes + Dolby Vision Metadata:
```
Video
ID                                       : 1
Format                                   : ProRes
Format version                           : Version 1
Format profile                           : 4444 XQ
HDR format                               : SMPTE ST 2086, HDR10 compatible / Dolby Vision Metadata, Version 4.0.2
Codec ID                                 : ap4x
Duration                                 : 2 s 458 ms
Bit rate mode                            : Variable
Bit rate                                 : 389 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame …
```
> MOV/MP4: support of Dolby Vision Metadata XML

- Source/MediaInfo/Audio/File_Adm.cpp
- Source/MediaInfo/Audio/File_Adm.h
- Source/MediaInfo/Audio/File_ChannelSplitting.cpp
- Source/MediaInfo/Audio/File_SmpteSt0337.cpp
- Source/MediaInfo/Multiple/File_Riff_Elements.cpp
With ADM we can have now a single AES3 half stream (subsample mode) in addition to AES3 pairs.
> SMPTE ST 337: support of odd number of channels

- Project/GNU/Library/Makefile.am
Fixes unresolved symbols when compiling with system tinyxml2.
> ADM: compile-in tfsxml unconditionally (unrelated to tinyxml2)

- Source/MediaInfoDLL/MediaInfoDLL.cs
The C# example [HowToUse_Dll.cs](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/Example/HowToUse_Dll.cs) is treating the `Status` Enum as a flagged Enum. Although the example technically works, the Enums should be decorated with the Flags attribute to get the full support of flagged Enums in C#. Looks like the `InfoFileOptions` is a bitwise Enum as well, so decorating with the `Flags` attribute, too.
> Update C# bitwise Enums to be treated as bitfields

- Source/MediaInfo/Audio/File_Mpega.cpp
From discussion in https://github.com/MediaArea/MediaInfoLib/issues/1066#issuecomment-966910868.
> MPEG Audio: detect Xing header even if the bytes after the Xing frame are garbage

- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Update of https://github.com/MediaArea/MediaInfoLib/pull/1416, fix https://github.com/mipops/dvrescue/pull/340#issuecomment-955574373.
> DV: check timecode and seqn jump in past

- Source/MediaInfo/Video/File_Av1.cpp
- Source/MediaInfo/Video/File_Av1.h
AV1 parser reads two bytes for _metadata_type_. This is incorrect. The wrong _metadata_type_ is read, which causes lack of HDR metadata for AV1 streams.
According to the [AV1 spec](https://aomediacodec.github.io/av1-spec/av1-spec.pdf) (see section: _5.8.1. General metadata OBU syntax_), this should instead be a `leb128` type.
This is further confirmed by:
* [aom av1 decoder obu.c](https://aomedia.googlesource.com/aom/+/2e6b85e5d7d87fc2f4b4b04e55f5108604d676db/av1/decoder/obu.c#772)
* [rav1e metadata encoding function](https://github.com/xiph/rav1e/blob/7960160f186149a47a99f7a3e4c52851018266dc/src/header.rs#L220-L262) (line 233 specifically)
* This AV1 HDR sample: [HDR10_SIZZLE_PLUS_UP-FINAL_02_AV1.mp4](https://hdr10plus.org/av1_sample/HDR10_SIZZLE_PLUS_UP-FINAL_02_AV1.mp4)
```
General …
```
> AV1: fix parsing of metadata OBU type

- Source/MediaInfo/Multiple/File_Mk.cpp
Without this changeset, the ENCODER_SETTINGS tag would not display if set in Matroska tags, vs. setting it into h264/h265 stream. This allows setting this flag on bitstreams that do not allow such tags, for example, AV1.
Entry will display as `Encoding settings` instead of `ENCODER_SETTINGS` and be able to use language system.
> MKV: Include "Encoding settings" from ENCODER_SETTINGS tag

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Fix https://github.com/MediaArea/MediaInfoLib/issues/1465.
> MP4/MOV: avoid to fill again the max bit rate if it is also in descriptors

- Source/ThirdParty/tfsxml/tfsxml.c
The tiny tfsxml lib is intended for maximum compatibility and some compilers are still using not supporting C99 by default, so let's keep avoiding C99.
> Avoid "modern" C when not needed

- Source/MediaInfo/Audio/File_DolbyE.cpp
Distinct structs with this name are defined in:
* Source/MediaInfo/Audio/File_DolbyE.cpp (used only in the same file)
* Source/MediaInfo/Audio/File_Mpegh3da.h (used also in File_Mpegh3da.cpp)
This violates the One Definition Rule and may potentially lead to runtime problems if runtime type information is ever used, if the types ever gain virtual tables, or if same-signature functions are defined for both types. For a plausible example, this can happen if `File_DolbyE` starts using `std::vector<speaker_info>`, which will generate some member function template instantiations that will have the same names and signatures as the ones already generated by `File_Mpegh3da` (which already uses this vector type) but different code (because the structs’ layouts are different). Depending on exact …
> Fix MediaInfo::speaker_info naming two different types

- Project/CMake/cmake/modules/FindTinyXML.cmake
This PR implements a small change to allow tinyxml to be found under Windows.  Closes #1452.
> [cmake] Allow FindTinyXML to search for tinyxml under Windows

- Source/MediaInfo/Video/File_Avc.cpp
- Source/MediaInfo/Video/File_Hevc.cpp
Fix infinite loop with some files after https://github.com/MediaArea/MediaInfoLib/pull/1417.
The AVC part is for security, should never happen due to forced SPS parsing after sync but it may be removed in the future and would trigger the same issue
> HEVC CEA-608/708 support, fix (infinite loop after seek and no new SPS)

- Source/MediaInfo/File__Analyse_Automatic.h
- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/MediaInfo/Text/File_Ttml.cpp
- Source/MediaInfo/TimeCode.cpp
- Source/MediaInfo/TimeCode.h
- Source/Resource/Text/Stream/Text.csv
Also prepare for hh:mm:ss.zzzzzzzzzSfffffffff style support (used by ADM)
> TTML: correct handling of 29.97 DF time codes

- Source/MediaInfo/Multiple/File_DvDif.cpp
- Source/MediaInfo/Multiple/File_DvDif.h
- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Check FSC value of all blocks of a frame instead of the last header block available. It permits to accept corrupted blocks.
If there are too many corrupted blocks FSC value is considered unknown.
We should do same for other items e.g. FSP, for another PR.
Fix https://github.com/mipops/dvrescue/issues/424.
> DV: Handle FSC value even if some blocks are corrupted

- Source/MediaInfo/MediaInfo_Events.h
- Source/MediaInfo/Multiple/File_DvDif.h
- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Instead of only 0x8000 as indicated in the standards.
Fix https://github.com/mipops/dvrescue/issues/418
> DV: consider audio with any value repeated as concealed audio

- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
Instead of only 0x8000 as indicated in the standards
Except 0x0000 and 0xFFFF (silence)
(Update of https://github.com/MediaArea/MediaInfoLib/pull/1475 with 0xFFFF value support and crash fix)
> DV: consider audio with any value repeated as concealed audio, update

- Source/MediaInfo/File__Analyze_Streams.cpp
(actually DTS can have more bitrates)
Revert https://github.com/MediaArea/MediaInfoLib/pull/1477
> DTS: revert provide exact bitrate when bitrate is estimated in a generic manner

- Source/MediaInfo/Multiple/File_Mk.cpp
No parser had been implemented for the VP9 codec, and the MKV analyzer was
not reporting Delay for any codec without a parser.
Since the parser is not actually necessary to extract the accurate Delay for
MKV video files, I did not fix this by implementing a VP9 parser; rather I
allowed the MKV analyzer to report a Delay if no parser is present.
With the Delay value detected correctly, the Duration can now be calculated
correctly as well.
This test video is an excerpt from [Big Buck Bunny](https://peach.blender.org/about/) which is copyright 2008, [Blender Foundation](https://www.blender.org/foundation/) and licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0/).
[test_video_000000002.zip](https://github.com/MediaArea/MediaInfoLib/files/4732455/test_video_000000002.zip) …
> MKV/WebM: Report Delay and Duration correctly for VP9 MKV/WebM files.

- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/Text/File_Ttml.cpp
- Source/MediaInfo/TimeCode.cpp
e.g.
``` 
<tt xmlns="http://www.w3.org/ns/ttml"
xml:lang="en"
ttp:frameRate="24"
ttp:frameRateMultiplier="1000 1001">
<body>
<div>
<p begin="24f" end="48f">Hello</p>
</div>
</body>
</tt>
```
leads to:
```
Duration                                 : 00:00:01.001 (00:00:01:00)
Start time                               : 00:00:01.001 (00:00:01:00)
End time                                 : 00:00:02.002 (00:00:02:00)
```
> TTML: support of timestamps in frames

- Source/MediaInfo/Audio/File_Ac3.cpp
It was OK only for AC-3 or E-AC-3 having a AC-3 core.
> E-AC-3: service kind was not correctly handled

- Source/MediaInfo/MediaInfo_Inform.cpp
Due to historical reasons, audio Format_Profile separated by " / " are compatibility profiles e.g. "HE-AACv2 / HE-AAC / AAC", and we don't want to remove the different profiles for other stream kinds because profiles listed are all modern e.g. "SMPTE-TT / EBU-TT / IMSC1" for TTML.
> XML: does not remove several Format_Profile values except for audio

- Source/MediaInfo/Multiple/File_DvDif.h
- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
There were some incoherencies in the algo for detecting rec date/time or timecode lesser than the previous value (so in DVRescue ` rdt_nc="2"` of ` tc_nc="2"`).
There were some incoherencies with repeated time codes e.g.
00:00:00:00
00:00:00:00 --> ` tc_r="1"`
00:00:00:01 --> ` tc_nc="1"`
(it was previously expecting 00:00:00:02 only, as if the previous time code was wrong, now supporting "wrong" time code and also the increment as if the previous frame was not repeated)
cc @dericed.
> DV: fix algorithm for detection non continuous timecode, fix non continuous direction

- Source/MediaInfo/Audio/File_DolbyAudioMetadata.cpp
- Source/MediaInfo/Audio/File_DolbyAudioMetadata.h
- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Riff.cpp
and some edits of the names of binaural render modes in order to match Dolby tools names.
> Dolby Audio Metadata: move of binaural render mode to sub-elements of ADM objects

- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Mxf.h
Old code was relying on a frame rate but the frame rate related code disappeared at some point.
Now using the new TimeCode class and showing frames instead of trying to show milliseconds.
Fix https://github.com/MediaArea/MediaInfoLib/issues/1508.
> MXF trace: SystemScheme1 TimeCodeArray StartTimecode milliseconds were always 0

- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.cpp
- Source/MediaInfo/TimeCode.cpp
- Source/MediaInfo/TimeCode.h
There are some files with weird config e.g. 25 fps with drop frame time code, trying to have a more coherent output in such cases
> TimeCode: handling of some corner cases

- Source/MediaInfo/Audio/File_Ac3.cpp
- Source/MediaInfo/Audio/File_Ac3.h
- Source/MediaInfo/Audio/File_DolbyAudioMetadata.cpp
- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/MediaInfo_Events_Internal.h
- Source/MediaInfo/Multiple/File_DvDif.cpp
- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
- Source/MediaInfo/Multiple/File_Gxf.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.cpp
- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Text/File_Scc.cpp
- Source/MediaInfo/Text/File_Ttml.cpp
- Source/MediaInfo/TimeCode.cpp
- Source/MediaInfo/TimeCode.h
- Source/MediaInfo/Video/File_Mpegv.cpp
timing like `begin="0.0388888h" dur="0.09167m"` is now supported.
With also refactoring of time code class in order to handle more corner cases.
> TTML: Support of more timeExpression flavors

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.h
Handle of multiplied frame count when frame rate is more than NumberOfFrames
Fix https://github.com/MediaArea/MediaInfoLib/pull/1511#issuecomment-1098269135.
> MPEG-4/MOV: support of time codes >30 fps

- Source/MediaInfo/Multiple/File_Mxf.cpp
Frame rate is read from linked component frame rate
> MXF: Include frame count in SDTI and SystemScheme1 time codes to time stamp conversion

- Source/MediaInfo/Audio/File_Aac.cpp
- Source/MediaInfo/Audio/File_Aac.h
- Source/MediaInfo/Audio/File_Aac_GeneralAudio.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.h
It permits to catch SBR (HE-AAC) and PS (HE-AACv2) in any frame, or at the opposite no check at all; default is first few frames.
Warning: CPU intensive.
Useful for [LeaveSD](https://github.com/MediaArea/LeaveSD).
> AAC: option for complete parse of all frames or none or partial

- Source/MediaInfo/Multiple/File_Nsv.cpp
- Source/MediaInfo/TimeCode.cpp
- Source/MediaInfo/Video/File_Avc.cpp
StarDiva behavior is buggy when the agenda is across 2 days, we try to keep as much info as possible from the agenda (but it is no more in synch with the file time line, it is "best effort").
> NSV: better handling of buggy StarDiva agenda negative timestamps

- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/File__Analyze_Streams_Finish.cpp
- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Text/File_Ttml.cpp
- Source/Resource/Text/Stream/Text.csv
Text frame rate becomes `29.970 (29970/1000) FPS`.
Close https://github.com/MediaArea/MediaInfo/issues/610.
> Frame rate precise numerator/denominator also for text streams in MOV

- Source/MediaInfo/Audio/File_Aac.cpp
- Source/MediaInfo/Audio/File_Aac.h
Fix of https://github.com/MediaArea/MediaInfoLib/commit/6eb6494f7658a658872c361b77b3ab3067fdaa54#r73156372
> AAC: option for complete parse of all frames or none or partial, update

- Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.h
- Source/MediaInfo/Multiple/File_DvDif.cpp
- Source/MediaInfo/Multiple/File_DvDif.h
- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
e.g. for DVRescue and deck input, we know that the provided frame is complete so we don't have to wait to the next bytes for probing if we have a DV50 frame in the case of a DV25 frame.
> DV: option for avoiding useless buffering in some use cases

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.h
Frame count computing was based on time code frame rate e.g. 24 instead of real frame rate e.g. 23.98.
> MOV/MPEG-4: Fix frame count for NDF non-integer frame rates

- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.h
Example:
```
Format                                   : QuickTime TC
Duration                                 : 22 s 22 ms
Frame rate                               : 23.976 (24000/1001) FPS
Time code of first frame                 : 00:00:00:00
Time code of last frame                  : 00:00:18:22
Discontinuities                          : 00:00:06:23-00:00:04:01
```
Require ` --ParseSpeed=0.7` or more.
Close https://github.com/MediaArea/MediaConch/issues/231.
> MOV/MPEG-4: List of QuickTime time code discontinuities

- Source/MediaInfoDLL/MediaInfoDLL.h
While using newest MediaInfoLib on Windows I wasn't able to compile without Unicode support. 
We must use the non-unicode name as LoadLibrary alias to LoadLibraryA on Windows when _UNICODE is not defined. Therefore LoadLibrary will only accept char*, not wchar_t*.
If we don't do that we get a compilation error when loading the library.
> Win32: Use non-unicode lib name when unicode is disabled

- Source/Resource/Text/Stream/Text.csv
Update (missing file update) of https://github.com/MediaArea/MediaInfoLib/pull/1577/files
> Text streams: show stream frame rate if not same as container frame rate , update

- Project/iOS/build.sh
According to Xcode 14 documentation:
> Deprecations
> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.
> 
> Xcode no longer builds bitcode by default and generates a warning message if a project explicitly enables bitcode: “Building with bitcode is deprecated. Please update your project and/or target settings to disable bitcode.” The capability to build with bitcode will be removed in a future Xcode release. IPAs that contain bitcode will have the bitcode stripped before being submitted to the App Store. Debug symbols for past bitcode submissions remain available for download. (86118779)
> Because bitcode is now deprecated, builds for iOS, tvOS, and watchOS no longer include …
> Remove the support for bitcode (ios)

- Project/GNU/PKGBUILD
python2 support removed from Arch Extra
> Remove python2-mediainfo Arch package

- Source/MediaInfo/Audio/File_Pcm.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Video/File_ProRes.cpp
- Source/MediaInfo/Video/File_ProRes.h
Fix https://github.com/MediaArea/MediaInfo/issues/655.
Also support correctly FFmpeg glbl atom. Skip all glbl elements but the color range, so ProRes can now have color range info.
> MOV/MP4: avoid to parse lot of frames if parser fails to parse the frames

- Project/MSVC2022/Library/MediaInfoLib.vcxproj
- Project/MSVC2022/RegressionTest/RegressionTest.vcxproj
The MSVC2022 project Includes point to the MSVC2019 project for ZenLib. Point to the MSVC2022 project instead to prevent build failures on systems with only the v143 toolset.
> Fix MSVC2022 project Includes

- Source/MediaInfo/TimeCode.cpp
Some code reordering in order to avoid a "fatal  error C1001: Internal compiler error" error from newest VS2022 in release mode.
Fix https://github.com/MediaArea/MediaInfoLib/issues/1621.
> VS2022 v17.5 does not like a specific valid code

- Source/MediaInfo/Audio/File_Aac_GeneralAudio_Sbr.cpp
Modified bs_amp_res value to handle correctly when bs_coupling=1 in sbr_channel_pair_element().
If the bs_coupling value is 1, the bs_amp_res value for each channel must be the same.
reference: ISO-IEC 14496-3 (2019) - Table 4.119 (4.5.2.8)
ffmpeg code : https://www.ffmpeg.org/doxygen/3.2/aacsbr__template_8c_source.html#l009999 (See copy_sbr_grid() and read_sbr_channel_pair_element() functions)
Issue: https://github.com/MediaArea/MediaInfoLib/issues/1624
> AAC: Add missing code in sbr_channel_pair_element() (#1624)

- Source/MediaInfo/Multiple/File_Mxf.cpp
Fix https://github.com/MediaArea/MediaInfo/issues/661 due to ugly copy/paste typo.
> MXF: fix UKDPP FpaPass value sometimes not outputted

- Source/MediaInfo/Audio/File_Mpega.cpp
Fix https://github.com/MediaArea/MediaInfoLib/issues/1637.
```
Writing library                          : LAMEH5.21
Encoding settings                        : -m  -lowpass 11.7
```
```
Writing library                          : LAMEH5.21
Encoding settings                        : -m  -V 5 -q 0 -lowpass 15.8
```
> MPEG-Audio: proper support of Helix MP3 encoder detection

- Source/MediaInfo/Audio/File_Ac3.cpp
- Source/MediaInfo/Audio/File_Ac4.cpp
- Source/MediaInfo/Audio/File_Dts.cpp
- Source/MediaInfo/Audio/File_Iab.cpp
- Source/MediaInfo/Audio/File_Iab.h
- Source/MediaInfo/Audio/File_Mpega.cpp
- Source/MediaInfo/Audio/File_SmpteSt0331.cpp
- Source/MediaInfo/Multiple/File_Ancillary.cpp
- Source/MediaInfo/Multiple/File_DvDif.cpp
- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Riff_Elements.cpp
- Source/MediaInfo/Multiple/File_Vbi.cpp
- Source/MediaInfo/Video/File_Av1.cpp
- Source/MediaInfo/Video/File_Avc.cpp
- Source/MediaInfo/Video/File_H263.cpp
- Source/MediaInfo/Video/File_Hevc.cpp
- Source/MediaInfo/Video/File_Mpeg4v.cpp
- Source/MediaInfo/Video/File_Mpegv.cpp
- Source/MediaInfo/Video/File_Vc1.cpp
- Source/MediaInfo/Video/File_Vc3.cpp
- Source/MediaInfo/Video/File_Vc3.h
- Source/MediaInfo/Video/File_Vp8.cpp
Reduce the count of bytes read from disk/network when ` --ParseSpeed=0` is used.
Focused on MXF but may also slightly improve the result for other containers as a collateral effect.
> MXF: quicker parsing when fast parsing is requested

- Source/MediaInfo/Multiple/File_Mxf.cpp
Greatly reduce the count of bytes read from disk, should be used only if stream metadata is not useful.
` --ParseSpeed=-0.5`: parse the header and footer (truncated file detection still active as usual).
` --ParseSpeed=-1`: parse the header only (truncated file detection active only if header partition has footer partition offset, and test based on file size only, integrity of footer partition is not tested).
> MXF: option for parsing only the header, no parsing of any frame

- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Greatly reduce the count of bytes read from disk, should be used only if stream metadata is not useful.
--ParseSpeed=-0.5: parse the header and test other root atoms (truncated file detection still active as usual).
--ParseSpeed=-1: parse the header only (truncated file detection active only if header is at the end of the file or if mdat atom end is more than file size).
> MOV/MP4: option for parsing only the header, no parsing of any frame

- Source/MediaInfo/Text/File_Ttml.cpp
- Source/MediaInfo/Text/File_Ttml.h
> Structs with the same name in the same namespace confuses GCC

- Source/MediaInfo/File__Analyze.h
- Source/MediaInfo/File__Analyze_MinimizeSize.h
- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/Video/File_Av1.cpp
Format is not exactly same than MPEG.
Fix https://github.com/MediaArea/MediaInfo/issues/597 and https://github.com/MediaArea/MediaInfo/issues/597#issuecomment-1214169287.
> AV1: add HDR format line and fix HDR values

- Source/MediaInfo/Audio/File_Dts.cpp
- Source/MediaInfo/Audio/File_Dts.h
- Source/MediaInfo/MediaInfo_Internal.cpp
Detection of [DTS IMAX Enhanced](https://www.highdefdigest.com/blog/imax-enhanced-dts-audio-format-debut/) in addition to "old" DTS:X.
Refactoring of DTS:X detection in order to avoid false positive detection.
Detection of real bit depth e.g. 20 instead of only byte aligned bit depth (16 or 24).
Close https://github.com/MediaArea/MediaInfo/issues/422.
> DTS: Detection of IMAX enhanced

- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
and `stpp` CodecID is correctly mapped to TTML.
> MOV/MP4: support of TTML with images

- Source/MediaInfo/MediaInfo_Inform.cpp
- Source/MediaInfo/MediaInfo_Internal.cpp
main element rename, media subelement, more attributes.
Close https://github.com/MediaArea/MediaInfoLib/issues/1663.
>  Extract of time codes, XML format, update

- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Whenever mediainfo encounters an unknown udta user data type it will fallback to parsing the content of the user data as a list of strings using the `File_Mpeg4::moov_udta_xxxx`method. This seems ill advised seeing as the Quicktime reference pages explicitly says to ignore unknown user data types (https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html)
However, assuming that this string fallback is wanted, it should at least not get stuck when interpreting something which is not a string as if it was a string. Further more, even if the user data actually is a list of strings it only parses the first string correctly. 
I first observed the behavior of mediainfo getting stuck on one of our customers files. However I'm not free to distribute this file …
> Mediainfo gets stuck because of bad fallback code for udta mov atoms

- Source/MediaInfo/Tag/File_VorbisCom.cpp
Some FLAC files have a special mapping of `bext` (BWF) chunk to FLAC comment metadata, let's support that.
Note: this is not the support of the parsing of the WAV header in the FLAC reversibility option, WIP for this one.
> FLAC: support of BWF in Vorbis comments

- Source/MediaInfo/Multiple/File_Mpeg4.cpp
Due to stsz Sample Size of 0 (stsz Number of entries must be used instead).
Fix https://github.com/MediaArea/MediaInfoLib/issues/1681.
> MP4/MOV: some timecode values were not displayed

- Source/MediaInfo/Export/Export_Mpeg7.cpp
- Source/MediaInfo/Export/Export_Mpeg7.h
- Source/MediaInfo/MediaInfo_Config.cpp
- Source/MediaInfo/MediaInfo_Inform.cpp
Strict: strict conformance to the MPEG-7 XSD
Relaxed: MediaInfo extension in case of important info missing e.g. more than 1 audio track, text track, encryption
Extended: MediaInfo extension in case of minor info missing e.g. open GOP
> MPEG-7: 3 modes (strict, relaxed, extended)

- Source/MediaInfo/File__Analyze_Streams.cpp
Just removing the try catch, there should be no C++ exception there.
> Normalization of date/time in report, update

- Source/MediaInfo/Tag/File_Id3v2.cpp
0 is actually is valid value, only 255 is not a valid value.
Fix https://github.com/MediaArea/MediaInfo/issues/682.
> ID3v2: fix Genre not showing ID 0 (Blues)

- Source/MediaInfo/Audio/File_Pcm.cpp
- Source/MediaInfo/Audio/File_Pcm.h
Full parsing needs to be selected.
It is in "Conformance information" part because it is a bit out of topic for the top level listing (and not a warning or error because it is something often normal).
```
Conformance information                  : 1
Content                                 : Content is silence
```
> MXF/PCM: detect silent tracks (full parsing only)

- Source/MediaInfo/Audio/File_Pcm.cpp
Update after https://github.com/MediaArea/MediaInfoLib/pull/1713
> MXF/PCM: detect silent tracks (full parsing only), update

- Source/MediaInfo/Audio/File_Ape.cpp
The downlable SDK is only 9.20 and it stipulates that 4 first bytes are `MAC `, this file has `MACF`, looks like it is a 10.0 thing but I have no idea about the difference between the 2 different magic values.
Anyway, if I accept `MACF`, it looks like it does not impact our parsing.
Foud SDK 10.00 beta, `MACF` means floating point.
Fix https://github.com/MediaArea/MediaInfoLib/issues/1716.
> Monkey's Audio: support of 32-bit files

- Source/MediaInfo/Multiple/File_Mk.cpp
- Source/MediaInfo/Multiple/File_Mk.h
Used for [support AVI in RAWcooked](https://github.com/MediaArea/RAWcooked/pull/405).
> Matroska: support of RAWcooked A/V container related elements

- Source/MediaInfo/Audio/File_Usac.cpp
Advanced USAC conformance checks are not fully ready, disabling them for the next public release
> USAC: revert conformance checks

- Source/MediaInfo/Audio/File_Usac.cpp
- Source/MediaInfo/Audio/File_Usac.h
NULL in c++ is not defined to always be 0, it can also be std::nullptr_t.
it is not valid to pass std::nullptr_t to memset, so pass 0 explicitly.
> USAC: fix usage of NULL in memset

- Source/MediaInfo/Reader/Reader_libcurl.cpp
- Source/MediaInfo/Reader/Reader_libcurl.h
- Source/MediaInfo/Reader/Reader_libcurl_Include.h
Retrieval of the S3 geolocated path was failing if `curl-ca-bundle.crt` is not embedded in the used curl library and provided by `--Ssl_CertificateFileName=...` option.
And check also `libcurl-x64.dll` presence on Windows.
> S3: accept external crt file also for non geolocated URLs

- Source/MediaInfo/Multiple/File_Mk.cpp
- Source/MediaInfo/Multiple/File_Mk.h
When in `BlockAddition` with ITU-T T.35 transport layer.
Basically a copy/paste of the HEVC implementation, to-do is a merge of AVC/HEVC/MKV code.
> Matroska: support of HDR10+

- Source/MediaInfo/Audio/File_Ac4.h
* fix C2666	'MediaInfoLib::File_Ac4::drc_decoder_config_curve::operator ==': overloaded functions have similar conversions	MediaInfoLib (MediaInfoLib\MediaInfoLib)
> fix drc_decoder_config_curve

- Source/MediaInfo/Audio/File_Dts.cpp
- Source/MediaInfo/MediaInfo_Internal.cpp
Update of https://github.com/MediaArea/MediaInfoLib/pull/1747 with more precise commercial name e.g. `DTS-HD MA + DTS:X IMAX Enhanced` (so the "Master Audio" is visible).
> DTS: Better handling of extensions parsing, update

- Source/MediaInfo/Audio/File_Dts.cpp
- Source/MediaInfo/MediaInfo_Internal.cpp
Usually it is there when with non Master Audio (non lossless) streams.
Fix https://github.com/MediaArea/MediaInfo/issues/710.
> DTS: detection of DTS:X also when after HD assets

- Source/MediaInfo/Audio/File_Dts.cpp
Fix https://github.com/MediaArea/MediaInfo/issues/717.
Note that it is forking from how FFmpeg flags DTS:X IMAX but at it is reverse engineering for both (I presume), I prefer to rely on the report from the ticket.
Edit: not sure
> DTS:X: Fix some streams are DTS:X not IMAX

- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Mxf.h
This patch adds support for recognizing AAC wrapped in MXF files following the ST 381-4:2017 standard.  This format is used by Harmonic's Spectrum product line to generate proxies during record.  There are a few other vendors in the broadcast industry that also generate files following this standard, but I don't have an exhaustive list.  For a sample file, see [https://harmonicinc.box.com/v/st381-4-sample]().  I don't have sample files to cover all potential variants.
Note that ST 381-4 also includes details about an AacSubDescriptor, but there doesn't seem to be any (immediate) value in parsing it.  I'd be happy to add it, if necessary.
> Support ST381-4

- Source/MediaInfo/Video/File_Hevc.cpp
Follow up of https://github.com/MediaArea/MediaInfoLib/pull/1757, thank to reminder from https://github.com/MediaArea/MediaInfoLib/commit/22efc689fbe536148cdd1e00d4ccba785695efde#commitcomment-112002219.
Need to have a refactoring of that at some point...
> HEVC: fix crash in support of HDR10+

- Source/MediaInfo/Audio/File_Dts.cpp
- Source/MediaInfo/Audio/File_Dts.h
Fix https://github.com/MediaArea/MediaInfoLib/issues/1769.
> DTS: keep extensions detection if if full parsing fails

- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/Resource/Text/DataBase/CodecID_Audio_Mpeg4.csv
Includes `chnl` and `pcmC` atom support.
Fix https://github.com/MediaArea/MediaInfoLib/issues/1781.
> MP4: support of ipcm CodecID

- Source/MediaInfo/File__Analyze_Streams_Finish.cpp
Update of https://github.com/MediaArea/MediaInfoLib/pull/1783 due to a stupid typo.
> New field Audio_Channels_Total, update

- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Mxf.h
- Source/MediaInfo/Text/File_Ttml.cpp
- Source/MediaInfo/TimeCode.cpp
In MXF SystemScheme (no tip, so using video or audio tracks framerate) and SDTI (`CPR_1_1001`).
In default TTML.
Also avoid a TTML timestamp rounding issue with duration from timecode of end and begin.
> TimeCode: 1/1.001 frame rate was not always detected

- Source/MediaInfo/Text/File_Ttml.cpp
"[if no application defined frame rate applies, then thirty (30) frames per second](https://www.w3.org/TR/2018/REC-ttml2-20181108/#parameter-attribute-frameRate)".
> TTML: fix default frame rate

- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Fix https://github.com/MediaArea/MediaInfoLib/issues/1804.
> MOV/MP4: avoid incoherent behavior if 2 tracks have the same ID

- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
More information about the GoPro track in https://github.com/MediaArea/MediaInfoLib/issues/1804, even if the content is still not parsed.
Also include a conformance error with track_ID being same in 2 tracks.
> MOV/MP4: more info with tracks having unknown type

- Source/MediaInfo/Audio/File_Dts.cpp
- Source/MediaInfo/Audio/File_Dts.h
Provides sample count so duration, as well as time code
Parser is in a separate class because [it will be used by another parser](https://github.com/MediaArea/MediaInfoLib/pull/1814).
> DTS-HD: DTSHDHDR header support

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Solves #1807
While reading some Blackmagic RAW files I noticed that a handful of the fields weren't being read properly.
With a little debugging I produced the table below, and continued to implement.
| Kind | Name | Data | Length |
|--------|--------|--------|--------|
| 76 | post_3dlut_embedded_size | 33 | 2 |
| 77 | braw_codec_bitrate | 17798144 | 4 |
| 71 | crop_origin | 16,8, | 8 |
| 71 | crop_size | 2868,1512, | 8 |
| 76 | anamorphic_enable | 0 |  2 |
| 76 | tone_curve_video_black_level | 0 | 2 |
| 76 | viewing_bmdgen | 4 | 2 |
> Blackmagic RAW: Read more kinds of metadata.

- Source/MediaInfo/Audio/File_Aac.cpp
- Source/MediaInfo/Audio/File_Aac_GeneralAudio.cpp
Mistake is global but impact is visible only with MEDIAINFO_MINIMIZESIZE
> ADIF: fix wrong detection of lot of files as ADIF

- Source/MediaInfo/Audio/File_Iab.cpp
- Source/MediaInfo/Audio/File_Usac.cpp
- Source/MediaInfo/Audio/File_Usac.h
- Source/MediaInfo/Export/Export_EbuCore.cpp
- Source/MediaInfo/MediaInfo_Config.cpp
- Source/MediaInfo/MediaInfo_Config.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Multiple/File_Mpeg_Psi.cpp
- Source/MediaInfo/Reader/Reader_libcurl.cpp
- Source/MediaInfo/Reader/Reader_libcurl.h
- Source/MediaInfo/Text/File_SubRip.cpp
- pass strings by reference where it is obviously reasonable
- fix few trivial-to-fix clang warnings
- fix few reasonable and easy-to-fix clang-tidy warnings
- prefer prefix increment for iterators
> minor improvements

- Project/BCB/Library/MediaInfoLib.cbproj
- Project/CMake/CMakeLists.txt
- Project/CodeBlocks/Library/MediaInfoLib.cbp
- Project/GNU/Library/Makefile.am
- Project/GNU/Library/configure.ac
- Project/GNU/Library/test/Makefile.am
- Project/MSVC2013/Library/MediaInfoLib.vcxproj
- Project/MSVC2013/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2015/Library/MediaInfoLib.vcxproj
- Project/MSVC2015/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2017/Library/MediaInfoLib.vcxproj
- Project/MSVC2017/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2017/Library/MediaInfoLib_UWP.vcxproj
- Project/MSVC2019/Library/MediaInfoLib.vcxproj
- Project/MSVC2019/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2019/Library/MediaInfoLib_UWP.vcxproj
- Project/MSVC2022/Library/MediaInfoLib.vcxproj
- Project/MSVC2022/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2022/Library/MediaInfoLib_UWP.vcxproj
- Project/Qt/MediaInfoLib.pro
- Source/MediaInfo/Audio/File_DtsUhd.cpp
- Source/MediaInfo/Audio/File_DtsUhd.h
- Source/MediaInfo/File__MultipleParsing.cpp
- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/MediaInfo/MediaInfo_File.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Setup.h
- Source/Resource/Text/DataBase/Format.csv
- Source/Resource/Text/Language/DefaultLanguage.csv
Created a new file parser File_DtsUhd to parse DTS:X P2 input files.  Functions specific to DTSUHD parsing used by File_MPeg4_Elements.cpp are moved into File_DtsUhd.cpp, similar to how File_Dts.cpp is arranged.  This pull request implements parsing of DTS-UHD frames to provide audio information.  The frame field display provided by "--Display=1" is not implemented at this time.  I would first like to confirm the code in this pull request is OK, sort out any changes necessary, and that the "--Display=1" functionality is needed.
> DTS-UHD: Adding parsing of .dtsx files.

- Source/MediaInfo/Video/File_Mpegv.cpp
(interlaced content only)
Fix https://sourceforge.net/p/mediainfo/bugs/1187/
> MPEG Video: fix duration not including last field duration

- Source/MediaInfo/Multiple/File_Riff.cpp
- Source/MediaInfo/Multiple/File_Riff_Elements.cpp
@MarcosSueiro
```
General
Format                                   : Wave
Format settings                          : PcmWaveformat
File size                                : 81.8 MiB
Duration                                 : 16 min 8 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 709 kb/s
Audio #1
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 5 min 48 s
Bit rate mode                            : Constant
Bit rate                                 : 705.6 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 44.1 kHz
Bit depth …
```
> WAV: better display of buggy WAV files have 2 fmt/data chunks

- Source/MediaInfo/Export/Export_Mpeg7.cpp
- Source/MediaInfo/Multiple/File_Dvdv.cpp
Fix stream IDs (add MPEG-PS `stream_id` prefix) for IFO without VOB or with streams not found in VOB quick parsing (mainly text streams).
Fix MPEG-7 duration field in collections, using the duration from menu track rather than the video track (which contains duration of all titles, but we need the duration of a title)
Fix 0 duration for IFO menus (should be empty rather than 0)
> MPEG-7: tweaking of the output for DVD Video in ISO, update

- Source/MediaInfo/Multiple/File_Mpeg4.cpp
Fix https://github.com/MediaArea/MediaInfoLib/issues/1867.
> MOV/MP4: caption probing time expanded from ~15s to ~30s

- Source/MediaInfo/Audio/File_DtsUhd.cpp
- Source/MediaInfo/Audio/File_DtsUhd.h
This pull request adds the T1CC flag to DTS-UHD in the commercial name only.
> DTS-UHD: Report t1cc flag in commercial name

- Source/MediaInfo/Multiple/File_Riff_Elements.cpp
Fix https://github.com/MediaArea/MediaInfoLib/issues/1876
> BWF: fix missing precision in TimeReference export

- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_TimeCode.h
In case of multiple stripped timecodes.
Fix https://github.com/MediaArea/MediaInfoLib/issues/1878.
Also show discontinuities for complex stripped timecodes also without full parsing, as it does not hurt much performance if it is only a couple of timecode samples.
> MP4/MOV: show right time code of last frame with complex time code tracks

- Source/MediaInfo/Audio/File_Adm.cpp
- Source/MediaInfo/Audio/File_Adm.h
- Source/MediaInfo/Multiple/File_Riff.cpp
- Source/MediaInfo/Multiple/File_Riff.h
- Source/MediaInfo/Multiple/File_Riff_Elements.cpp
- Source/ThirdParty/tfsxml/tfsxml.c
- Source/ThirdParty/tfsxml/tfsxml.h
Some ADM content are really big and loading the complete XML file in RAM was too much for 32-bit systems (but also too much RAM consuming on low memory 64-bit systems)
> WAV: support of big (1+ GB) axml chunks

- Source/MediaInfo/File__Analyze_Streams_Finish.cpp
Only for default display (advance view still shows 2 decimals and sample offset).
Change is made in order to match (future) Dolby tools.
> ADM: rounding of FFoA to 0 decimal and Start/End time codes to 2 decimals

- Source/MediaInfo/Multiple/File_Mk.cpp
Fix https://github.com/MediaArea/MediaInfoLib/issues/1892.
> Matroska: fix date readout if before the millennium

- Source/MediaInfo/Multiple/File_Gxf_TimeCode.cpp
- Source/MediaInfo/Multiple/File_Gxf_TimeCode.h
- Source/MediaInfo/Multiple/File_Mk.cpp
Parsing (so MediaTrace) is already there, so just showing a timecode track
```
Other
ID                                       : 1-Add-121
Muxing mode                              : BlockAddition
Time code of first frame                 : 00:00:00:00
```
ID need some review about how to manage block addition IDs.
Time code is not yet checked about discontinuities.
> Matroska: show ST-12 timecode of first frame

- Source/MediaInfoDLL/MediaInfoDLL.h
Not convinced that it changes something but it is more explicit and does not hurt.
Fix https://github.com/MediaArea/MediaInfoLib/issues/1904.
> MediaInfoDLL dynamic load: explicit nullptr

- Source/MediaInfo/File__Analyze_Streams.cpp
Small typo in https://github.com/MediaArea/MediaInfoLib/pull/1905 and the opposite of was what wanted was implemented :(.
> Duration: timecode output does not use drop frame for 23.976fps, fix

- Source/MediaInfo/File__Analyze_Streams.cpp
804 is not a multiple of 8 so 800 is often preferred but source content us a bit cut, we want to do the difference between the full source content at 2.39:1 and some missing lines at 2.40:1.
https://en.wikipedia.org/wiki/Aspect_ratio_(image)#Previous_and_currently_used_aspect_ratios
> 2.4:1 = 12:5
> Rounded notation of 2.39:1, also as 2.40:1. [Blu-ray Disc](https://en.wikipedia.org/wiki/Blu-ray_Disc) film releases may use only         800 instead of 803 or 804 lines of the 1920×1080 resolution, resulting in an even 2.4:1 aspect ratio."
> DAR: do the difference between 2.40 (1920x800) and 2.39 (1920x804)

- Source/MediaInfo/File__Analyze.h
- Source/MediaInfo/File__Analyze_MinimizeSize.h
- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/Image/File_Png.cpp
Update of https://github.com/MediaArea/MediaInfoLib/pull/1924
CLLI in PNG is not like others (0.0001 step)
> PNG: support of color description chunks (CCIP CLLI MDCV), update

- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
General fix + specifically skip `PANA` atom (todo: parse it... As well as the XML atom)
Fix https://github.com/MediaArea/MediaInfoLib/issues/1940
> I1940, MOV/MP4: fix slowness with some unrecognized metadata atoms

- Source/ThirdParty/tfsxml/tfsxml.c
get_level() expects an int pointer.
> tfsxml: fix sign integer type

- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Video/File_Hevc.cpp
- Source/MediaInfo/Video/File_Hevc.h
- Source/Resource/Text/Language/DefaultLanguage.csv
`vps_extension` is not fully parsed so bitstream integrity is not checked but we have the real profile in the case it is present.
> HEVC: support of multiview profile signaled in VPS extension

- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Mxf.h
And yet another timecode...
(+ camera settings)
Close https://github.com/MediaArea/MediaInfo/issues/624.
```
Other
ID                                       : 3
Type                                     : meta
Format                                   : Sony Real Time Metadata
Codec ID                                 : rtmd
Duration                                 : 19 s 200 ms
Bit rate mode                            : Constant
Time code of first frame                 : 03:47:26;44
Encoded date                             : 2022-06-10 08:16:01 UTC
Tagged date                              : 2022-06-10 08:16:01 UTC
TransferCharacteristics_FirstFrame       : xvYCC
ColorPrimaries_FirstFrame                : BT.709
MatrixCoefficients_FirstFrame            : BT.709
IrisFNumber_FirstFrame …
```
> MOV/MP4: parsing of rtmd (real time metadata) tracks

- Source/MediaInfo/File__MultipleParsing.cpp
We still don't support referencing other files inside an ISO, but at least there are some info from a single file
fix https://github.com/MediaArea/MediaInfoLib/issues/1964#issuecomment-1962325965
> By buffer API: accept blu-ray files

- Source/MediaInfo/Audio/File_Adm.cpp
Especially about Speaker common definitions.
> ADM: conformance checker update

- Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.h
- Source/MediaInfo/Text/File_Eia608.cpp
- Source/MediaInfo/Text/File_Eia708.cpp
Close https://github.com/MediaArea/MediaInfoLib/issues/1882 (CLI only, GUI will command with other options).
```
mediainfo UXKV-A_01_D01.scc.txt "--Inform=Text;%ID%,"
CC1,T1,
mediainfo UXKV-A_01_D01.scc.txt "--Inform=Text;%ID%,"  --File_CommandOnlyMeansEmpty=1
CC1,
```
> CEA-608/708: options for ignoring command only streams

- Source/MediaInfo/Audio/File_Wvpk.cpp
- Source/MediaInfo/Audio/File_Wvpk.h
Fix https://github.com/MediaArea/MediaInfoLib/issues/2008.
> Wavpack: support of DSD

- Source/MediaInfo/File__Analyze.cpp
Fix of emscripten build after https://github.com/MediaArea/MediaInfoLib/pull/2019
> AVC & HEVC & AAC: report of malformed frames, update

- Source/MediaInfo/Audio/File_Ac3.cpp
- Source/MediaInfo/Audio/File_Ac4.cpp
- Source/MediaInfo/Audio/File_DolbyE.cpp
- Source/MediaInfo/Audio/File_Dts.cpp
- Source/MediaInfo/Audio/File_DtsUhd.cpp
- Source/MediaInfo/Audio/File_SmpteSt0337.cpp
- Source/MediaInfo/Audio/File_Wvpk.cpp
- Source/MediaInfo/File__Analyze.cpp
- Source/MediaInfo/File__MultipleParsing.cpp
- Source/MediaInfo/File__MultipleParsing.h
- Source/MediaInfo/Image/File_Tga.cpp
- Source/MediaInfo/Image/File_Tga.h
- Source/MediaInfo/Multiple/File_DvDif.cpp
- Source/MediaInfo/Multiple/File_Gxf.cpp
- Source/MediaInfo/Multiple/File_MpegPs.cpp
- Source/MediaInfo/Multiple/File_MpegTs.cpp
- Source/MediaInfo/Multiple/File_Ogg.cpp
- Source/MediaInfo/Video/File_Avc.cpp
- Source/MediaInfo/Video/File_AvsV.cpp
- Source/MediaInfo/Video/File_Dirac.cpp
- Source/MediaInfo/Video/File_H263.cpp
- Source/MediaInfo/Video/File_Hevc.cpp
- Source/MediaInfo/Video/File_Mpeg4v.cpp
- Source/MediaInfo/Video/File_Mpegv.cpp
- Source/MediaInfo/Video/File_Vc1.cpp
Also avoid some false positive detection as H.263 and tweak amount of bytes read with distant files.
Fix https://github.com/MediaArea/MediaInfoLib/issues/2015
> Avoid infinite loop with distant files

- Source/MediaInfo/File__Analyze.cpp
- Source/MediaInfo/Video/File_Ffv1.cpp
- Source/MediaInfo/Video/File_Ffv1.h
Activate conformance report in MediaInfo report, which permits at the same time to display FFV1 conformance error in MediaInfo directly instead of relying on MediaConch and to add support of FFV1 conformance checks on containers other than MKV.
> FFV1 conformance checks also when in AVI and MOV/MP4

- Source/MediaInfo/Image/File_Jpeg.cpp
- Source/MediaInfo/Image/File_Jpeg.h
- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Mxf.h
I2 mode is interlaced but with FrameLayout FULL_FRAME, despite what is for interlaced content for all other formats.
All the I2 files I received up to https://github.com/MediaArea/MediaInfoLib/issues/2037 violates this part of the spec but well, we need to at least support correctly when theoretically a file is conforming to specs.
In order to not break the support of I2 files in the wild, both FrameLayout FULL_FRAME and FrameLayout SEPARATE_FIELDS are supported and there is a probe in the JP2k frame in case of former UL with essence container label Content Kind of 0.
Mainly fix https://github.com/MediaArea/MediaInfoLib/issues/2037 but also fix some incoherent issues about frame rate with other files.
> MXF: Support of SMPTE ST 422-2019 I2

- Source/MediaInfo/Tag/File_Id3v2.cpp
- Source/MediaInfo/Tag/File_Id3v2.h
Also correctly handle ID3v2.4 unsynchronization.
fix https://github.com/MediaArea/MediaInfoLib/issues/2054.
> ID3v2: fix crash with some malformed files

- Source/MediaInfo/Tag/File_VorbisCom.cpp
Fix https://github.com/MediaArea/MediaInfoLib/issues/2058.
> VorbisCom: show MusicBrainz IDs in XML or full text output

- Source/MediaInfo/Audio/File_Wvpk.cpp
- Source/MediaInfo/Audio/File_Wvpk.h
- fix parsing of multichannel files with greater than 8 streams
- fix compression ratio calculation for all multichannel files
- fix DSD file parsing
> WavPack: various fixes for multichannel & DSD files

- Source/MediaInfo/Multiple/File_Mpeg4.cpp
Fix potential crash after https://github.com/MediaArea/MediaInfoLib/pull/2051.
> Conformance checker: an element is indicated bigger than its upper element, fix

- Source/MediaInfo/MediaInfo_Inform.cpp
Improve and modernize the HTML that is generated. Tested on Firefox (including Responsive Design Mode), Edge, VCL GUI (with IE and WebView2 engine) and Qt GUI. The display is considered consistent across all with the exception that the Qt GUI displays borders differently.
`width="100%"` and `width="150"` should be removed but is kept there to maintain compatibility with Qt GUI and possibly older browser engines.
**HTML Validator now:**
```
"file:/D:/%5BTHD%20DDP%20Atmos%5D%20Dolby%20Atmos%20Amaze.m2ts.MediaInfo%20(2).html":9.1-9.119: error: The ÔÇ£widthÔÇØ attribute on the ÔÇ£tableÔÇØ element is obsolete. Use CSS instead.
"file:/D:/%5BTHD%20DDP%20Atmos%5D%20Dolby%20Atmos%20Amaze.m2ts.MediaInfo%20(2).html":10.7-11.76: error: The ÔÇ£widthÔÇØ attribute on the ÔÇ£tdÔÇØ element is obsolete. …
```
> HTML Improvements

- Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.h
- Source/MediaInfo/Text/File_Cdp.cpp
- Source/MediaInfo/Text/File_DtvccTransport.cpp
- Source/MediaInfo/Text/File_Eia608.cpp
- Source/MediaInfo/Text/File_Eia608.h
- Source/MediaInfo/Text/File_Eia708.cpp
- Source/MediaInfo/Text/File_Eia708.h
- Source/MediaInfo/Text/File_Scte20.cpp
Common option for https://github.com/MediaArea/MediaInfo/issues/674 and https://github.com/MediaArea/MediaInfoLib/issues/1882, now `File_DisplayCaptions` with `Content`, `Command`, `Stream`.
> CEA-608/708: option for forcing all CC1-CC4/T1 if stream is detected

- Source/MediaInfo/MediaInfo_Inform.cpp
More HTML improvements:
- Enable native dark mode
- There is now dark mode for the exported HTML on all modern browsers
- Will work in MediaInfo GUI too with newer browser engine implemented
- Move all styles from inline to <style> tag
- Remove colspans that appear to do nothing and cause validator errors
- Standardize indents
HTML validator results:
There is only one warning for language.
Tested for proper display and dark mode switching on Edge, Firefox and MediaInfo VCL GUI.
This change makes MediaInfo Qt GUI display differently since it is currently not using a web engine for the HTML view. This should be fixable on Qt GUI side if necessary.
> HTML Improvements 2

- Source/MediaInfo/Video/File_Hevc.cpp
- Source/MediaInfo/Video/File_Hevc.h
I have a few multiview samples generated by either iPhone or Apple's authoring tools, and for all of them i get the following:
```
Conformance errors                       : 1
HEVC                                    : Yes
General compliance                     : Bitstream parsing ran out of data to read before the end of the syntax was reached, most probably the bitstream is malformed  (offset 0xDEADBEEF)
Codec configuration box                  : hvcC+lhvC
```
In both cases, the offset reported is the start of whatever box follows the lhvC one, so it was clear there were LHEVCDecoderConfigurationRecord parsing related issues.
Looking into it i found one problem parsing SPS when nuh_layer_id > 0 and one when MultiLayerExtSpsFlag is true (nuh_layer_id > 0 && …
> HEVC: add missing parsing of some multilayer SPS elements

- Source/MediaInfo/OutputHelpers.cpp
- Source/MediaInfo/OutputHelpers.h
Fix https://github.com/MediaArea/MediaInfoLib/issues/2097
> XML export: fix comment in comment

- Source/MediaInfo/MediaInfo_Inform.cpp
Escape HTML strings to ensure they display exactly what is in the file and not trigger unwanted results.
Fixes #1975 
Test file:
https://github.com/user-attachments/assets/fcebf2f9-532c-4a25-b810-5a389f55d44b
Before:
After:
> Escape HTML strings

- Source/MediaInfo/Audio/File_Aac_Main.cpp
As mentioned in https://github.com/MediaArea/MediaInfoLib/issues/2105#issuecomment-2381399096, this is one of the issues found with Visual Studio Code Analysis and also Cppcheck.
Visual Studio:
Cppcheck:
```
Id: arrayIndexOutOfBoundsCond
CWE: 788
Either the condition 'OutputChannels[i]>Aac_OutputChannelPosition_Size' is redundant or the array 'Aac_ChannelMode[43]' is accessed at index 43, which is out of bounds.
```
https://github.com/MediaArea/MediaInfoLib/blob/00d96580cfaff7f189af13d6ec6cf8f7d8b3a72d/Source/MediaInfo/Audio/File_Aac_Main.cpp#L498-L501
The issue is that `Aac_OutputChannelPosition_Size` is 43 and `Aac_ChannelMode` has 43 elements. Since an array starts with `0`, the max we can access in `Aac_ChannelMode` is 42. So we change `>Aac_OutputChannelPosition_Size` to …
> Fix out-of-bounds array read in File_Aac_Main

- Source/MediaInfo/Audio/File_Iab.cpp
As mentioned at the end of https://github.com/MediaArea/MediaInfoLib/issues/2105#issuecomment-2381399096, Cppcheck found an array access that is out of bounds:
```
Id: arrayIndexOutOfBoundsCond
CWE: 788
Either the condition 'Code>=0x80' is redundant or the array 'Iab_Channel_Values[34]' is accessed at index 104, which is out of bounds.
```
https://github.com/MediaArea/MediaInfoLib/blob/dbed0279c05911f50f9ad715d187666e38f8764c/Source/MediaInfo/Audio/File_Iab.cpp#L117-L118
Upon further inspection and looking at the IAB specs, I concluded that there is indeed a bug.
Since I do not have an IAB test file to test, I wrote a test based on pages 31 and 32 of https://pub.smpte.org/doc/st2098-2/20220525-pub/st2098-2-2022.pdf to test it and confirmed that this PR is needed. The fixed version is also …
> Fix bug in IAB channel code mapping

- Source/MediaInfo/MediaInfo_Config_MediaInfo.cpp
- Source/MediaInfo/MediaInfo_Config_MediaInfo.h
- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Multiple/File_Mxf.h
- Source/MediaInfo/Multiple/File__ReferenceFilesHelper.cpp
Fix https://github.com/MediaArea/MediaInfoLib/issues/2110
> MXF: fix wrong Delay field with NDF timecodes

- Source/MediaInfo/Multiple/File_Mxf.cpp
- Source/MediaInfo/Video/File_Avc.cpp
- Source/MediaInfo/Video/File_Avc.h
Detection of AVC-Intra was already present in theory but was working only on MXF Clip wrapped content in practice.
Close https://github.com/MediaArea/MediaInfoLib/issues/2124.
> AVC: improved detection of AVC-Intra

- Source/MediaInfo/Multiple/File_MpegTs.cpp
It reads more content from the disk but this is the only way to get the real end time of each stream. A smarter way could be to keep the previous behavior but seek earlier if not all found, on the todo-list
> MPEG-TS: increase probing at end of FileHeader_Begin

- Source/MediaInfo/Audio/File_Mga.cpp
- Source/MediaInfo/Audio/File_SmpteSt0337.cpp
- Source/MediaInfo/Image/File_Png.cpp
- Source/MediaInfo/Multiple/File_Riff_Elements.cpp
Solves recently opened issue at #2120
> Removed buffer leak in PNG file parsing and when using inflate

- Source/MediaInfo/Image/File_Exr.cpp
- Source/MediaInfo/Image/File_Exr.h
Close https://github.com/MediaArea/MediaInfoLib/issues/2130.
> EXR: support of time code and frame rate

- Source/MediaInfo/Multiple/File_DvDif_Analysis.cpp
> DvDif: Avoid to call Synchro_Manage() twice

- Source/MediaInfo/Audio/File_Aac_GeneralAudio.cpp
Currently, if HEAAC v2 is detected, the number of channels is updated to 2, the `ChannelPositions` are updated to `Front: L R` but the `ChannelLayout` is not updated to 'L R' but shows the previously set layout of 'M'. 
Before Fix:
```
Audio
Format                                   : AAC LC SBR PS
Format/Info                              : Advanced Audio Codec Low Complexity with Spectral Band Replication and Parametric Stereo
Commercial name                          : HE-AACv2
Format version                           : Version 4
Format settings                          : Implicit
Codec ID                                 : 2
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : M
Sampling rate …
```
> Also set ChannelLayout to Stereo when HEAAC v2 is detected

- Source/MediaInfo/Video/File_Ffv1.cpp
Fix https://github.com/MediaArea/MediaConch_SourceCode/issues/790.
> FFV1: MaxSliceCount not in XML report

- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/Resource/Text/DataBase/CodecID_Video_Matroska.csv
This will detect VVC Matroska video tag official from Matroska format.
You can have look a commit of matroska-specification, that VVC defines Matroska video tag:
https://github.com/ietf-wg-cellar/matroska-specification/commit/c9fbd31e94156eaed04c91a000a1562d5aa792b3
But, official matroska page doesn't have VVC information of codec mapping written on it.
Also I'm leaving examples here, if you need it just in case.
[matroska-vvcsamples.zip](https://github.com/user-attachments/files/17926351/matroska-vvcsamples.zip)
If you have question, feedback or issue, feel free to let me know. Thanks! :)
Regards,
Martin Eesmaa
> Matroska tag: Detection for VVC

- Source/MediaInfo/Video/File_Avc.cpp
- Source/MediaInfo/Video/File_Avc.h
- Source/MediaInfo/Video/File_Hevc.cpp
- Source/MediaInfo/Video/File_Hevc.h
Specs: "When aspect_ratio_idc is equal to 0 or sar_width is equal to 0 or sar_height is equal to 0, the sample aspect ratio is unspecified in this Specification".
> AVC&HEVC: PAR is unspecified if not indicated

- Project/MSVC2022/Dll/MediaInfoDll.vcxproj
- Project/MSVC2022/Library/MediaInfoLib.vcxproj
- Project/MSVC2022/ShellExtension/MediaInfoShellExt.vcxproj
Since we have enabled all security mitigations that we know for x86/x64 (except Spectre), let's enable all for ARM64 as well.
Depends on:
> ARM64: Enable Signed Returns / Pointer Authentication

- Source/ThirdParty/aes-gladman/aes_ni.c
`_M_AMD64` is defined in ARM64EC mode causing `USE_INTEL_AES_IF_PRESENT` to be defined and the Intel AES intrinsics do actually work via `softintrin`. However, `#pragma intrinsic(__cpuid)` causes [Compiler Warning C4163](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4163?view=msvc-170) since it is not actually an intrinsic in ARM64EC mode. This PR adds a guard that excludes this line in ARM64EC mode.
> ARM64EC: Resolve Compiler Warning C4163

- Source/MediaInfo/MediaInfo_Inform.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.cpp
Metadata tag used by Android phones to store location coordinates for videos recorded by camera.
Before:
```
xyz                                      : +01.5515+110.3584/
```
After:
```
Location                                 : +01.5515, +110.3584
```
MediaTrace:
```
19268D0   Text - Location (30 bytes)
19268D0    Header (8 bytes)
19268D0     Size:                               30 (0x0000001E)
19268D4     Name:                               ©xyz
19268D8    Size:                                18 (0x0012)
19268DA    Language:                            5575 (0x15C7) - eng
19268DC    Value:                               +01.5515+110.3584/
```
Not sure if it is better to format the coordinates for Text/HTML display so that it is easier/nicer to read and can be copy pasted directly to other …
> MP4: Handle `©xyz` location metadata

- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/Resource/Text/Language/DefaultLanguage.csv
- Extract Samsung Model Number metadata from `udta->smta->mdln` atom
- Show writing library metadata from container in output
- Handle `com.android.version` metadata
Issue #2175
MediaTrace:
```
96BED65   Text - Performer (31 bytes)
96BED65    Header (8 bytes)
96BED65     Size:                               31 (0x0000001F)
96BED69     Name:                               auth
96BED6D    Version:                             0 (0x00)
96BED6E    Flags:                               0 (0x000000)
96BED71    Language:                            5575 (0x15C7) - eng
96BED73    Value:                               Galaxy S23 Ultra
96BED84   Samsung Metadata (42 bytes)
96BED84    Header (8 bytes)
96BED84     Size:                               42 (0x0000002A)
96BED88     Name: …
```
> MP4: Handle more metadata

- .github/workflows/MediaInfoLib_Checks.yml
Remove non "normal" builds except for 1 platform.
Separate LLVM builds from GCC workflow (more parallel).
Make all warnings into errors also for GCC and LLVM.
> Update GitHub Actions

- Source/MediaInfo/Text/File_Pac.cpp
Also improve the count of max characters per line (Handling of non printable characters, italic markers, mix of 7-bit characters and 16-bit characters)
Fix https://github.com/MediaArea/MediaInfoLib/issues/2191.
> PAC: fix crash with some W16 blocs

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
QuickTime says without version/flag, MP4 says with version flag, and some MP4 files are without version/flag, so checking if the version/flag is present or not.
Before this patch only moov meta atoms without version/flag were supported.
Fix https://github.com/MediaArea/MediaInfoLib/issues/2199.
> MP4: fix moov meta support

- Source/MediaInfo/Audio/File_DolbyE.cpp
- Source/MediaInfo/Multiple/File_MiXml.cpp
This also closes #578 
Note that `File_MiXml.cpp` has inconsistent line endings:
> Fix UTF-8 micro symbol in string

- Source/MediaInfo/Audio/File_Ac3.cpp
According to the AC3 specification, the size of mixlevel and mixlevel2 is always five bits, not eight. Parsing it as eight bits will show invalid data, because it will end up including the values of roomtype and the copyright bit. Similarly, the following fields will also not show their real values, but whatever value is written three bits ahead.
> AC3: Fix wrong size of mixlevel

- Project/GNU/Library/configure.ac
Necessary for cross-compilation to work, where pkg-config will be set to ${CHOST}-pkg-config.
> configure.ac: Use proper $PKG_CONFIG variable.

- Source/MediaInfo/MediaInfo_Inform.cpp
Does not compile anymore on old CentOS 7 / SLE 12 but we actually don't need it as it is used only with non Unicode builds and we use non Unicode builds only for JavaScript and 1 sponsor who does not use theses operating systems.
> Fix codecvt include

- Source/MediaInfo/TimeCode.cpp
The current 16 bit definition of MJD in DVB systems 'rolls over' from 0xFFFF to 0x0000 on 23 April 2038.
> 
> **Explanation of proposed fix**
> This proposal is in effect the same as a receiver seeing a 16bit MJD of zero, and deciding it can’t possibly be 1858 or 1859, deciding the 16bit MJD must have rolled over, therefore it is likely 2038 or 2039.
> The most significant bit of the least significant 16bits of the MJD has been 1 since 5 August 1948. It seems unlikely anyone has signalled that date or earlier in a DVB system, since the first version of EN300 468 was published in 1995.
> This proposal is to change the receiver behaviour based on the most significant bit of the signalled 16bit MJD, this should require no change to headend equipment, provided they continue to set the 16bit …
> update to MJD processing to support 16 bit rollover in 2038 - accepted solution for the next version of ETSI EN 300 468

- Project/CMake/CMakeLists.txt
In order to have CMake 4.0 working without option
Fix https://github.com/MediaArea/MediaInfoLib/issues/2242.
> Bump CMake min version to 3.5

- Project/CMake/CMakeLists.txt
- Project/GNU/Library/Makefile.am
- Project/Qt/MediaInfoLib.pro
Resolves: https://github.com/MediaArea/MediaInfo/issues/1068
More details in the above issue.
> Fix non-MSVC builds with AES NI enabled

- Source/MediaInfo/Audio/File_Flac.cpp
Fix https://github.com/MediaArea/MediaInfoLib/issues/2248
> FLAC: fix format name in case of image in metadata

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Map `com.apple.quicktime.location.ISO6709` to `General_Recorded_Location`.
Seems to be used by newer iPhones that appear to no longer use `loci` atom.
Before:
```
Recorded date                            : 2024-01-08T15:06:17-0800
Encoded date                             : 2024-01-08 23:06:17 UTC
Tagged date                              : 2024-01-08 23:07:18 UTC
Writing library                          : Apple QuickTime
Writing operating system                 : Apple iOS 17.2.1
Writing hardware                         : Apple iPhone 15 Pro Max
com.apple.quicktime.location.accuracy.ho : 21.307141
com.apple.quicktime.spatial.format-versi : 1.0
com.apple.quicktime.spatial.aggressors-s : 0
com.apple.quicktime.location.ISO6709     : +36.1318-115.1517+621.989/
```
After:
```
Recorded date …
```
> MP4: Map `com.apple.quicktime.location.ISO6709`

- Source/MediaInfo/Multiple/File_Mpeg4.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Infinite loop is due to a wrong parsing of a box, so we fix 2 issues:
- avoid nearly infinite loops with buggy streams (so we avoid the freeze whatever are the streams)
- support of UUID box names (so we don't show any parsing error with the file in the ticket)
Fix 2249.
> MPEG-4: avoid nearly infinite loops

- Source/MediaInfo/Reader/Reader_libcurl.cpp
Fixes https://github.com/MediaArea/MediaInfoLib/issues/2233
Hope nothing gets broken by this.
Test:
```
General
Complete name                            : http://[2400:8901::f03c:94ff:fed0:3fee]:80/images-nc/knob_green.png
Format                                   : PNG
Format/Info                              : Portable Network Graphic
File size                                : 9.52 KiB
Image
Format                                   : PNG
Format/Info                              : Portable Network Graphic
Compression                              : Deflate
Format settings                          : Indexed-8
Width                                    : 299 pixels
Height                                   : 299 pixels
Display aspect ratio                     : 1.000
Color space …
```
> Curl: Fix parsing Literal IPv6 Addresses in URLs

- Source/MediaInfo/File__Analyze.cpp
When there is not enough buffer during any header parsing.
fix https://github.com/MediaArea/MediaInfoLib/pull/2252#issuecomment-2804616747.
> Fix false positive conformance error

- Project/BCB/Library/MediaInfoLib.cbproj
- Project/CMake/CMakeLists.txt
- Project/CodeBlocks/Library/MediaInfoLib.cbp
- Project/GNU/Library/Makefile.am
- Project/GNU/Library/configure.ac
- Project/MSVC2015/Library/MediaInfoLib.vcxproj
- Project/MSVC2015/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2017/Library/MediaInfoLib.vcxproj
- Project/MSVC2017/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2017/Library/MediaInfoLib_UWP.vcxproj
- Project/MSVC2019/Library/MediaInfoLib.vcxproj
- Project/MSVC2019/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2019/Library/MediaInfoLib_UWP.vcxproj
- Project/MSVC2022/Library/MediaInfoLib.vcxproj
- Project/MSVC2022/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2022/Library/MediaInfoLib_UWP.vcxproj
- Project/Qt/MediaInfoLib.pro
- Source/MediaInfo/File_Other.cpp
- Source/MediaInfo/Image/File_WebP.cpp
- Source/MediaInfo/Image/File_WebP.h
- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/MediaInfo/MediaInfo_File.cpp
- Source/MediaInfo/Setup.h
- Source/Resource/Text/DataBase/Format.csv
Hi, I noticed that WebP didn't work, so thought I'd add it using the info from #1391 
General file info is still handled by the RIFF parser, this just adds basic image stream support. It doesn't rely on libwebp, to keep the binary sizes down. It doesn't do EXIF metadata (that'd need the JPEG EXIF code split out?). I tried to add the .cpp files to all the projects, but only built it on Linux.
Test data with vp8, lossless, alpha channel, animated and iccp colour profiles attached:
[testdata.zip](https://github.com/user-attachments/files/19781107/testdata.zip)
> WebP support

- Project/BCB/Library/MediaInfoLib.cbproj
- Project/CMake/CMakeLists.txt
- Project/GNU/Library/Makefile.am
- Project/GNU/Library/configure.ac
- Project/MSVC2022/Library/MediaInfoLib.vcxproj
- Project/MSVC2022/Library/MediaInfoLib.vcxproj.filters
- Project/MSVC2022/Library/MediaInfoLib_UWP.vcxproj
- Project/Qt/MediaInfoLib.pro
- Source/MediaInfo/Archive/File_MachO.cpp
- Source/MediaInfo/Archive/File_MachO.h
- Source/MediaInfo/File__Analyze_Streams_Finish.cpp
- Source/MediaInfo/MediaInfo_Config_Automatic.cpp
- Source/MediaInfo/MediaInfo_File.cpp
- Source/MediaInfo/Setup.h
- Source/Resource/Text/DataBase/Format.csv
Although I do not have an Apple device, since MediaInfoLib already detects Windows and Linux binaries, I just gave it a try. Not sure what to name stuff or how to present the information.
```
General
Complete name                            : mediainfo
Format                                   : Mach-O
Format profile                           : Mach Object / ARM64
File size                                : 8.04 MiB
FileExtension_Invalid                    : o dylib kext
General
Complete name                            : libmediainfo.0.dylib
Format                                   : Universal Binary
File size                                : 16.9 MiB
Other #1
Type                                     : Binary
Format                                   : Mach-O
Format profile …
```
> Basic Mach-O / Universal Binary detection

- Source/MediaInfo/Image/File_Png.cpp
- Source/MediaInfo/Tag/File_Xmp.cpp
Field is used in images generated by Google Gemini/Imagen. A quick way to check if image is AI generated.
```
General
Complete name                            : Imagen.jpg
Format                                   : JPEG
File size                                : 474 KiB
Credit                                   : Made with Google AI
Image
Format                                   : JPEG
Width                                    : 2 048 pixels
Height                                   : 2 048 pixels
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Compression mode                         : Lossy
Stream size                              : 474 KiB (100%)
```
> XMP: Display `photoshop:Credit` + fix for PNG

- Source/MediaInfo/Multiple/File_Mpeg4.cpp
Map more Arranger, Label, Lyricist and Publisher tags in MP4.
Fix uninitialized variables warnings for File_Mpeg4.cpp.
Resolves #1590
> MP4: Map more tags

- Source/MediaInfo/Text/File_OtherText.cpp
- Limit the size of the buffer sent to From_Unicode as is done for 8-bit encodings
> OtherText: Fix crash when probing file type

- Source/MediaInfo/MediaInfo_Inform.cpp
At the moment only usable with CLI:
```
MediaInfo --cover_data=base64 --output=HTML <filename> > out.html
```
validated for when single file is opened:
> HTML: Display cover image

- Source/MediaInfo/MediaInfo_Internal.cpp
Using references here causes crash on arm with memory tagging extension enabled
> Fix segfault with MTE enabled

- Source/MediaInfo/File__Analyze_Streams.cpp
Fix after #2309 
Discovered that a file with single digit minute coordinate was not zero-padded.
> Location: AddZeroDMS fix

- Source/MediaInfo/Image/File_Jpeg.cpp
- Source/MediaInfo/Image/File_Jpeg.h
- Source/MediaInfo/Tag/File_Xmp.cpp
- Source/MediaInfo/Tag/File_Xmp.h
Extended XMP spans multiple APP1 sections and is used to contain original image and depth map for portrait mode on Android devices.
This PR adds initial parsing, showing the XMP data in trace but does not extract anything from it.
> JPEG: Parse Extended XMP

- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
Parse correctly to fix false conformance errors for test files at https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles/Link-U
> MP4: Handle `iinf` version > 0

- Source/MediaInfo/File__Analyze.h
- Source/MediaInfo/File__Analyze_MinimizeSize.h
- Source/MediaInfo/File__Analyze_Streams.cpp
- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Video/File_Hevc.cpp
- Source/MediaInfo/Video/File_Hevc.h
Parse Ambient viewing environment `amve` box.
> ```
> class AmbientViewingEnvironmentBox extends Box('amve') { 
>     unsigned int(32) ambient_illuminance;
>     unsigned int(16) ambient_light_x;
>     unsigned int(16) ambient_light_y;
> }
> ```
> **ambient_illuminance** specifies the environmental illluminance of the ambient viewing environment in units of 0.0001
lux. ambient_illuminance shall not be equal to 0.
> **ambient_light_x** and **ambient_light_y** specify the normalized x and y chromaticity coordinates, respectively, of the
environmental ambient light in the nominal viewing environment, according to the CIE 1931 definition of x and y as
specified in ISO 11664-1 (see also ISO 11664-3 and CIE 15), in normalized increments of 0.00002. The values of
ambient_light_x and …
> MP4/MOV/HEVC: Ambient viewing environment

- Source/MediaInfo/Video/File_Av1.cpp
- Source/MediaInfo/Video/File_Av1.h
Parse `frame` OBU. Fix parsing `.obu` files and actually parse only the desired `Frame_Count_Valid` number of frames.
Ref: https://github.com/MediaArea/MediaInfo/issues/862#issuecomment-3132816445
> AV1: Fix parsing

- Source/MediaInfo/Text/File_OtherText.cpp
> Fix crashes with glibc's avx2 implementation of wcsncpy

- Source/MediaInfo/Multiple/File_Mpeg4.h
- Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp
- Source/MediaInfo/Video/File_Vp9.cpp
- Source/MediaInfo/Video/File_Vp9.h
`vpcC` is also used for VP8 so maybe there is a better way to do this.
> VP9: VP9 in MP4 support

- .github/workflows/MediaInfoLib_Checks.yml
- Project/CMake/CMakeLists.txt
Also set CMake version range to prevent deprecation warnings.
> CMake: Enable ZLIBSTATIC
